# AUTO-GENERATED by scripts/sync_client.py — DO NOT EDIT
# Source of truth: the flopscope core library (src/flopscope/)
# Regenerate: uv run scripts/sync_client.py
"""Custom exceptions and warnings for the flopscope client."""

from __future__ import annotations


class FlopscopeError(Exception):
    """Base exception for all flopscope errors."""


class BudgetExhaustedError(FlopscopeError):
    """Raised when an operation would exceed the FLOP budget."""

    def __init__(self, message: str = "") -> None:
        super().__init__(message)


class TimeExhaustedError(FlopscopeError):
    """Raised when an operation exceeds the wall-clock time limit."""

    def __init__(self, message: str = "") -> None:
        super().__init__(message)


class NoBudgetContextError(FlopscopeError):
    """Raised when a counted operation is called outside a BudgetContext."""

    def __init__(self, message: str = "") -> None:
        super().__init__(message)


class SymmetryError(FlopscopeError):
    """Raised when a claimed tensor symmetry does not hold."""

    def __init__(self, message: str = "") -> None:
        super().__init__(message)


class UnsupportedFunctionError(FlopscopeError):
    """Raised when calling a function not available in the installed NumPy."""

    def __init__(self, message: str = "") -> None:
        super().__init__(message)


class FlopscopeWarning(UserWarning):
    """Warning issued when flopscope detects potential numerical issues."""


class SymmetryLossWarning(FlopscopeWarning):
    """Warning issued when an operation causes loss of symmetry metadata."""


class FlopscopeServerError(FlopscopeError):
    """Server-side error that does not map to a more specific exception."""


# ---------------------------------------------------------------------------
# Error map and dispatcher
# ---------------------------------------------------------------------------

_FLOPSCOPE_ERRORS: frozenset[str] = frozenset(
    {
        "BudgetExhaustedError",
        "TimeExhaustedError",
        "NoBudgetContextError",
        "SymmetryError",
        "UnsupportedFunctionError",
    }
)

_ERROR_MAP: dict[str, type[Exception]] = {
    "BudgetExhaustedError": BudgetExhaustedError,
    "TimeExhaustedError": TimeExhaustedError,
    "NoBudgetContextError": NoBudgetContextError,
    "SymmetryError": SymmetryError,
    "UnsupportedFunctionError": UnsupportedFunctionError,
    "FlopscopeServerError": FlopscopeServerError,
    "ValueError": ValueError,
    "TypeError": TypeError,
    "KeyError": KeyError,
    "RuntimeError": RuntimeError,
    "InvalidRequestError": FlopscopeServerError,
}


def raise_from_response(error_type: str, message: str) -> None:
    """Map *error_type* string to an exception class and raise it.

    Unknown error types are treated as :class:`FlopscopeServerError`.
    """
    # Ensure message is a str (server may send bytes if it contains non-ASCII)
    if isinstance(message, bytes):
        message = message.decode("utf-8", errors="replace")
    if isinstance(error_type, bytes):
        error_type = error_type.decode("utf-8", errors="replace")

    exc_cls = _ERROR_MAP.get(error_type, FlopscopeServerError)
    if error_type in _FLOPSCOPE_ERRORS:
        raise exc_cls(message=message)
    raise exc_cls(message)
