"""mechestim: NumPy-compatible math primitives with FLOP counting.

Usage::

    import mechestim as me

    with me.BudgetContext(flop_budget=1_000_000) as budget:
        W = me.array(weight_matrix)
        h = me.einsum('ij,j->i', W, x)
        h = me.maximum(h, 0)
        print(budget.summary())
"""

import numpy as _np
from mechestim._registry import REGISTRY_META as _REGISTRY_META

__version__ = f"0.2.0+np{_np.__version__}"
__numpy_version__ = _np.__version__
__numpy_pinned__ = _REGISTRY_META["numpy_version"]

from mechestim._version_check import check_numpy_version as _check_numpy_version
_check_numpy_version(__numpy_pinned__)

# --- Budget and diagnostics ---
from mechestim._budget import BudgetContext, OpRecord  # noqa: F401

# --- Errors ---
from mechestim.errors import (  # noqa: F401
    BudgetExhaustedError,
    MechEstimError,
    MechEstimWarning,
    NoBudgetContextError,
    SymmetryError,
)

# --- Einsum ---
from mechestim._einsum import einsum  # noqa: F401

# --- Pointwise (counted) ---
from mechestim._pointwise import (  # noqa: F401
    abs,
    absolute,
    acos,
    acosh,
    add,
    all,
    amax,
    amin,
    angle,
    any,
    arccos,
    arccosh,
    arcsin,
    arcsinh,
    arctan,
    arctan2,
    arctanh,
    argmax,
    argmin,
    around,
    asin,
    asinh,
    atan,
    atan2,
    atanh,
    average,
    bitwise_and,
    bitwise_count,
    bitwise_invert,
    bitwise_left_shift,
    bitwise_not,
    bitwise_or,
    bitwise_right_shift,
    bitwise_xor,
    cbrt,
    ceil,
    clip,
    conj,
    conjugate,
    copysign,
    convolve,
    corrcoef,
    correlate,
    cos,
    cosh,
    count_nonzero,
    cov,
    cross,
    cumprod,
    cumsum,
    cumulative_prod,
    cumulative_sum,
    deg2rad,
    degrees,
    diff,
    divide,
    divmod,
    dot,
    ediff1d,
    einsum_path,
    equal,
    exp,
    exp2,
    expm1,
    fabs,
    fix,
    float_power,
    floor,
    floor_divide,
    fmax,
    fmin,
    fmod,
    frexp,
    gcd,
    gradient,
    greater,
    greater_equal,
    heaviside,
    hypot,
    i0,
    imag,
    inner,
    interp,
    invert,
    isclose,
    iscomplex,
    iscomplexobj,
    isnat,
    isneginf,
    isposinf,
    isreal,
    isrealobj,
    kron,
    lcm,
    ldexp,
    left_shift,
    less,
    less_equal,
    log,
    log1p,
    log2,
    log10,
    logaddexp,
    logaddexp2,
    logical_and,
    logical_not,
    logical_or,
    logical_xor,
    matmul,
    max,
    maximum,
    mean,
    median,
    min,
    minimum,
    mod,
    modf,
    multiply,
    nan_to_num,
    nanargmax,
    nanargmin,
    nancumprod,
    nancumsum,
    nanmax,
    nanmean,
    nanmedian,
    nanmin,
    nanpercentile,
    nanprod,
    nanquantile,
    nanstd,
    nansum,
    nanvar,
    negative,
    nextafter,
    not_equal,
    outer,
    percentile,
    positive,
    pow,
    power,
    prod,
    ptp,
    quantile,
    rad2deg,
    radians,
    real,
    real_if_close,
    reciprocal,
    remainder,
    right_shift,
    rint,
    round,
    sign,
    signbit,
    sin,
    sinc,
    sinh,
    sort_complex,
    spacing,
    sqrt,
    square,
    std,
    subtract,
    sum,
    tan,
    tanh,
    tensordot,
    trapezoid,
    trapz,
    true_divide,
    trunc,
    var,
    vdot,
    vecdot,
)

# --- Free ops ---
from mechestim._free_ops import (  # noqa: F401
    allclose,
    append,
    arange,
    argpartition,
    argsort,
    argwhere,
    array,
    array_equal,
    array_equiv,
    array_split,
    asarray,
    asarray_chkfinite,
    astype,
    atleast_1d,
    atleast_2d,
    atleast_3d,
    base_repr,
    binary_repr,
    bincount,
    block,
    bmat,
    broadcast_arrays,
    broadcast_shapes,
    broadcast_to,
    can_cast,
    choose,
    column_stack,
    common_type,
    compress,
    concat,
    concatenate,
    copy,
    copyto,
    delete,
    diag,
    diag_indices,
    diag_indices_from,
    diagflat,
    diagonal,
    digitize,
    dsplit,
    dstack,
    empty,
    empty_like,
    expand_dims,
    extract,
    eye,
    fill_diagonal,
    flatnonzero,
    flip,
    fliplr,
    flipud,
    from_dlpack,
    frombuffer,
    fromfile,
    fromfunction,
    fromiter,
    fromregex,
    fromstring,
    full,
    full_like,
    geomspace,
    histogram,
    histogram2d,
    histogram_bin_edges,
    histogramdd,
    hstack,
    hsplit,
    identity,
    in1d,
    indices,
    insert,
    intersect1d,
    isdtype,
    isfinite,
    isfortran,
    isin,
    isinf,
    isnan,
    isscalar,
    issubdtype,
    iterable,
    ix_,
    lexsort,
    linspace,
    logspace,
    mask_indices,
    matrix_transpose,
    may_share_memory,
    meshgrid,
    min_scalar_type,
    mintypecode,
    moveaxis,
    ndim,
    nonzero,
    ones,
    ones_like,
    packbits,
    pad,
    partition,
    permute_dims,
    place,
    promote_types,
    put,
    put_along_axis,
    putmask,
    ravel,
    ravel_multi_index,
    repeat,
    require,
    reshape,
    resize,
    result_type,
    roll,
    rollaxis,
    rot90,
    row_stack,
    searchsorted,
    select,
    setdiff1d,
    setxor1d,
    shape,
    shares_memory,
    size,
    sort,
    split,
    squeeze,
    stack,
    swapaxes,
    take,
    take_along_axis,
    tile,
    trace,
    transpose,
    tri,
    tril,
    tril_indices,
    tril_indices_from,
    trim_zeros,
    triu,
    triu_indices,
    triu_indices_from,
    typename,
    union1d,
    unique,
    unique_all,
    unique_counts,
    unique_inverse,
    unique_values,
    unpackbits,
    unravel_index,
    unstack,
    vander,
    vsplit,
    vstack,
    where,
    zeros,
    zeros_like,
)

# --- Submodules ---
from mechestim import fft  # noqa: F401
from mechestim import flops  # noqa: F401
from mechestim import linalg  # noqa: F401
from mechestim import random  # noqa: F401

# --- NumPy constants and types ---
# _np already imported above for version attributes

pi = _np.pi
e = _np.e
inf = _np.inf
nan = _np.nan
newaxis = _np.newaxis
ndarray = _np.ndarray
float16 = _np.float16
float32 = _np.float32
float64 = _np.float64
int8 = _np.int8
int16 = _np.int16
int32 = _np.int32
int64 = _np.int64
uint8 = _np.uint8
bool_ = _np.bool_
complex64 = _np.complex64
complex128 = _np.complex128


from mechestim._registry import make_module_getattr as _make_module_getattr

__getattr__ = _make_module_getattr(module_prefix="", module_label="mechestim")
