"""Tests for Permutation and PermutationGroup."""

from __future__ import annotations

import math
import pytest

from mechestim._perm_group import Permutation
from mechestim._perm_group import PermutationGroup


class TestPermutation:
    def test_identity(self):
        e = Permutation.identity(3)
        assert e.array_form == [0, 1, 2]
        assert e.size == 3
        assert e.is_identity

    def test_from_array(self):
        p = Permutation([1, 2, 0])
        assert p.array_form == [1, 2, 0]
        assert p.size == 3
        assert not p.is_identity

    def test_from_cycle(self):
        # (0 → 1 → 2 → 0)
        p = Permutation.from_cycle(3, [0, 1, 2])
        assert p.array_form == [1, 2, 0]

    def test_from_cycle_transposition(self):
        p = Permutation.from_cycle(4, [1, 3])
        assert p.array_form == [0, 3, 2, 1]

    def test_compose(self):
        # (0 1 2) * (0 1 2) = (0 2 1)
        p = Permutation([1, 2, 0])
        q = p * p
        assert q.array_form == [2, 0, 1]

    def test_inverse(self):
        p = Permutation([1, 2, 0])
        inv = ~p
        e = p * inv
        assert e.is_identity

    def test_eq_and_hash(self):
        a = Permutation([1, 2, 0])
        b = Permutation([1, 2, 0])
        c = Permutation([2, 0, 1])
        assert a == b
        assert a != c
        assert hash(a) == hash(b)
        assert len({a, b, c}) == 2

    def test_cyclic_form(self):
        p = Permutation([1, 2, 0])
        assert p.cyclic_form == [(0, 1, 2)]

    def test_cyclic_form_two_cycles(self):
        # (0 1)(2 3)
        p = Permutation([1, 0, 3, 2])
        cycles = p.cyclic_form
        assert len(cycles) == 2
        assert set(map(frozenset, cycles)) == {frozenset({0, 1}), frozenset({2, 3})}

    def test_cyclic_form_identity(self):
        assert Permutation.identity(3).cyclic_form == []

    def test_full_cyclic_form_includes_fixed_points(self):
        # (0 1) on size 4: fixed points 2, 3 become 1-cycles
        p = Permutation([1, 0, 2, 3])
        full = p.full_cyclic_form
        # Should cover every position exactly once
        all_positions = sorted(pos for cycle in full for pos in cycle)
        assert all_positions == [0, 1, 2, 3]

    def test_cycle_structure(self):
        # (0 1 2) = one 3-cycle
        p = Permutation([1, 2, 0])
        assert p.cycle_structure == {3: 1}

    def test_cycle_structure_mixed(self):
        # (0 1)(2 3 4) on size 5 → {2: 1, 3: 1}
        p = Permutation([1, 0, 3, 4, 2])
        assert p.cycle_structure == {2: 1, 3: 1}

    def test_order(self):
        # (0 1 2) has order 3
        assert Permutation([1, 2, 0]).order == 3
        # (0 1)(2 3 4) has order lcm(2,3) = 6
        assert Permutation([1, 0, 3, 4, 2]).order == 6
        # identity has order 1
        assert Permutation.identity(5).order == 1


class TestPermutationGroup:
    def test_symmetric_2(self):
        """S_2 has order 2."""
        g = PermutationGroup.symmetric(2)
        assert g.degree == 2
        assert g.order() == 2
        assert g.is_symmetric()

    def test_symmetric_3(self):
        """S_3 has order 6."""
        g = PermutationGroup.symmetric(3)
        assert g.order() == 6
        assert g.is_symmetric()

    def test_cyclic_3(self):
        """C_3 has order 3, is NOT the full symmetric group."""
        g = PermutationGroup.cyclic(3)
        assert g.order() == 3
        assert not g.is_symmetric()
        elems = g.elements()
        assert len(elems) == 3
        assert Permutation.identity(3) in elems
        assert Permutation([1, 2, 0]) in elems
        assert Permutation([2, 0, 1]) in elems

    def test_cyclic_4(self):
        """C_4 has order 4."""
        g = PermutationGroup.cyclic(4)
        assert g.order() == 4
        assert not g.is_symmetric()

    def test_dihedral_3(self):
        """D_3 = S_3 has order 6."""
        g = PermutationGroup.dihedral(3)
        assert g.order() == 6
        assert g.is_symmetric()

    def test_dihedral_4(self):
        """D_4 has order 8, which is < 4! = 24."""
        g = PermutationGroup.dihedral(4)
        assert g.order() == 8
        assert not g.is_symmetric()

    def test_from_generators(self):
        """Group generated by a single transposition (0 1) on 3 points has order 2."""
        gen = Permutation.from_cycle(3, [0, 1])
        g = PermutationGroup(gen)
        assert g.order() == 2
        assert not g.is_symmetric()

    def test_elements_cached(self):
        g = PermutationGroup.symmetric(3)
        e1 = g.elements()
        e2 = g.elements()
        assert e1 is e2

    def test_axes(self):
        g = PermutationGroup.cyclic(3, axes=(2, 5, 7))
        assert g.axes == (2, 5, 7)
        assert g.degree == 3

    def test_orbits_transitive(self):
        """S_3 is transitive: one orbit = {0, 1, 2}."""
        g = PermutationGroup.symmetric(3)
        orbs = g.orbits()
        assert len(orbs) == 1
        assert orbs[0] == frozenset({0, 1, 2})

    def test_orbits_intransitive(self):
        """(0 1) on 4 points: orbits = {0,1}, {2}, {3}."""
        gen = Permutation.from_cycle(4, [0, 1])
        g = PermutationGroup(gen)
        orbs = sorted(g.orbits(), key=lambda s: min(s))
        assert orbs == [frozenset({0, 1}), frozenset({2}), frozenset({3})]


class TestBurnsideCount:
    def test_s2_matches_stars_and_bars(self):
        """S_2 on two dims of size n: C(n+1, 2)."""
        g = PermutationGroup.symmetric(2)
        for n in [3, 5, 10]:
            expected = math.comb(n + 1, 2)
            assert g.burnside_unique_count({0: n, 1: n}) == expected

    def test_s3_matches_stars_and_bars(self):
        """S_3 on three dims of size n: C(n+2, 3)."""
        g = PermutationGroup.symmetric(3)
        for n in [3, 5, 10]:
            expected = math.comb(n + 2, 3)
            assert g.burnside_unique_count({0: n, 1: n, 2: n}) == expected

    def test_c3_differs_from_s3(self):
        """C_3 unique count = (n^3 + 2n) / 3, which differs from S_3."""
        g = PermutationGroup.cyclic(3)
        for n in [3, 5, 10]:
            expected_c3 = (n**3 + 2 * n) // 3
            expected_s3 = math.comb(n + 2, 3)
            result = g.burnside_unique_count({0: n, 1: n, 2: n})
            assert result == expected_c3
            assert result > expected_s3

    def test_c4_burnside(self):
        """C_4 unique count for n=3: verify it's between C_4 and S_4 results."""
        g = PermutationGroup.cyclic(4)
        n = 3
        result = g.burnside_unique_count({0: n, 1: n, 2: n, 3: n})
        s4_result = math.comb(n + 3, 4)
        assert result > s4_result
        assert result < n**4

    def test_identity_group(self):
        """Trivial group (identity only) on k dims: all elements unique = n^k."""
        e = Permutation.identity(3)
        g = PermutationGroup(e)
        assert g.order() == 1
        assert g.burnside_unique_count({0: 5, 1: 5, 2: 5}) == 125

    def test_heterogeneous_sizes_raises(self):
        """Positions in the same orbit must have equal sizes."""
        g = PermutationGroup.symmetric(2)
        with pytest.raises(ValueError, match="same dimension size"):
            g.burnside_unique_count({0: 3, 1: 5})
