# AUTO-GENERATED by scripts/sync_client.py — DO NOT EDIT
# Source of truth: the mechestim core library (src/mechestim/)
# Regenerate: uv run scripts/sync_client.py
"""Custom exceptions and warnings for the mechestim client."""

from __future__ import annotations


class MechEstimError(Exception):
    """Base exception for all mechestim errors."""


class BudgetExhaustedError(MechEstimError):
    """Raised when an operation would exceed the FLOP budget."""

    def __init__(self, message: str = "") -> None:
        super().__init__(message)


class NoBudgetContextError(MechEstimError):
    """Raised when a counted operation is called outside a BudgetContext."""

    def __init__(self, message: str = "") -> None:
        super().__init__(message)


class SymmetryError(MechEstimError):
    """Raised when a claimed tensor symmetry does not hold."""

    def __init__(self, message: str = "") -> None:
        super().__init__(message)


class UnsupportedFunctionError(MechEstimError):
    """Raised when calling a function not available in the installed NumPy."""

    def __init__(self, message: str = "") -> None:
        super().__init__(message)


class MechEstimWarning(UserWarning):
    """Warning issued when mechestim detects potential numerical issues."""


class SymmetryLossWarning(MechEstimWarning):
    """Warning issued when an operation causes loss of symmetry metadata."""


class MechEstimServerError(MechEstimError):
    """Server-side error that does not map to a more specific exception."""


# ---------------------------------------------------------------------------
# Error map and dispatcher
# ---------------------------------------------------------------------------

_MECHESTIM_ERRORS: frozenset[str] = frozenset(
    {
        "BudgetExhaustedError",
        "NoBudgetContextError",
        "SymmetryError",
        "UnsupportedFunctionError",
    }
)

_ERROR_MAP: dict[str, type[Exception]] = {
    "BudgetExhaustedError": BudgetExhaustedError,
    "NoBudgetContextError": NoBudgetContextError,
    "SymmetryError": SymmetryError,
    "UnsupportedFunctionError": UnsupportedFunctionError,
    "MechEstimServerError": MechEstimServerError,
    "ValueError": ValueError,
    "TypeError": TypeError,
    "KeyError": KeyError,
    "RuntimeError": RuntimeError,
    "InvalidRequestError": MechEstimServerError,
}


def raise_from_response(error_type: str, message: str) -> None:
    """Map *error_type* string to an exception class and raise it.

    Unknown error types are treated as :class:`MechEstimServerError`.
    """
    # Ensure message is a str (server may send bytes if it contains non-ASCII)
    if isinstance(message, bytes):
        message = message.decode("utf-8", errors="replace")
    if isinstance(error_type, bytes):
        error_type = error_type.decode("utf-8", errors="replace")

    exc_cls = _ERROR_MAP.get(error_type, MechEstimServerError)
    if error_type in _MECHESTIM_ERRORS:
        raise exc_cls(message=message)
    raise exc_cls(message)
