# AUTO-GENERATED by scripts/sync_client.py — DO NOT EDIT
# Source of truth: the flopscope core library (src/flopscope/)
# Regenerate: uv run scripts/sync_client.py
"""flopscope.stats — statistical distributions submodule proxy."""

from __future__ import annotations

from flopscope._connection import get_connection
from flopscope._getattr import make_module_getattr
from flopscope._protocol import encode_request
from flopscope._remote_array import (
    _encode_arg,
    _result_from_response,
)


class _DistributionProxy:
    """Proxy for a server-side statistical distribution."""

    def __init__(self, name: str) -> None:
        self._name = name

    def __repr__(self) -> str:
        return f"<flopscope.stats.{self._name}>"

    def pdf(self, x, *args, **kwargs):
        """Dispatch stats.{self._name}.pdf to the server."""
        conn = get_connection()
        op = f"stats.{self._name}.pdf"
        encoded_args = [_encode_arg(x)] + [_encode_arg(a) for a in args]
        encoded_kwargs = {k: _encode_arg(v) for k, v in kwargs.items()}
        resp = conn.send_recv(
            encode_request(op, args=encoded_args, kwargs=encoded_kwargs)
        )
        return _result_from_response(resp)

    def cdf(self, x, *args, **kwargs):
        """Dispatch stats.{self._name}.cdf to the server."""
        conn = get_connection()
        op = f"stats.{self._name}.cdf"
        encoded_args = [_encode_arg(x)] + [_encode_arg(a) for a in args]
        encoded_kwargs = {k: _encode_arg(v) for k, v in kwargs.items()}
        resp = conn.send_recv(
            encode_request(op, args=encoded_args, kwargs=encoded_kwargs)
        )
        return _result_from_response(resp)

    def ppf(self, x, *args, **kwargs):
        """Dispatch stats.{self._name}.ppf to the server."""
        conn = get_connection()
        op = f"stats.{self._name}.ppf"
        encoded_args = [_encode_arg(x)] + [_encode_arg(a) for a in args]
        encoded_kwargs = {k: _encode_arg(v) for k, v in kwargs.items()}
        resp = conn.send_recv(
            encode_request(op, args=encoded_args, kwargs=encoded_kwargs)
        )
        return _result_from_response(resp)


# Distribution instances
cauchy = _DistributionProxy("cauchy")
expon = _DistributionProxy("expon")
laplace = _DistributionProxy("laplace")
logistic = _DistributionProxy("logistic")
lognorm = _DistributionProxy("lognorm")
norm = _DistributionProxy("norm")
truncnorm = _DistributionProxy("truncnorm")
uniform = _DistributionProxy("uniform")

__all__ = [
    "cauchy",
    "expon",
    "laplace",
    "logistic",
    "lognorm",
    "norm",
    "truncnorm",
    "uniform",
]

# Fall-through for unknown names
__getattr__ = make_module_getattr("stats.", "flopscope.stats")
