FROM python:3.10-slim
WORKDIR /app
COPY . /app/mechestim-lib/
COPY mechestim-server/ /app/mechestim-server/
RUN pip install --no-cache-dir /app/mechestim-lib/ /app/mechestim-server/
CMD ["python", "-m", "mechestim_server", "--url", "ipc:///tmp/mechestim.sock"]
