"""Linear algebra submodule for whest."""

from whest._registry import make_module_getattr as _make_module_getattr
from whest.linalg._aliases import (  # noqa: F401
    cross,
    diagonal,
    matmul,
    matrix_transpose,
    outer,
    tensordot,
    vecdot,
)
from whest.linalg._compound import (  # noqa: F401
    matrix_power,
    matrix_power_cost,
    multi_dot,
    multi_dot_cost,
)
from whest.linalg._decompositions import (  # noqa: F401
    cholesky,
    cholesky_cost,
    eig,
    eig_cost,
    eigh,
    eigh_cost,
    eigvals,
    eigvals_cost,
    eigvalsh,
    eigvalsh_cost,
    qr,
    qr_cost,
    svdvals,
    svdvals_cost,
)
from whest.linalg._properties import (  # noqa: F401
    cond,
    cond_cost,
    det,
    det_cost,
    matrix_norm,
    matrix_norm_cost,
    matrix_rank,
    matrix_rank_cost,
    norm,
    norm_cost,
    slogdet,
    slogdet_cost,
    trace,
    trace_cost,
    vector_norm,
    vector_norm_cost,
)
from whest.linalg._solvers import (  # noqa: F401
    inv,
    inv_cost,
    lstsq,
    lstsq_cost,
    pinv,
    pinv_cost,
    solve,
    solve_cost,
    tensorinv,
    tensorinv_cost,
    tensorsolve,
    tensorsolve_cost,
)
from whest.linalg._svd import svd  # noqa: F401

__all__ = [
    "svd",
    "matmul",
    "cross",
    "outer",
    "tensordot",
    "vecdot",
    "diagonal",
    "matrix_transpose",
    "cholesky",
    "qr",
    "eig",
    "eigh",
    "eigvals",
    "eigvalsh",
    "svdvals",
    "solve",
    "inv",
    "lstsq",
    "pinv",
    "tensorsolve",
    "tensorinv",
    "trace",
    "det",
    "slogdet",
    "norm",
    "vector_norm",
    "matrix_norm",
    "cond",
    "matrix_rank",
    "multi_dot",
    "matrix_power",
]

__getattr__ = _make_module_getattr(module_prefix="linalg.", module_label="whest.linalg")
