export const opDocImports: Record<string, () => Promise<{ default: unknown }>> = {
  "absolute": () => import("./ops/absolute.json"),
  "add": () => import("./ops/add.json"),
  "all": () => import("./ops/all.json"),
  "allclose": () => import("./ops/allclose.json"),
  "angle": () => import("./ops/angle.json"),
  "any": () => import("./ops/any.json"),
  "append": () => import("./ops/append.json"),
  "apply_along_axis": () => import("./ops/apply_along_axis.json"),
  "apply_over_axes": () => import("./ops/apply_over_axes.json"),
  "arange": () => import("./ops/arange.json"),
  "arccos": () => import("./ops/arccos.json"),
  "arccosh": () => import("./ops/arccosh.json"),
  "arcsin": () => import("./ops/arcsin.json"),
  "arcsinh": () => import("./ops/arcsinh.json"),
  "arctan": () => import("./ops/arctan.json"),
  "arctan2": () => import("./ops/arctan2.json"),
  "arctanh": () => import("./ops/arctanh.json"),
  "argmax": () => import("./ops/argmax.json"),
  "argmin": () => import("./ops/argmin.json"),
  "argpartition": () => import("./ops/argpartition.json"),
  "argsort": () => import("./ops/argsort.json"),
  "argwhere": () => import("./ops/argwhere.json"),
  "array": () => import("./ops/array.json"),
  "array_equal": () => import("./ops/array_equal.json"),
  "array_equiv": () => import("./ops/array_equiv.json"),
  "array_split": () => import("./ops/array_split.json"),
  "asarray": () => import("./ops/asarray.json"),
  "asarray_chkfinite": () => import("./ops/asarray_chkfinite.json"),
  "astype": () => import("./ops/astype.json"),
  "atleast_1d": () => import("./ops/atleast_1d.json"),
  "atleast_2d": () => import("./ops/atleast_2d.json"),
  "atleast_3d": () => import("./ops/atleast_3d.json"),
  "average": () => import("./ops/average.json"),
  "bartlett": () => import("./ops/bartlett.json"),
  "bincount": () => import("./ops/bincount.json"),
  "bitwise_and": () => import("./ops/bitwise_and.json"),
  "bitwise_count": () => import("./ops/bitwise_count.json"),
  "bitwise_left_shift": () => import("./ops/bitwise_left_shift.json"),
  "bitwise_not": () => import("./ops/bitwise_not.json"),
  "bitwise_or": () => import("./ops/bitwise_or.json"),
  "bitwise_right_shift": () => import("./ops/bitwise_right_shift.json"),
  "bitwise_xor": () => import("./ops/bitwise_xor.json"),
  "blackman": () => import("./ops/blackman.json"),
  "block": () => import("./ops/block.json"),
  "bmat": () => import("./ops/bmat.json"),
  "broadcast_arrays": () => import("./ops/broadcast_arrays.json"),
  "broadcast_shapes": () => import("./ops/broadcast_shapes.json"),
  "broadcast_to": () => import("./ops/broadcast_to.json"),
  "can_cast": () => import("./ops/can_cast.json"),
  "cbrt": () => import("./ops/cbrt.json"),
  "ceil": () => import("./ops/ceil.json"),
  "choose": () => import("./ops/choose.json"),
  "clip": () => import("./ops/clip.json"),
  "column_stack": () => import("./ops/column_stack.json"),
  "common_type": () => import("./ops/common_type.json"),
  "compress": () => import("./ops/compress.json"),
  "concatenate": () => import("./ops/concatenate.json"),
  "conj": () => import("./ops/conj.json"),
  "conjugate": () => import("./ops/conjugate.json"),
  "convolve": () => import("./ops/convolve.json"),
  "copy": () => import("./ops/copy.json"),
  "copysign": () => import("./ops/copysign.json"),
  "copyto": () => import("./ops/copyto.json"),
  "corrcoef": () => import("./ops/corrcoef.json"),
  "correlate": () => import("./ops/correlate.json"),
  "cos": () => import("./ops/cos.json"),
  "cosh": () => import("./ops/cosh.json"),
  "count_nonzero": () => import("./ops/count_nonzero.json"),
  "cov": () => import("./ops/cov.json"),
  "cross": () => import("./ops/cross.json"),
  "cumprod": () => import("./ops/cumprod.json"),
  "cumsum": () => import("./ops/cumsum.json"),
  "cumulative_prod": () => import("./ops/cumulative_prod.json"),
  "cumulative_sum": () => import("./ops/cumulative_sum.json"),
  "degrees": () => import("./ops/degrees.json"),
  "delete": () => import("./ops/delete.json"),
  "diag": () => import("./ops/diag.json"),
  "diag_indices": () => import("./ops/diag_indices.json"),
  "diag_indices_from": () => import("./ops/diag_indices_from.json"),
  "diagflat": () => import("./ops/diagflat.json"),
  "diagonal": () => import("./ops/diagonal.json"),
  "diff": () => import("./ops/diff.json"),
  "digitize": () => import("./ops/digitize.json"),
  "divide": () => import("./ops/divide.json"),
  "dot": () => import("./ops/dot.json"),
  "dsplit": () => import("./ops/dsplit.json"),
  "dstack": () => import("./ops/dstack.json"),
  "ediff1d": () => import("./ops/ediff1d.json"),
  "einsum": () => import("./ops/einsum.json"),
  "einsum_path": () => import("./ops/einsum_path.json"),
  "empty": () => import("./ops/empty.json"),
  "empty_like": () => import("./ops/empty_like.json"),
  "equal": () => import("./ops/equal.json"),
  "exp": () => import("./ops/exp.json"),
  "exp2": () => import("./ops/exp2.json"),
  "expand_dims": () => import("./ops/expand_dims.json"),
  "expm1": () => import("./ops/expm1.json"),
  "extract": () => import("./ops/extract.json"),
  "eye": () => import("./ops/eye.json"),
  "fabs": () => import("./ops/fabs.json"),
  "fft-fft": () => import("./ops/fft-fft.json"),
  "fft-fft2": () => import("./ops/fft-fft2.json"),
  "fft-fftfreq": () => import("./ops/fft-fftfreq.json"),
  "fft-fftn": () => import("./ops/fft-fftn.json"),
  "fft-fftshift": () => import("./ops/fft-fftshift.json"),
  "fft-hfft": () => import("./ops/fft-hfft.json"),
  "fft-ifft": () => import("./ops/fft-ifft.json"),
  "fft-ifft2": () => import("./ops/fft-ifft2.json"),
  "fft-ifftn": () => import("./ops/fft-ifftn.json"),
  "fft-ifftshift": () => import("./ops/fft-ifftshift.json"),
  "fft-ihfft": () => import("./ops/fft-ihfft.json"),
  "fft-irfft": () => import("./ops/fft-irfft.json"),
  "fft-irfft2": () => import("./ops/fft-irfft2.json"),
  "fft-irfftn": () => import("./ops/fft-irfftn.json"),
  "fft-rfft": () => import("./ops/fft-rfft.json"),
  "fft-rfft2": () => import("./ops/fft-rfft2.json"),
  "fft-rfftfreq": () => import("./ops/fft-rfftfreq.json"),
  "fft-rfftn": () => import("./ops/fft-rfftn.json"),
  "fill_diagonal": () => import("./ops/fill_diagonal.json"),
  "flatnonzero": () => import("./ops/flatnonzero.json"),
  "flip": () => import("./ops/flip.json"),
  "fliplr": () => import("./ops/fliplr.json"),
  "flipud": () => import("./ops/flipud.json"),
  "float_power": () => import("./ops/float_power.json"),
  "floor": () => import("./ops/floor.json"),
  "floor_divide": () => import("./ops/floor_divide.json"),
  "fmax": () => import("./ops/fmax.json"),
  "fmin": () => import("./ops/fmin.json"),
  "fmod": () => import("./ops/fmod.json"),
  "frexp": () => import("./ops/frexp.json"),
  "from_dlpack": () => import("./ops/from_dlpack.json"),
  "frombuffer": () => import("./ops/frombuffer.json"),
  "fromfunction": () => import("./ops/fromfunction.json"),
  "fromiter": () => import("./ops/fromiter.json"),
  "full": () => import("./ops/full.json"),
  "full_like": () => import("./ops/full_like.json"),
  "gcd": () => import("./ops/gcd.json"),
  "geomspace": () => import("./ops/geomspace.json"),
  "gradient": () => import("./ops/gradient.json"),
  "greater": () => import("./ops/greater.json"),
  "greater_equal": () => import("./ops/greater_equal.json"),
  "hamming": () => import("./ops/hamming.json"),
  "hanning": () => import("./ops/hanning.json"),
  "heaviside": () => import("./ops/heaviside.json"),
  "histogram": () => import("./ops/histogram.json"),
  "histogram2d": () => import("./ops/histogram2d.json"),
  "histogram_bin_edges": () => import("./ops/histogram_bin_edges.json"),
  "histogramdd": () => import("./ops/histogramdd.json"),
  "hsplit": () => import("./ops/hsplit.json"),
  "hstack": () => import("./ops/hstack.json"),
  "hypot": () => import("./ops/hypot.json"),
  "i0": () => import("./ops/i0.json"),
  "identity": () => import("./ops/identity.json"),
  "imag": () => import("./ops/imag.json"),
  "in1d": () => import("./ops/in1d.json"),
  "indices": () => import("./ops/indices.json"),
  "inner": () => import("./ops/inner.json"),
  "insert": () => import("./ops/insert.json"),
  "interp": () => import("./ops/interp.json"),
  "intersect1d": () => import("./ops/intersect1d.json"),
  "invert": () => import("./ops/invert.json"),
  "isclose": () => import("./ops/isclose.json"),
  "iscomplex": () => import("./ops/iscomplex.json"),
  "iscomplexobj": () => import("./ops/iscomplexobj.json"),
  "isdtype": () => import("./ops/isdtype.json"),
  "isfinite": () => import("./ops/isfinite.json"),
  "isfortran": () => import("./ops/isfortran.json"),
  "isin": () => import("./ops/isin.json"),
  "isinf": () => import("./ops/isinf.json"),
  "isnan": () => import("./ops/isnan.json"),
  "isneginf": () => import("./ops/isneginf.json"),
  "isposinf": () => import("./ops/isposinf.json"),
  "isreal": () => import("./ops/isreal.json"),
  "isrealobj": () => import("./ops/isrealobj.json"),
  "isscalar": () => import("./ops/isscalar.json"),
  "issubdtype": () => import("./ops/issubdtype.json"),
  "iterable": () => import("./ops/iterable.json"),
  "ix_": () => import("./ops/ix_.json"),
  "kaiser": () => import("./ops/kaiser.json"),
  "kron": () => import("./ops/kron.json"),
  "lcm": () => import("./ops/lcm.json"),
  "ldexp": () => import("./ops/ldexp.json"),
  "left_shift": () => import("./ops/left_shift.json"),
  "less": () => import("./ops/less.json"),
  "less_equal": () => import("./ops/less_equal.json"),
  "lexsort": () => import("./ops/lexsort.json"),
  "linalg-cholesky": () => import("./ops/linalg-cholesky.json"),
  "linalg-cond": () => import("./ops/linalg-cond.json"),
  "linalg-cross": () => import("./ops/linalg-cross.json"),
  "linalg-det": () => import("./ops/linalg-det.json"),
  "linalg-diagonal": () => import("./ops/linalg-diagonal.json"),
  "linalg-eig": () => import("./ops/linalg-eig.json"),
  "linalg-eigh": () => import("./ops/linalg-eigh.json"),
  "linalg-eigvals": () => import("./ops/linalg-eigvals.json"),
  "linalg-eigvalsh": () => import("./ops/linalg-eigvalsh.json"),
  "linalg-inv": () => import("./ops/linalg-inv.json"),
  "linalg-lstsq": () => import("./ops/linalg-lstsq.json"),
  "linalg-matmul": () => import("./ops/linalg-matmul.json"),
  "linalg-matrix_norm": () => import("./ops/linalg-matrix_norm.json"),
  "linalg-matrix_power": () => import("./ops/linalg-matrix_power.json"),
  "linalg-matrix_rank": () => import("./ops/linalg-matrix_rank.json"),
  "linalg-matrix_transpose": () => import("./ops/linalg-matrix_transpose.json"),
  "linalg-multi_dot": () => import("./ops/linalg-multi_dot.json"),
  "linalg-norm": () => import("./ops/linalg-norm.json"),
  "linalg-outer": () => import("./ops/linalg-outer.json"),
  "linalg-pinv": () => import("./ops/linalg-pinv.json"),
  "linalg-qr": () => import("./ops/linalg-qr.json"),
  "linalg-slogdet": () => import("./ops/linalg-slogdet.json"),
  "linalg-solve": () => import("./ops/linalg-solve.json"),
  "linalg-svd": () => import("./ops/linalg-svd.json"),
  "linalg-svdvals": () => import("./ops/linalg-svdvals.json"),
  "linalg-tensordot": () => import("./ops/linalg-tensordot.json"),
  "linalg-tensorinv": () => import("./ops/linalg-tensorinv.json"),
  "linalg-tensorsolve": () => import("./ops/linalg-tensorsolve.json"),
  "linalg-trace": () => import("./ops/linalg-trace.json"),
  "linalg-vecdot": () => import("./ops/linalg-vecdot.json"),
  "linalg-vector_norm": () => import("./ops/linalg-vector_norm.json"),
  "linspace": () => import("./ops/linspace.json"),
  "log": () => import("./ops/log.json"),
  "log10": () => import("./ops/log10.json"),
  "log1p": () => import("./ops/log1p.json"),
  "log2": () => import("./ops/log2.json"),
  "logaddexp": () => import("./ops/logaddexp.json"),
  "logaddexp2": () => import("./ops/logaddexp2.json"),
  "logical_and": () => import("./ops/logical_and.json"),
  "logical_not": () => import("./ops/logical_not.json"),
  "logical_or": () => import("./ops/logical_or.json"),
  "logical_xor": () => import("./ops/logical_xor.json"),
  "logspace": () => import("./ops/logspace.json"),
  "mask_indices": () => import("./ops/mask_indices.json"),
  "matmul": () => import("./ops/matmul.json"),
  "matrix_transpose": () => import("./ops/matrix_transpose.json"),
  "matvec": () => import("./ops/matvec.json"),
  "max": () => import("./ops/max.json"),
  "maximum": () => import("./ops/maximum.json"),
  "may_share_memory": () => import("./ops/may_share_memory.json"),
  "mean": () => import("./ops/mean.json"),
  "median": () => import("./ops/median.json"),
  "meshgrid": () => import("./ops/meshgrid.json"),
  "min": () => import("./ops/min.json"),
  "min_scalar_type": () => import("./ops/min_scalar_type.json"),
  "minimum": () => import("./ops/minimum.json"),
  "mintypecode": () => import("./ops/mintypecode.json"),
  "mod": () => import("./ops/mod.json"),
  "modf": () => import("./ops/modf.json"),
  "moveaxis": () => import("./ops/moveaxis.json"),
  "multiply": () => import("./ops/multiply.json"),
  "nan_to_num": () => import("./ops/nan_to_num.json"),
  "nanargmax": () => import("./ops/nanargmax.json"),
  "nanargmin": () => import("./ops/nanargmin.json"),
  "nancumprod": () => import("./ops/nancumprod.json"),
  "nancumsum": () => import("./ops/nancumsum.json"),
  "nanmax": () => import("./ops/nanmax.json"),
  "nanmean": () => import("./ops/nanmean.json"),
  "nanmedian": () => import("./ops/nanmedian.json"),
  "nanmin": () => import("./ops/nanmin.json"),
  "nanpercentile": () => import("./ops/nanpercentile.json"),
  "nanprod": () => import("./ops/nanprod.json"),
  "nanquantile": () => import("./ops/nanquantile.json"),
  "nanstd": () => import("./ops/nanstd.json"),
  "nansum": () => import("./ops/nansum.json"),
  "nanvar": () => import("./ops/nanvar.json"),
  "ndim": () => import("./ops/ndim.json"),
  "negative": () => import("./ops/negative.json"),
  "nextafter": () => import("./ops/nextafter.json"),
  "nonzero": () => import("./ops/nonzero.json"),
  "not_equal": () => import("./ops/not_equal.json"),
  "ones": () => import("./ops/ones.json"),
  "ones_like": () => import("./ops/ones_like.json"),
  "outer": () => import("./ops/outer.json"),
  "packbits": () => import("./ops/packbits.json"),
  "pad": () => import("./ops/pad.json"),
  "partition": () => import("./ops/partition.json"),
  "percentile": () => import("./ops/percentile.json"),
  "permute_dims": () => import("./ops/permute_dims.json"),
  "piecewise": () => import("./ops/piecewise.json"),
  "place": () => import("./ops/place.json"),
  "poly": () => import("./ops/poly.json"),
  "polyadd": () => import("./ops/polyadd.json"),
  "polyder": () => import("./ops/polyder.json"),
  "polydiv": () => import("./ops/polydiv.json"),
  "polyfit": () => import("./ops/polyfit.json"),
  "polyint": () => import("./ops/polyint.json"),
  "polymul": () => import("./ops/polymul.json"),
  "polysub": () => import("./ops/polysub.json"),
  "polyval": () => import("./ops/polyval.json"),
  "positive": () => import("./ops/positive.json"),
  "power": () => import("./ops/power.json"),
  "prod": () => import("./ops/prod.json"),
  "promote_types": () => import("./ops/promote_types.json"),
  "ptp": () => import("./ops/ptp.json"),
  "put": () => import("./ops/put.json"),
  "put_along_axis": () => import("./ops/put_along_axis.json"),
  "putmask": () => import("./ops/putmask.json"),
  "quantile": () => import("./ops/quantile.json"),
  "radians": () => import("./ops/radians.json"),
  "random-beta": () => import("./ops/random-beta.json"),
  "random-binomial": () => import("./ops/random-binomial.json"),
  "random-bytes": () => import("./ops/random-bytes.json"),
  "random-chisquare": () => import("./ops/random-chisquare.json"),
  "random-choice": () => import("./ops/random-choice.json"),
  "random-default_rng": () => import("./ops/random-default_rng.json"),
  "random-dirichlet": () => import("./ops/random-dirichlet.json"),
  "random-exponential": () => import("./ops/random-exponential.json"),
  "random-f": () => import("./ops/random-f.json"),
  "random-gamma": () => import("./ops/random-gamma.json"),
  "random-geometric": () => import("./ops/random-geometric.json"),
  "random-get_state": () => import("./ops/random-get_state.json"),
  "random-gumbel": () => import("./ops/random-gumbel.json"),
  "random-hypergeometric": () => import("./ops/random-hypergeometric.json"),
  "random-laplace": () => import("./ops/random-laplace.json"),
  "random-logistic": () => import("./ops/random-logistic.json"),
  "random-lognormal": () => import("./ops/random-lognormal.json"),
  "random-logseries": () => import("./ops/random-logseries.json"),
  "random-multinomial": () => import("./ops/random-multinomial.json"),
  "random-multivariate_normal": () => import("./ops/random-multivariate_normal.json"),
  "random-negative_binomial": () => import("./ops/random-negative_binomial.json"),
  "random-noncentral_chisquare": () => import("./ops/random-noncentral_chisquare.json"),
  "random-noncentral_f": () => import("./ops/random-noncentral_f.json"),
  "random-normal": () => import("./ops/random-normal.json"),
  "random-pareto": () => import("./ops/random-pareto.json"),
  "random-permutation": () => import("./ops/random-permutation.json"),
  "random-poisson": () => import("./ops/random-poisson.json"),
  "random-power": () => import("./ops/random-power.json"),
  "random-rand": () => import("./ops/random-rand.json"),
  "random-randint": () => import("./ops/random-randint.json"),
  "random-randn": () => import("./ops/random-randn.json"),
  "random-random": () => import("./ops/random-random.json"),
  "random-random_integers": () => import("./ops/random-random_integers.json"),
  "random-random_sample": () => import("./ops/random-random_sample.json"),
  "random-rayleigh": () => import("./ops/random-rayleigh.json"),
  "random-seed": () => import("./ops/random-seed.json"),
  "random-set_state": () => import("./ops/random-set_state.json"),
  "random-shuffle": () => import("./ops/random-shuffle.json"),
  "random-standard_cauchy": () => import("./ops/random-standard_cauchy.json"),
  "random-standard_exponential": () => import("./ops/random-standard_exponential.json"),
  "random-standard_gamma": () => import("./ops/random-standard_gamma.json"),
  "random-standard_normal": () => import("./ops/random-standard_normal.json"),
  "random-standard_t": () => import("./ops/random-standard_t.json"),
  "random-triangular": () => import("./ops/random-triangular.json"),
  "random-uniform": () => import("./ops/random-uniform.json"),
  "random-vonmises": () => import("./ops/random-vonmises.json"),
  "random-wald": () => import("./ops/random-wald.json"),
  "random-weibull": () => import("./ops/random-weibull.json"),
  "random-zipf": () => import("./ops/random-zipf.json"),
  "ravel": () => import("./ops/ravel.json"),
  "ravel_multi_index": () => import("./ops/ravel_multi_index.json"),
  "real": () => import("./ops/real.json"),
  "real_if_close": () => import("./ops/real_if_close.json"),
  "reciprocal": () => import("./ops/reciprocal.json"),
  "remainder": () => import("./ops/remainder.json"),
  "repeat": () => import("./ops/repeat.json"),
  "require": () => import("./ops/require.json"),
  "reshape": () => import("./ops/reshape.json"),
  "resize": () => import("./ops/resize.json"),
  "result_type": () => import("./ops/result_type.json"),
  "right_shift": () => import("./ops/right_shift.json"),
  "rint": () => import("./ops/rint.json"),
  "roll": () => import("./ops/roll.json"),
  "rollaxis": () => import("./ops/rollaxis.json"),
  "roots": () => import("./ops/roots.json"),
  "rot90": () => import("./ops/rot90.json"),
  "row_stack": () => import("./ops/row_stack.json"),
  "searchsorted": () => import("./ops/searchsorted.json"),
  "select": () => import("./ops/select.json"),
  "setdiff1d": () => import("./ops/setdiff1d.json"),
  "setxor1d": () => import("./ops/setxor1d.json"),
  "shape": () => import("./ops/shape.json"),
  "shares_memory": () => import("./ops/shares_memory.json"),
  "sign": () => import("./ops/sign.json"),
  "signbit": () => import("./ops/signbit.json"),
  "sin": () => import("./ops/sin.json"),
  "sinc": () => import("./ops/sinc.json"),
  "sinh": () => import("./ops/sinh.json"),
  "size": () => import("./ops/size.json"),
  "sort": () => import("./ops/sort.json"),
  "sort_complex": () => import("./ops/sort_complex.json"),
  "spacing": () => import("./ops/spacing.json"),
  "split": () => import("./ops/split.json"),
  "sqrt": () => import("./ops/sqrt.json"),
  "square": () => import("./ops/square.json"),
  "squeeze": () => import("./ops/squeeze.json"),
  "stack": () => import("./ops/stack.json"),
  "stats-cauchy-cdf": () => import("./ops/stats-cauchy-cdf.json"),
  "stats-cauchy-pdf": () => import("./ops/stats-cauchy-pdf.json"),
  "stats-cauchy-ppf": () => import("./ops/stats-cauchy-ppf.json"),
  "stats-expon-cdf": () => import("./ops/stats-expon-cdf.json"),
  "stats-expon-pdf": () => import("./ops/stats-expon-pdf.json"),
  "stats-expon-ppf": () => import("./ops/stats-expon-ppf.json"),
  "stats-laplace-cdf": () => import("./ops/stats-laplace-cdf.json"),
  "stats-laplace-pdf": () => import("./ops/stats-laplace-pdf.json"),
  "stats-laplace-ppf": () => import("./ops/stats-laplace-ppf.json"),
  "stats-logistic-cdf": () => import("./ops/stats-logistic-cdf.json"),
  "stats-logistic-pdf": () => import("./ops/stats-logistic-pdf.json"),
  "stats-logistic-ppf": () => import("./ops/stats-logistic-ppf.json"),
  "stats-lognorm-cdf": () => import("./ops/stats-lognorm-cdf.json"),
  "stats-lognorm-pdf": () => import("./ops/stats-lognorm-pdf.json"),
  "stats-lognorm-ppf": () => import("./ops/stats-lognorm-ppf.json"),
  "stats-norm-cdf": () => import("./ops/stats-norm-cdf.json"),
  "stats-norm-pdf": () => import("./ops/stats-norm-pdf.json"),
  "stats-norm-ppf": () => import("./ops/stats-norm-ppf.json"),
  "stats-truncnorm-cdf": () => import("./ops/stats-truncnorm-cdf.json"),
  "stats-truncnorm-pdf": () => import("./ops/stats-truncnorm-pdf.json"),
  "stats-truncnorm-ppf": () => import("./ops/stats-truncnorm-ppf.json"),
  "stats-uniform-cdf": () => import("./ops/stats-uniform-cdf.json"),
  "stats-uniform-pdf": () => import("./ops/stats-uniform-pdf.json"),
  "stats-uniform-ppf": () => import("./ops/stats-uniform-ppf.json"),
  "std": () => import("./ops/std.json"),
  "subtract": () => import("./ops/subtract.json"),
  "sum": () => import("./ops/sum.json"),
  "swapaxes": () => import("./ops/swapaxes.json"),
  "take": () => import("./ops/take.json"),
  "take_along_axis": () => import("./ops/take_along_axis.json"),
  "tan": () => import("./ops/tan.json"),
  "tanh": () => import("./ops/tanh.json"),
  "tensordot": () => import("./ops/tensordot.json"),
  "tile": () => import("./ops/tile.json"),
  "trace": () => import("./ops/trace.json"),
  "transpose": () => import("./ops/transpose.json"),
  "trapezoid": () => import("./ops/trapezoid.json"),
  "tri": () => import("./ops/tri.json"),
  "tril": () => import("./ops/tril.json"),
  "tril_indices": () => import("./ops/tril_indices.json"),
  "tril_indices_from": () => import("./ops/tril_indices_from.json"),
  "trim_zeros": () => import("./ops/trim_zeros.json"),
  "triu": () => import("./ops/triu.json"),
  "triu_indices": () => import("./ops/triu_indices.json"),
  "triu_indices_from": () => import("./ops/triu_indices_from.json"),
  "true_divide": () => import("./ops/true_divide.json"),
  "trunc": () => import("./ops/trunc.json"),
  "typename": () => import("./ops/typename.json"),
  "union1d": () => import("./ops/union1d.json"),
  "unique": () => import("./ops/unique.json"),
  "unique_all": () => import("./ops/unique_all.json"),
  "unique_counts": () => import("./ops/unique_counts.json"),
  "unique_inverse": () => import("./ops/unique_inverse.json"),
  "unique_values": () => import("./ops/unique_values.json"),
  "unpackbits": () => import("./ops/unpackbits.json"),
  "unravel_index": () => import("./ops/unravel_index.json"),
  "unstack": () => import("./ops/unstack.json"),
  "unwrap": () => import("./ops/unwrap.json"),
  "vander": () => import("./ops/vander.json"),
  "var": () => import("./ops/var.json"),
  "vdot": () => import("./ops/vdot.json"),
  "vecdot": () => import("./ops/vecdot.json"),
  "vecmat": () => import("./ops/vecmat.json"),
  "vsplit": () => import("./ops/vsplit.json"),
  "vstack": () => import("./ops/vstack.json"),
  "where": () => import("./ops/where.json"),
  "zeros": () => import("./ops/zeros.json"),
  "zeros_like": () => import("./ops/zeros_like.json"),
};

export const opDocSlugs = [
  "absolute",
  "add",
  "all",
  "allclose",
  "angle",
  "any",
  "append",
  "apply_along_axis",
  "apply_over_axes",
  "arange",
  "arccos",
  "arccosh",
  "arcsin",
  "arcsinh",
  "arctan",
  "arctan2",
  "arctanh",
  "argmax",
  "argmin",
  "argpartition",
  "argsort",
  "argwhere",
  "array",
  "array_equal",
  "array_equiv",
  "array_split",
  "asarray",
  "asarray_chkfinite",
  "astype",
  "atleast_1d",
  "atleast_2d",
  "atleast_3d",
  "average",
  "bartlett",
  "bincount",
  "bitwise_and",
  "bitwise_count",
  "bitwise_left_shift",
  "bitwise_not",
  "bitwise_or",
  "bitwise_right_shift",
  "bitwise_xor",
  "blackman",
  "block",
  "bmat",
  "broadcast_arrays",
  "broadcast_shapes",
  "broadcast_to",
  "can_cast",
  "cbrt",
  "ceil",
  "choose",
  "clip",
  "column_stack",
  "common_type",
  "compress",
  "concatenate",
  "conj",
  "conjugate",
  "convolve",
  "copy",
  "copysign",
  "copyto",
  "corrcoef",
  "correlate",
  "cos",
  "cosh",
  "count_nonzero",
  "cov",
  "cross",
  "cumprod",
  "cumsum",
  "cumulative_prod",
  "cumulative_sum",
  "degrees",
  "delete",
  "diag",
  "diag_indices",
  "diag_indices_from",
  "diagflat",
  "diagonal",
  "diff",
  "digitize",
  "divide",
  "dot",
  "dsplit",
  "dstack",
  "ediff1d",
  "einsum",
  "einsum_path",
  "empty",
  "empty_like",
  "equal",
  "exp",
  "exp2",
  "expand_dims",
  "expm1",
  "extract",
  "eye",
  "fabs",
  "fft-fft",
  "fft-fft2",
  "fft-fftfreq",
  "fft-fftn",
  "fft-fftshift",
  "fft-hfft",
  "fft-ifft",
  "fft-ifft2",
  "fft-ifftn",
  "fft-ifftshift",
  "fft-ihfft",
  "fft-irfft",
  "fft-irfft2",
  "fft-irfftn",
  "fft-rfft",
  "fft-rfft2",
  "fft-rfftfreq",
  "fft-rfftn",
  "fill_diagonal",
  "flatnonzero",
  "flip",
  "fliplr",
  "flipud",
  "float_power",
  "floor",
  "floor_divide",
  "fmax",
  "fmin",
  "fmod",
  "frexp",
  "from_dlpack",
  "frombuffer",
  "fromfunction",
  "fromiter",
  "full",
  "full_like",
  "gcd",
  "geomspace",
  "gradient",
  "greater",
  "greater_equal",
  "hamming",
  "hanning",
  "heaviside",
  "histogram",
  "histogram2d",
  "histogram_bin_edges",
  "histogramdd",
  "hsplit",
  "hstack",
  "hypot",
  "i0",
  "identity",
  "imag",
  "in1d",
  "indices",
  "inner",
  "insert",
  "interp",
  "intersect1d",
  "invert",
  "isclose",
  "iscomplex",
  "iscomplexobj",
  "isdtype",
  "isfinite",
  "isfortran",
  "isin",
  "isinf",
  "isnan",
  "isneginf",
  "isposinf",
  "isreal",
  "isrealobj",
  "isscalar",
  "issubdtype",
  "iterable",
  "ix_",
  "kaiser",
  "kron",
  "lcm",
  "ldexp",
  "left_shift",
  "less",
  "less_equal",
  "lexsort",
  "linalg-cholesky",
  "linalg-cond",
  "linalg-cross",
  "linalg-det",
  "linalg-diagonal",
  "linalg-eig",
  "linalg-eigh",
  "linalg-eigvals",
  "linalg-eigvalsh",
  "linalg-inv",
  "linalg-lstsq",
  "linalg-matmul",
  "linalg-matrix_norm",
  "linalg-matrix_power",
  "linalg-matrix_rank",
  "linalg-matrix_transpose",
  "linalg-multi_dot",
  "linalg-norm",
  "linalg-outer",
  "linalg-pinv",
  "linalg-qr",
  "linalg-slogdet",
  "linalg-solve",
  "linalg-svd",
  "linalg-svdvals",
  "linalg-tensordot",
  "linalg-tensorinv",
  "linalg-tensorsolve",
  "linalg-trace",
  "linalg-vecdot",
  "linalg-vector_norm",
  "linspace",
  "log",
  "log10",
  "log1p",
  "log2",
  "logaddexp",
  "logaddexp2",
  "logical_and",
  "logical_not",
  "logical_or",
  "logical_xor",
  "logspace",
  "mask_indices",
  "matmul",
  "matrix_transpose",
  "matvec",
  "max",
  "maximum",
  "may_share_memory",
  "mean",
  "median",
  "meshgrid",
  "min",
  "min_scalar_type",
  "minimum",
  "mintypecode",
  "mod",
  "modf",
  "moveaxis",
  "multiply",
  "nan_to_num",
  "nanargmax",
  "nanargmin",
  "nancumprod",
  "nancumsum",
  "nanmax",
  "nanmean",
  "nanmedian",
  "nanmin",
  "nanpercentile",
  "nanprod",
  "nanquantile",
  "nanstd",
  "nansum",
  "nanvar",
  "ndim",
  "negative",
  "nextafter",
  "nonzero",
  "not_equal",
  "ones",
  "ones_like",
  "outer",
  "packbits",
  "pad",
  "partition",
  "percentile",
  "permute_dims",
  "piecewise",
  "place",
  "poly",
  "polyadd",
  "polyder",
  "polydiv",
  "polyfit",
  "polyint",
  "polymul",
  "polysub",
  "polyval",
  "positive",
  "power",
  "prod",
  "promote_types",
  "ptp",
  "put",
  "put_along_axis",
  "putmask",
  "quantile",
  "radians",
  "random-beta",
  "random-binomial",
  "random-bytes",
  "random-chisquare",
  "random-choice",
  "random-default_rng",
  "random-dirichlet",
  "random-exponential",
  "random-f",
  "random-gamma",
  "random-geometric",
  "random-get_state",
  "random-gumbel",
  "random-hypergeometric",
  "random-laplace",
  "random-logistic",
  "random-lognormal",
  "random-logseries",
  "random-multinomial",
  "random-multivariate_normal",
  "random-negative_binomial",
  "random-noncentral_chisquare",
  "random-noncentral_f",
  "random-normal",
  "random-pareto",
  "random-permutation",
  "random-poisson",
  "random-power",
  "random-rand",
  "random-randint",
  "random-randn",
  "random-random",
  "random-random_integers",
  "random-random_sample",
  "random-rayleigh",
  "random-seed",
  "random-set_state",
  "random-shuffle",
  "random-standard_cauchy",
  "random-standard_exponential",
  "random-standard_gamma",
  "random-standard_normal",
  "random-standard_t",
  "random-triangular",
  "random-uniform",
  "random-vonmises",
  "random-wald",
  "random-weibull",
  "random-zipf",
  "ravel",
  "ravel_multi_index",
  "real",
  "real_if_close",
  "reciprocal",
  "remainder",
  "repeat",
  "require",
  "reshape",
  "resize",
  "result_type",
  "right_shift",
  "rint",
  "roll",
  "rollaxis",
  "roots",
  "rot90",
  "row_stack",
  "searchsorted",
  "select",
  "setdiff1d",
  "setxor1d",
  "shape",
  "shares_memory",
  "sign",
  "signbit",
  "sin",
  "sinc",
  "sinh",
  "size",
  "sort",
  "sort_complex",
  "spacing",
  "split",
  "sqrt",
  "square",
  "squeeze",
  "stack",
  "stats-cauchy-cdf",
  "stats-cauchy-pdf",
  "stats-cauchy-ppf",
  "stats-expon-cdf",
  "stats-expon-pdf",
  "stats-expon-ppf",
  "stats-laplace-cdf",
  "stats-laplace-pdf",
  "stats-laplace-ppf",
  "stats-logistic-cdf",
  "stats-logistic-pdf",
  "stats-logistic-ppf",
  "stats-lognorm-cdf",
  "stats-lognorm-pdf",
  "stats-lognorm-ppf",
  "stats-norm-cdf",
  "stats-norm-pdf",
  "stats-norm-ppf",
  "stats-truncnorm-cdf",
  "stats-truncnorm-pdf",
  "stats-truncnorm-ppf",
  "stats-uniform-cdf",
  "stats-uniform-pdf",
  "stats-uniform-ppf",
  "std",
  "subtract",
  "sum",
  "swapaxes",
  "take",
  "take_along_axis",
  "tan",
  "tanh",
  "tensordot",
  "tile",
  "trace",
  "transpose",
  "trapezoid",
  "tri",
  "tril",
  "tril_indices",
  "tril_indices_from",
  "trim_zeros",
  "triu",
  "triu_indices",
  "triu_indices_from",
  "true_divide",
  "trunc",
  "typename",
  "union1d",
  "unique",
  "unique_all",
  "unique_counts",
  "unique_inverse",
  "unique_values",
  "unpackbits",
  "unravel_index",
  "unstack",
  "unwrap",
  "vander",
  "var",
  "vdot",
  "vecdot",
  "vecmat",
  "vsplit",
  "vstack",
  "where",
  "zeros",
  "zeros_like",
] as const;
