import type { OpDocPayload } from '@/components/api-reference/op-doc-types';

export const opDocImports: Record<string, () => Promise<{ default: OpDocPayload }>> = {
  "abs": () => import("../public/api-data/ops/abs.json"),
  "absolute": () => import("../public/api-data/ops/absolute.json"),
  "acos": () => import("../public/api-data/ops/acos.json"),
  "acosh": () => import("../public/api-data/ops/acosh.json"),
  "add": () => import("../public/api-data/ops/add.json"),
  "all": () => import("../public/api-data/ops/all.json"),
  "allclose": () => import("../public/api-data/ops/allclose.json"),
  "amax": () => import("../public/api-data/ops/amax.json"),
  "amin": () => import("../public/api-data/ops/amin.json"),
  "angle": () => import("../public/api-data/ops/angle.json"),
  "any": () => import("../public/api-data/ops/any.json"),
  "append": () => import("../public/api-data/ops/append.json"),
  "apply_along_axis": () => import("../public/api-data/ops/apply_along_axis.json"),
  "apply_over_axes": () => import("../public/api-data/ops/apply_over_axes.json"),
  "arange": () => import("../public/api-data/ops/arange.json"),
  "arccos": () => import("../public/api-data/ops/arccos.json"),
  "arccosh": () => import("../public/api-data/ops/arccosh.json"),
  "arcsin": () => import("../public/api-data/ops/arcsin.json"),
  "arcsinh": () => import("../public/api-data/ops/arcsinh.json"),
  "arctan": () => import("../public/api-data/ops/arctan.json"),
  "arctan2": () => import("../public/api-data/ops/arctan2.json"),
  "arctanh": () => import("../public/api-data/ops/arctanh.json"),
  "argmax": () => import("../public/api-data/ops/argmax.json"),
  "argmin": () => import("../public/api-data/ops/argmin.json"),
  "argpartition": () => import("../public/api-data/ops/argpartition.json"),
  "argsort": () => import("../public/api-data/ops/argsort.json"),
  "argwhere": () => import("../public/api-data/ops/argwhere.json"),
  "around": () => import("../public/api-data/ops/around.json"),
  "array": () => import("../public/api-data/ops/array.json"),
  "array2string": () => import("../public/api-data/ops/array2string.json"),
  "array_equal": () => import("../public/api-data/ops/array_equal.json"),
  "array_equiv": () => import("../public/api-data/ops/array_equiv.json"),
  "array_repr": () => import("../public/api-data/ops/array_repr.json"),
  "array_split": () => import("../public/api-data/ops/array_split.json"),
  "array_str": () => import("../public/api-data/ops/array_str.json"),
  "asarray": () => import("../public/api-data/ops/asarray.json"),
  "asarray_chkfinite": () => import("../public/api-data/ops/asarray_chkfinite.json"),
  "asin": () => import("../public/api-data/ops/asin.json"),
  "asinh": () => import("../public/api-data/ops/asinh.json"),
  "asmatrix": () => import("../public/api-data/ops/asmatrix.json"),
  "astype": () => import("../public/api-data/ops/astype.json"),
  "atan": () => import("../public/api-data/ops/atan.json"),
  "atan2": () => import("../public/api-data/ops/atan2.json"),
  "atanh": () => import("../public/api-data/ops/atanh.json"),
  "atleast_1d": () => import("../public/api-data/ops/atleast_1d.json"),
  "atleast_2d": () => import("../public/api-data/ops/atleast_2d.json"),
  "atleast_3d": () => import("../public/api-data/ops/atleast_3d.json"),
  "average": () => import("../public/api-data/ops/average.json"),
  "bartlett": () => import("../public/api-data/ops/bartlett.json"),
  "base_repr": () => import("../public/api-data/ops/base_repr.json"),
  "binary_repr": () => import("../public/api-data/ops/binary_repr.json"),
  "bincount": () => import("../public/api-data/ops/bincount.json"),
  "bitwise_and": () => import("../public/api-data/ops/bitwise_and.json"),
  "bitwise_count": () => import("../public/api-data/ops/bitwise_count.json"),
  "bitwise_invert": () => import("../public/api-data/ops/bitwise_invert.json"),
  "bitwise_left_shift": () => import("../public/api-data/ops/bitwise_left_shift.json"),
  "bitwise_not": () => import("../public/api-data/ops/bitwise_not.json"),
  "bitwise_or": () => import("../public/api-data/ops/bitwise_or.json"),
  "bitwise_right_shift": () => import("../public/api-data/ops/bitwise_right_shift.json"),
  "bitwise_xor": () => import("../public/api-data/ops/bitwise_xor.json"),
  "blackman": () => import("../public/api-data/ops/blackman.json"),
  "block": () => import("../public/api-data/ops/block.json"),
  "bmat": () => import("../public/api-data/ops/bmat.json"),
  "broadcast_arrays": () => import("../public/api-data/ops/broadcast_arrays.json"),
  "broadcast_shapes": () => import("../public/api-data/ops/broadcast_shapes.json"),
  "broadcast_to": () => import("../public/api-data/ops/broadcast_to.json"),
  "busday_count": () => import("../public/api-data/ops/busday_count.json"),
  "busday_offset": () => import("../public/api-data/ops/busday_offset.json"),
  "can_cast": () => import("../public/api-data/ops/can_cast.json"),
  "cbrt": () => import("../public/api-data/ops/cbrt.json"),
  "ceil": () => import("../public/api-data/ops/ceil.json"),
  "choose": () => import("../public/api-data/ops/choose.json"),
  "clip": () => import("../public/api-data/ops/clip.json"),
  "column_stack": () => import("../public/api-data/ops/column_stack.json"),
  "common_type": () => import("../public/api-data/ops/common_type.json"),
  "compress": () => import("../public/api-data/ops/compress.json"),
  "concat": () => import("../public/api-data/ops/concat.json"),
  "concatenate": () => import("../public/api-data/ops/concatenate.json"),
  "conj": () => import("../public/api-data/ops/conj.json"),
  "conjugate": () => import("../public/api-data/ops/conjugate.json"),
  "convolve": () => import("../public/api-data/ops/convolve.json"),
  "copy": () => import("../public/api-data/ops/copy.json"),
  "copysign": () => import("../public/api-data/ops/copysign.json"),
  "copyto": () => import("../public/api-data/ops/copyto.json"),
  "corrcoef": () => import("../public/api-data/ops/corrcoef.json"),
  "correlate": () => import("../public/api-data/ops/correlate.json"),
  "cos": () => import("../public/api-data/ops/cos.json"),
  "cosh": () => import("../public/api-data/ops/cosh.json"),
  "count_nonzero": () => import("../public/api-data/ops/count_nonzero.json"),
  "cov": () => import("../public/api-data/ops/cov.json"),
  "cross": () => import("../public/api-data/ops/cross.json"),
  "cumprod": () => import("../public/api-data/ops/cumprod.json"),
  "cumsum": () => import("../public/api-data/ops/cumsum.json"),
  "cumulative_prod": () => import("../public/api-data/ops/cumulative_prod.json"),
  "cumulative_sum": () => import("../public/api-data/ops/cumulative_sum.json"),
  "datetime_as_string": () => import("../public/api-data/ops/datetime_as_string.json"),
  "datetime_data": () => import("../public/api-data/ops/datetime_data.json"),
  "deg2rad": () => import("../public/api-data/ops/deg2rad.json"),
  "degrees": () => import("../public/api-data/ops/degrees.json"),
  "delete": () => import("../public/api-data/ops/delete.json"),
  "diag": () => import("../public/api-data/ops/diag.json"),
  "diag_indices": () => import("../public/api-data/ops/diag_indices.json"),
  "diag_indices_from": () => import("../public/api-data/ops/diag_indices_from.json"),
  "diagflat": () => import("../public/api-data/ops/diagflat.json"),
  "diagonal": () => import("../public/api-data/ops/diagonal.json"),
  "diff": () => import("../public/api-data/ops/diff.json"),
  "digitize": () => import("../public/api-data/ops/digitize.json"),
  "divide": () => import("../public/api-data/ops/divide.json"),
  "divmod": () => import("../public/api-data/ops/divmod.json"),
  "dot": () => import("../public/api-data/ops/dot.json"),
  "dsplit": () => import("../public/api-data/ops/dsplit.json"),
  "dstack": () => import("../public/api-data/ops/dstack.json"),
  "ediff1d": () => import("../public/api-data/ops/ediff1d.json"),
  "einsum": () => import("../public/api-data/ops/einsum.json"),
  "einsum_path": () => import("../public/api-data/ops/einsum_path.json"),
  "empty": () => import("../public/api-data/ops/empty.json"),
  "empty_like": () => import("../public/api-data/ops/empty_like.json"),
  "equal": () => import("../public/api-data/ops/equal.json"),
  "exp": () => import("../public/api-data/ops/exp.json"),
  "exp2": () => import("../public/api-data/ops/exp2.json"),
  "expand_dims": () => import("../public/api-data/ops/expand_dims.json"),
  "expm1": () => import("../public/api-data/ops/expm1.json"),
  "extract": () => import("../public/api-data/ops/extract.json"),
  "eye": () => import("../public/api-data/ops/eye.json"),
  "fabs": () => import("../public/api-data/ops/fabs.json"),
  "fft.fft": () => import("../public/api-data/ops/fft.fft.json"),
  "fft.fft2": () => import("../public/api-data/ops/fft.fft2.json"),
  "fft.fftfreq": () => import("../public/api-data/ops/fft.fftfreq.json"),
  "fft.fftn": () => import("../public/api-data/ops/fft.fftn.json"),
  "fft.fftshift": () => import("../public/api-data/ops/fft.fftshift.json"),
  "fft.hfft": () => import("../public/api-data/ops/fft.hfft.json"),
  "fft.ifft": () => import("../public/api-data/ops/fft.ifft.json"),
  "fft.ifft2": () => import("../public/api-data/ops/fft.ifft2.json"),
  "fft.ifftn": () => import("../public/api-data/ops/fft.ifftn.json"),
  "fft.ifftshift": () => import("../public/api-data/ops/fft.ifftshift.json"),
  "fft.ihfft": () => import("../public/api-data/ops/fft.ihfft.json"),
  "fft.irfft": () => import("../public/api-data/ops/fft.irfft.json"),
  "fft.irfft2": () => import("../public/api-data/ops/fft.irfft2.json"),
  "fft.irfftn": () => import("../public/api-data/ops/fft.irfftn.json"),
  "fft.rfft": () => import("../public/api-data/ops/fft.rfft.json"),
  "fft.rfft2": () => import("../public/api-data/ops/fft.rfft2.json"),
  "fft.rfftfreq": () => import("../public/api-data/ops/fft.rfftfreq.json"),
  "fft.rfftn": () => import("../public/api-data/ops/fft.rfftn.json"),
  "fill_diagonal": () => import("../public/api-data/ops/fill_diagonal.json"),
  "fix": () => import("../public/api-data/ops/fix.json"),
  "flatnonzero": () => import("../public/api-data/ops/flatnonzero.json"),
  "flip": () => import("../public/api-data/ops/flip.json"),
  "fliplr": () => import("../public/api-data/ops/fliplr.json"),
  "flipud": () => import("../public/api-data/ops/flipud.json"),
  "float_power": () => import("../public/api-data/ops/float_power.json"),
  "floor": () => import("../public/api-data/ops/floor.json"),
  "floor_divide": () => import("../public/api-data/ops/floor_divide.json"),
  "fmax": () => import("../public/api-data/ops/fmax.json"),
  "fmin": () => import("../public/api-data/ops/fmin.json"),
  "fmod": () => import("../public/api-data/ops/fmod.json"),
  "format_float_positional": () => import("../public/api-data/ops/format_float_positional.json"),
  "format_float_scientific": () => import("../public/api-data/ops/format_float_scientific.json"),
  "frexp": () => import("../public/api-data/ops/frexp.json"),
  "from_dlpack": () => import("../public/api-data/ops/from_dlpack.json"),
  "frombuffer": () => import("../public/api-data/ops/frombuffer.json"),
  "fromfile": () => import("../public/api-data/ops/fromfile.json"),
  "fromfunction": () => import("../public/api-data/ops/fromfunction.json"),
  "fromiter": () => import("../public/api-data/ops/fromiter.json"),
  "frompyfunc": () => import("../public/api-data/ops/frompyfunc.json"),
  "fromregex": () => import("../public/api-data/ops/fromregex.json"),
  "fromstring": () => import("../public/api-data/ops/fromstring.json"),
  "full": () => import("../public/api-data/ops/full.json"),
  "full_like": () => import("../public/api-data/ops/full_like.json"),
  "gcd": () => import("../public/api-data/ops/gcd.json"),
  "genfromtxt": () => import("../public/api-data/ops/genfromtxt.json"),
  "geomspace": () => import("../public/api-data/ops/geomspace.json"),
  "get_include": () => import("../public/api-data/ops/get_include.json"),
  "getbufsize": () => import("../public/api-data/ops/getbufsize.json"),
  "geterr": () => import("../public/api-data/ops/geterr.json"),
  "geterrcall": () => import("../public/api-data/ops/geterrcall.json"),
  "gradient": () => import("../public/api-data/ops/gradient.json"),
  "greater": () => import("../public/api-data/ops/greater.json"),
  "greater_equal": () => import("../public/api-data/ops/greater_equal.json"),
  "hamming": () => import("../public/api-data/ops/hamming.json"),
  "hanning": () => import("../public/api-data/ops/hanning.json"),
  "heaviside": () => import("../public/api-data/ops/heaviside.json"),
  "histogram": () => import("../public/api-data/ops/histogram.json"),
  "histogram2d": () => import("../public/api-data/ops/histogram2d.json"),
  "histogram_bin_edges": () => import("../public/api-data/ops/histogram_bin_edges.json"),
  "histogramdd": () => import("../public/api-data/ops/histogramdd.json"),
  "hsplit": () => import("../public/api-data/ops/hsplit.json"),
  "hstack": () => import("../public/api-data/ops/hstack.json"),
  "hypot": () => import("../public/api-data/ops/hypot.json"),
  "i0": () => import("../public/api-data/ops/i0.json"),
  "identity": () => import("../public/api-data/ops/identity.json"),
  "imag": () => import("../public/api-data/ops/imag.json"),
  "in1d": () => import("../public/api-data/ops/in1d.json"),
  "indices": () => import("../public/api-data/ops/indices.json"),
  "inner": () => import("../public/api-data/ops/inner.json"),
  "insert": () => import("../public/api-data/ops/insert.json"),
  "interp": () => import("../public/api-data/ops/interp.json"),
  "intersect1d": () => import("../public/api-data/ops/intersect1d.json"),
  "invert": () => import("../public/api-data/ops/invert.json"),
  "is_busday": () => import("../public/api-data/ops/is_busday.json"),
  "isclose": () => import("../public/api-data/ops/isclose.json"),
  "iscomplex": () => import("../public/api-data/ops/iscomplex.json"),
  "iscomplexobj": () => import("../public/api-data/ops/iscomplexobj.json"),
  "isdtype": () => import("../public/api-data/ops/isdtype.json"),
  "isfinite": () => import("../public/api-data/ops/isfinite.json"),
  "isfortran": () => import("../public/api-data/ops/isfortran.json"),
  "isin": () => import("../public/api-data/ops/isin.json"),
  "isinf": () => import("../public/api-data/ops/isinf.json"),
  "isnan": () => import("../public/api-data/ops/isnan.json"),
  "isnat": () => import("../public/api-data/ops/isnat.json"),
  "isneginf": () => import("../public/api-data/ops/isneginf.json"),
  "isposinf": () => import("../public/api-data/ops/isposinf.json"),
  "isreal": () => import("../public/api-data/ops/isreal.json"),
  "isrealobj": () => import("../public/api-data/ops/isrealobj.json"),
  "isscalar": () => import("../public/api-data/ops/isscalar.json"),
  "issubdtype": () => import("../public/api-data/ops/issubdtype.json"),
  "iterable": () => import("../public/api-data/ops/iterable.json"),
  "ix_": () => import("../public/api-data/ops/ix_.json"),
  "kaiser": () => import("../public/api-data/ops/kaiser.json"),
  "kron": () => import("../public/api-data/ops/kron.json"),
  "lcm": () => import("../public/api-data/ops/lcm.json"),
  "ldexp": () => import("../public/api-data/ops/ldexp.json"),
  "left_shift": () => import("../public/api-data/ops/left_shift.json"),
  "less": () => import("../public/api-data/ops/less.json"),
  "less_equal": () => import("../public/api-data/ops/less_equal.json"),
  "lexsort": () => import("../public/api-data/ops/lexsort.json"),
  "linalg.cholesky": () => import("../public/api-data/ops/linalg.cholesky.json"),
  "linalg.cond": () => import("../public/api-data/ops/linalg.cond.json"),
  "linalg.cross": () => import("../public/api-data/ops/linalg.cross.json"),
  "linalg.det": () => import("../public/api-data/ops/linalg.det.json"),
  "linalg.diagonal": () => import("../public/api-data/ops/linalg.diagonal.json"),
  "linalg.eig": () => import("../public/api-data/ops/linalg.eig.json"),
  "linalg.eigh": () => import("../public/api-data/ops/linalg.eigh.json"),
  "linalg.eigvals": () => import("../public/api-data/ops/linalg.eigvals.json"),
  "linalg.eigvalsh": () => import("../public/api-data/ops/linalg.eigvalsh.json"),
  "linalg.inv": () => import("../public/api-data/ops/linalg.inv.json"),
  "linalg.lstsq": () => import("../public/api-data/ops/linalg.lstsq.json"),
  "linalg.matmul": () => import("../public/api-data/ops/linalg.matmul.json"),
  "linalg.matrix_norm": () => import("../public/api-data/ops/linalg.matrix_norm.json"),
  "linalg.matrix_power": () => import("../public/api-data/ops/linalg.matrix_power.json"),
  "linalg.matrix_rank": () => import("../public/api-data/ops/linalg.matrix_rank.json"),
  "linalg.matrix_transpose": () => import("../public/api-data/ops/linalg.matrix_transpose.json"),
  "linalg.multi_dot": () => import("../public/api-data/ops/linalg.multi_dot.json"),
  "linalg.norm": () => import("../public/api-data/ops/linalg.norm.json"),
  "linalg.outer": () => import("../public/api-data/ops/linalg.outer.json"),
  "linalg.pinv": () => import("../public/api-data/ops/linalg.pinv.json"),
  "linalg.qr": () => import("../public/api-data/ops/linalg.qr.json"),
  "linalg.slogdet": () => import("../public/api-data/ops/linalg.slogdet.json"),
  "linalg.solve": () => import("../public/api-data/ops/linalg.solve.json"),
  "linalg.svd": () => import("../public/api-data/ops/linalg.svd.json"),
  "linalg.svdvals": () => import("../public/api-data/ops/linalg.svdvals.json"),
  "linalg.tensordot": () => import("../public/api-data/ops/linalg.tensordot.json"),
  "linalg.tensorinv": () => import("../public/api-data/ops/linalg.tensorinv.json"),
  "linalg.tensorsolve": () => import("../public/api-data/ops/linalg.tensorsolve.json"),
  "linalg.trace": () => import("../public/api-data/ops/linalg.trace.json"),
  "linalg.vecdot": () => import("../public/api-data/ops/linalg.vecdot.json"),
  "linalg.vector_norm": () => import("../public/api-data/ops/linalg.vector_norm.json"),
  "linspace": () => import("../public/api-data/ops/linspace.json"),
  "load": () => import("../public/api-data/ops/load.json"),
  "loadtxt": () => import("../public/api-data/ops/loadtxt.json"),
  "log": () => import("../public/api-data/ops/log.json"),
  "log10": () => import("../public/api-data/ops/log10.json"),
  "log1p": () => import("../public/api-data/ops/log1p.json"),
  "log2": () => import("../public/api-data/ops/log2.json"),
  "logaddexp": () => import("../public/api-data/ops/logaddexp.json"),
  "logaddexp2": () => import("../public/api-data/ops/logaddexp2.json"),
  "logical_and": () => import("../public/api-data/ops/logical_and.json"),
  "logical_not": () => import("../public/api-data/ops/logical_not.json"),
  "logical_or": () => import("../public/api-data/ops/logical_or.json"),
  "logical_xor": () => import("../public/api-data/ops/logical_xor.json"),
  "logspace": () => import("../public/api-data/ops/logspace.json"),
  "mask_indices": () => import("../public/api-data/ops/mask_indices.json"),
  "matmul": () => import("../public/api-data/ops/matmul.json"),
  "matrix_transpose": () => import("../public/api-data/ops/matrix_transpose.json"),
  "matvec": () => import("../public/api-data/ops/matvec.json"),
  "max": () => import("../public/api-data/ops/max.json"),
  "maximum": () => import("../public/api-data/ops/maximum.json"),
  "may_share_memory": () => import("../public/api-data/ops/may_share_memory.json"),
  "mean": () => import("../public/api-data/ops/mean.json"),
  "median": () => import("../public/api-data/ops/median.json"),
  "meshgrid": () => import("../public/api-data/ops/meshgrid.json"),
  "min": () => import("../public/api-data/ops/min.json"),
  "min_scalar_type": () => import("../public/api-data/ops/min_scalar_type.json"),
  "minimum": () => import("../public/api-data/ops/minimum.json"),
  "mintypecode": () => import("../public/api-data/ops/mintypecode.json"),
  "mod": () => import("../public/api-data/ops/mod.json"),
  "modf": () => import("../public/api-data/ops/modf.json"),
  "moveaxis": () => import("../public/api-data/ops/moveaxis.json"),
  "multiply": () => import("../public/api-data/ops/multiply.json"),
  "nan_to_num": () => import("../public/api-data/ops/nan_to_num.json"),
  "nanargmax": () => import("../public/api-data/ops/nanargmax.json"),
  "nanargmin": () => import("../public/api-data/ops/nanargmin.json"),
  "nancumprod": () => import("../public/api-data/ops/nancumprod.json"),
  "nancumsum": () => import("../public/api-data/ops/nancumsum.json"),
  "nanmax": () => import("../public/api-data/ops/nanmax.json"),
  "nanmean": () => import("../public/api-data/ops/nanmean.json"),
  "nanmedian": () => import("../public/api-data/ops/nanmedian.json"),
  "nanmin": () => import("../public/api-data/ops/nanmin.json"),
  "nanpercentile": () => import("../public/api-data/ops/nanpercentile.json"),
  "nanprod": () => import("../public/api-data/ops/nanprod.json"),
  "nanquantile": () => import("../public/api-data/ops/nanquantile.json"),
  "nanstd": () => import("../public/api-data/ops/nanstd.json"),
  "nansum": () => import("../public/api-data/ops/nansum.json"),
  "nanvar": () => import("../public/api-data/ops/nanvar.json"),
  "ndim": () => import("../public/api-data/ops/ndim.json"),
  "negative": () => import("../public/api-data/ops/negative.json"),
  "nested_iters": () => import("../public/api-data/ops/nested_iters.json"),
  "nextafter": () => import("../public/api-data/ops/nextafter.json"),
  "nonzero": () => import("../public/api-data/ops/nonzero.json"),
  "not_equal": () => import("../public/api-data/ops/not_equal.json"),
  "ones": () => import("../public/api-data/ops/ones.json"),
  "ones_like": () => import("../public/api-data/ops/ones_like.json"),
  "outer": () => import("../public/api-data/ops/outer.json"),
  "packbits": () => import("../public/api-data/ops/packbits.json"),
  "pad": () => import("../public/api-data/ops/pad.json"),
  "partition": () => import("../public/api-data/ops/partition.json"),
  "percentile": () => import("../public/api-data/ops/percentile.json"),
  "permute_dims": () => import("../public/api-data/ops/permute_dims.json"),
  "piecewise": () => import("../public/api-data/ops/piecewise.json"),
  "place": () => import("../public/api-data/ops/place.json"),
  "poly": () => import("../public/api-data/ops/poly.json"),
  "polyadd": () => import("../public/api-data/ops/polyadd.json"),
  "polyder": () => import("../public/api-data/ops/polyder.json"),
  "polydiv": () => import("../public/api-data/ops/polydiv.json"),
  "polyfit": () => import("../public/api-data/ops/polyfit.json"),
  "polyint": () => import("../public/api-data/ops/polyint.json"),
  "polymul": () => import("../public/api-data/ops/polymul.json"),
  "polysub": () => import("../public/api-data/ops/polysub.json"),
  "polyval": () => import("../public/api-data/ops/polyval.json"),
  "positive": () => import("../public/api-data/ops/positive.json"),
  "pow": () => import("../public/api-data/ops/pow.json"),
  "power": () => import("../public/api-data/ops/power.json"),
  "prod": () => import("../public/api-data/ops/prod.json"),
  "promote_types": () => import("../public/api-data/ops/promote_types.json"),
  "ptp": () => import("../public/api-data/ops/ptp.json"),
  "put": () => import("../public/api-data/ops/put.json"),
  "put_along_axis": () => import("../public/api-data/ops/put_along_axis.json"),
  "putmask": () => import("../public/api-data/ops/putmask.json"),
  "quantile": () => import("../public/api-data/ops/quantile.json"),
  "rad2deg": () => import("../public/api-data/ops/rad2deg.json"),
  "radians": () => import("../public/api-data/ops/radians.json"),
  "random.beta": () => import("../public/api-data/ops/random.beta.json"),
  "random.binomial": () => import("../public/api-data/ops/random.binomial.json"),
  "random.bytes": () => import("../public/api-data/ops/random.bytes.json"),
  "random.chisquare": () => import("../public/api-data/ops/random.chisquare.json"),
  "random.choice": () => import("../public/api-data/ops/random.choice.json"),
  "random.default_rng": () => import("../public/api-data/ops/random.default_rng.json"),
  "random.dirichlet": () => import("../public/api-data/ops/random.dirichlet.json"),
  "random.exponential": () => import("../public/api-data/ops/random.exponential.json"),
  "random.f": () => import("../public/api-data/ops/random.f.json"),
  "random.gamma": () => import("../public/api-data/ops/random.gamma.json"),
  "random.geometric": () => import("../public/api-data/ops/random.geometric.json"),
  "random.get_state": () => import("../public/api-data/ops/random.get_state.json"),
  "random.gumbel": () => import("../public/api-data/ops/random.gumbel.json"),
  "random.hypergeometric": () => import("../public/api-data/ops/random.hypergeometric.json"),
  "random.laplace": () => import("../public/api-data/ops/random.laplace.json"),
  "random.logistic": () => import("../public/api-data/ops/random.logistic.json"),
  "random.lognormal": () => import("../public/api-data/ops/random.lognormal.json"),
  "random.logseries": () => import("../public/api-data/ops/random.logseries.json"),
  "random.multinomial": () => import("../public/api-data/ops/random.multinomial.json"),
  "random.multivariate_normal": () => import("../public/api-data/ops/random.multivariate_normal.json"),
  "random.negative_binomial": () => import("../public/api-data/ops/random.negative_binomial.json"),
  "random.noncentral_chisquare": () => import("../public/api-data/ops/random.noncentral_chisquare.json"),
  "random.noncentral_f": () => import("../public/api-data/ops/random.noncentral_f.json"),
  "random.normal": () => import("../public/api-data/ops/random.normal.json"),
  "random.pareto": () => import("../public/api-data/ops/random.pareto.json"),
  "random.permutation": () => import("../public/api-data/ops/random.permutation.json"),
  "random.poisson": () => import("../public/api-data/ops/random.poisson.json"),
  "random.power": () => import("../public/api-data/ops/random.power.json"),
  "random.rand": () => import("../public/api-data/ops/random.rand.json"),
  "random.randint": () => import("../public/api-data/ops/random.randint.json"),
  "random.randn": () => import("../public/api-data/ops/random.randn.json"),
  "random.random": () => import("../public/api-data/ops/random.random.json"),
  "random.random_integers": () => import("../public/api-data/ops/random.random_integers.json"),
  "random.random_sample": () => import("../public/api-data/ops/random.random_sample.json"),
  "random.ranf": () => import("../public/api-data/ops/random.ranf.json"),
  "random.rayleigh": () => import("../public/api-data/ops/random.rayleigh.json"),
  "random.sample": () => import("../public/api-data/ops/random.sample.json"),
  "random.seed": () => import("../public/api-data/ops/random.seed.json"),
  "random.set_state": () => import("../public/api-data/ops/random.set_state.json"),
  "random.shuffle": () => import("../public/api-data/ops/random.shuffle.json"),
  "random.standard_cauchy": () => import("../public/api-data/ops/random.standard_cauchy.json"),
  "random.standard_exponential": () => import("../public/api-data/ops/random.standard_exponential.json"),
  "random.standard_gamma": () => import("../public/api-data/ops/random.standard_gamma.json"),
  "random.standard_normal": () => import("../public/api-data/ops/random.standard_normal.json"),
  "random.standard_t": () => import("../public/api-data/ops/random.standard_t.json"),
  "random.triangular": () => import("../public/api-data/ops/random.triangular.json"),
  "random.uniform": () => import("../public/api-data/ops/random.uniform.json"),
  "random.vonmises": () => import("../public/api-data/ops/random.vonmises.json"),
  "random.wald": () => import("../public/api-data/ops/random.wald.json"),
  "random.weibull": () => import("../public/api-data/ops/random.weibull.json"),
  "random.zipf": () => import("../public/api-data/ops/random.zipf.json"),
  "ravel": () => import("../public/api-data/ops/ravel.json"),
  "ravel_multi_index": () => import("../public/api-data/ops/ravel_multi_index.json"),
  "real": () => import("../public/api-data/ops/real.json"),
  "real_if_close": () => import("../public/api-data/ops/real_if_close.json"),
  "reciprocal": () => import("../public/api-data/ops/reciprocal.json"),
  "remainder": () => import("../public/api-data/ops/remainder.json"),
  "repeat": () => import("../public/api-data/ops/repeat.json"),
  "require": () => import("../public/api-data/ops/require.json"),
  "reshape": () => import("../public/api-data/ops/reshape.json"),
  "resize": () => import("../public/api-data/ops/resize.json"),
  "result_type": () => import("../public/api-data/ops/result_type.json"),
  "right_shift": () => import("../public/api-data/ops/right_shift.json"),
  "rint": () => import("../public/api-data/ops/rint.json"),
  "roll": () => import("../public/api-data/ops/roll.json"),
  "rollaxis": () => import("../public/api-data/ops/rollaxis.json"),
  "roots": () => import("../public/api-data/ops/roots.json"),
  "rot90": () => import("../public/api-data/ops/rot90.json"),
  "round": () => import("../public/api-data/ops/round.json"),
  "row_stack": () => import("../public/api-data/ops/row_stack.json"),
  "save": () => import("../public/api-data/ops/save.json"),
  "savetxt": () => import("../public/api-data/ops/savetxt.json"),
  "savez": () => import("../public/api-data/ops/savez.json"),
  "savez_compressed": () => import("../public/api-data/ops/savez_compressed.json"),
  "searchsorted": () => import("../public/api-data/ops/searchsorted.json"),
  "select": () => import("../public/api-data/ops/select.json"),
  "setbufsize": () => import("../public/api-data/ops/setbufsize.json"),
  "setdiff1d": () => import("../public/api-data/ops/setdiff1d.json"),
  "seterr": () => import("../public/api-data/ops/seterr.json"),
  "seterrcall": () => import("../public/api-data/ops/seterrcall.json"),
  "setxor1d": () => import("../public/api-data/ops/setxor1d.json"),
  "shape": () => import("../public/api-data/ops/shape.json"),
  "shares_memory": () => import("../public/api-data/ops/shares_memory.json"),
  "show_config": () => import("../public/api-data/ops/show_config.json"),
  "show_runtime": () => import("../public/api-data/ops/show_runtime.json"),
  "sign": () => import("../public/api-data/ops/sign.json"),
  "signbit": () => import("../public/api-data/ops/signbit.json"),
  "sin": () => import("../public/api-data/ops/sin.json"),
  "sinc": () => import("../public/api-data/ops/sinc.json"),
  "sinh": () => import("../public/api-data/ops/sinh.json"),
  "size": () => import("../public/api-data/ops/size.json"),
  "sort": () => import("../public/api-data/ops/sort.json"),
  "sort_complex": () => import("../public/api-data/ops/sort_complex.json"),
  "spacing": () => import("../public/api-data/ops/spacing.json"),
  "split": () => import("../public/api-data/ops/split.json"),
  "sqrt": () => import("../public/api-data/ops/sqrt.json"),
  "square": () => import("../public/api-data/ops/square.json"),
  "squeeze": () => import("../public/api-data/ops/squeeze.json"),
  "stack": () => import("../public/api-data/ops/stack.json"),
  "stats.cauchy.cdf": () => import("../public/api-data/ops/stats.cauchy.cdf.json"),
  "stats.cauchy.pdf": () => import("../public/api-data/ops/stats.cauchy.pdf.json"),
  "stats.cauchy.ppf": () => import("../public/api-data/ops/stats.cauchy.ppf.json"),
  "stats.expon.cdf": () => import("../public/api-data/ops/stats.expon.cdf.json"),
  "stats.expon.pdf": () => import("../public/api-data/ops/stats.expon.pdf.json"),
  "stats.expon.ppf": () => import("../public/api-data/ops/stats.expon.ppf.json"),
  "stats.laplace.cdf": () => import("../public/api-data/ops/stats.laplace.cdf.json"),
  "stats.laplace.pdf": () => import("../public/api-data/ops/stats.laplace.pdf.json"),
  "stats.laplace.ppf": () => import("../public/api-data/ops/stats.laplace.ppf.json"),
  "stats.logistic.cdf": () => import("../public/api-data/ops/stats.logistic.cdf.json"),
  "stats.logistic.pdf": () => import("../public/api-data/ops/stats.logistic.pdf.json"),
  "stats.logistic.ppf": () => import("../public/api-data/ops/stats.logistic.ppf.json"),
  "stats.lognorm.cdf": () => import("../public/api-data/ops/stats.lognorm.cdf.json"),
  "stats.lognorm.pdf": () => import("../public/api-data/ops/stats.lognorm.pdf.json"),
  "stats.lognorm.ppf": () => import("../public/api-data/ops/stats.lognorm.ppf.json"),
  "stats.norm.cdf": () => import("../public/api-data/ops/stats.norm.cdf.json"),
  "stats.norm.pdf": () => import("../public/api-data/ops/stats.norm.pdf.json"),
  "stats.norm.ppf": () => import("../public/api-data/ops/stats.norm.ppf.json"),
  "stats.truncnorm.cdf": () => import("../public/api-data/ops/stats.truncnorm.cdf.json"),
  "stats.truncnorm.pdf": () => import("../public/api-data/ops/stats.truncnorm.pdf.json"),
  "stats.truncnorm.ppf": () => import("../public/api-data/ops/stats.truncnorm.ppf.json"),
  "stats.uniform.cdf": () => import("../public/api-data/ops/stats.uniform.cdf.json"),
  "stats.uniform.pdf": () => import("../public/api-data/ops/stats.uniform.pdf.json"),
  "stats.uniform.ppf": () => import("../public/api-data/ops/stats.uniform.ppf.json"),
  "std": () => import("../public/api-data/ops/std.json"),
  "subtract": () => import("../public/api-data/ops/subtract.json"),
  "sum": () => import("../public/api-data/ops/sum.json"),
  "swapaxes": () => import("../public/api-data/ops/swapaxes.json"),
  "take": () => import("../public/api-data/ops/take.json"),
  "take_along_axis": () => import("../public/api-data/ops/take_along_axis.json"),
  "tan": () => import("../public/api-data/ops/tan.json"),
  "tanh": () => import("../public/api-data/ops/tanh.json"),
  "tensordot": () => import("../public/api-data/ops/tensordot.json"),
  "tile": () => import("../public/api-data/ops/tile.json"),
  "trace": () => import("../public/api-data/ops/trace.json"),
  "transpose": () => import("../public/api-data/ops/transpose.json"),
  "trapezoid": () => import("../public/api-data/ops/trapezoid.json"),
  "trapz": () => import("../public/api-data/ops/trapz.json"),
  "tri": () => import("../public/api-data/ops/tri.json"),
  "tril": () => import("../public/api-data/ops/tril.json"),
  "tril_indices": () => import("../public/api-data/ops/tril_indices.json"),
  "tril_indices_from": () => import("../public/api-data/ops/tril_indices_from.json"),
  "trim_zeros": () => import("../public/api-data/ops/trim_zeros.json"),
  "triu": () => import("../public/api-data/ops/triu.json"),
  "triu_indices": () => import("../public/api-data/ops/triu_indices.json"),
  "triu_indices_from": () => import("../public/api-data/ops/triu_indices_from.json"),
  "true_divide": () => import("../public/api-data/ops/true_divide.json"),
  "trunc": () => import("../public/api-data/ops/trunc.json"),
  "typename": () => import("../public/api-data/ops/typename.json"),
  "union1d": () => import("../public/api-data/ops/union1d.json"),
  "unique": () => import("../public/api-data/ops/unique.json"),
  "unique_all": () => import("../public/api-data/ops/unique_all.json"),
  "unique_counts": () => import("../public/api-data/ops/unique_counts.json"),
  "unique_inverse": () => import("../public/api-data/ops/unique_inverse.json"),
  "unique_values": () => import("../public/api-data/ops/unique_values.json"),
  "unpackbits": () => import("../public/api-data/ops/unpackbits.json"),
  "unravel_index": () => import("../public/api-data/ops/unravel_index.json"),
  "unstack": () => import("../public/api-data/ops/unstack.json"),
  "unwrap": () => import("../public/api-data/ops/unwrap.json"),
  "vander": () => import("../public/api-data/ops/vander.json"),
  "var": () => import("../public/api-data/ops/var.json"),
  "vdot": () => import("../public/api-data/ops/vdot.json"),
  "vecdot": () => import("../public/api-data/ops/vecdot.json"),
  "vecmat": () => import("../public/api-data/ops/vecmat.json"),
  "vsplit": () => import("../public/api-data/ops/vsplit.json"),
  "vstack": () => import("../public/api-data/ops/vstack.json"),
  "where": () => import("../public/api-data/ops/where.json"),
  "zeros": () => import("../public/api-data/ops/zeros.json"),
  "zeros_like": () => import("../public/api-data/ops/zeros_like.json"),
};

export const opDocSlugs = [
  "abs",
  "absolute",
  "acos",
  "acosh",
  "add",
  "all",
  "allclose",
  "amax",
  "amin",
  "angle",
  "any",
  "append",
  "apply_along_axis",
  "apply_over_axes",
  "arange",
  "arccos",
  "arccosh",
  "arcsin",
  "arcsinh",
  "arctan",
  "arctan2",
  "arctanh",
  "argmax",
  "argmin",
  "argpartition",
  "argsort",
  "argwhere",
  "around",
  "array",
  "array2string",
  "array_equal",
  "array_equiv",
  "array_repr",
  "array_split",
  "array_str",
  "asarray",
  "asarray_chkfinite",
  "asin",
  "asinh",
  "asmatrix",
  "astype",
  "atan",
  "atan2",
  "atanh",
  "atleast_1d",
  "atleast_2d",
  "atleast_3d",
  "average",
  "bartlett",
  "base_repr",
  "binary_repr",
  "bincount",
  "bitwise_and",
  "bitwise_count",
  "bitwise_invert",
  "bitwise_left_shift",
  "bitwise_not",
  "bitwise_or",
  "bitwise_right_shift",
  "bitwise_xor",
  "blackman",
  "block",
  "bmat",
  "broadcast_arrays",
  "broadcast_shapes",
  "broadcast_to",
  "busday_count",
  "busday_offset",
  "can_cast",
  "cbrt",
  "ceil",
  "choose",
  "clip",
  "column_stack",
  "common_type",
  "compress",
  "concat",
  "concatenate",
  "conj",
  "conjugate",
  "convolve",
  "copy",
  "copysign",
  "copyto",
  "corrcoef",
  "correlate",
  "cos",
  "cosh",
  "count_nonzero",
  "cov",
  "cross",
  "cumprod",
  "cumsum",
  "cumulative_prod",
  "cumulative_sum",
  "datetime_as_string",
  "datetime_data",
  "deg2rad",
  "degrees",
  "delete",
  "diag",
  "diag_indices",
  "diag_indices_from",
  "diagflat",
  "diagonal",
  "diff",
  "digitize",
  "divide",
  "divmod",
  "dot",
  "dsplit",
  "dstack",
  "ediff1d",
  "einsum",
  "einsum_path",
  "empty",
  "empty_like",
  "equal",
  "exp",
  "exp2",
  "expand_dims",
  "expm1",
  "extract",
  "eye",
  "fabs",
  "fft.fft",
  "fft.fft2",
  "fft.fftfreq",
  "fft.fftn",
  "fft.fftshift",
  "fft.hfft",
  "fft.ifft",
  "fft.ifft2",
  "fft.ifftn",
  "fft.ifftshift",
  "fft.ihfft",
  "fft.irfft",
  "fft.irfft2",
  "fft.irfftn",
  "fft.rfft",
  "fft.rfft2",
  "fft.rfftfreq",
  "fft.rfftn",
  "fill_diagonal",
  "fix",
  "flatnonzero",
  "flip",
  "fliplr",
  "flipud",
  "float_power",
  "floor",
  "floor_divide",
  "fmax",
  "fmin",
  "fmod",
  "format_float_positional",
  "format_float_scientific",
  "frexp",
  "from_dlpack",
  "frombuffer",
  "fromfile",
  "fromfunction",
  "fromiter",
  "frompyfunc",
  "fromregex",
  "fromstring",
  "full",
  "full_like",
  "gcd",
  "genfromtxt",
  "geomspace",
  "get_include",
  "getbufsize",
  "geterr",
  "geterrcall",
  "gradient",
  "greater",
  "greater_equal",
  "hamming",
  "hanning",
  "heaviside",
  "histogram",
  "histogram2d",
  "histogram_bin_edges",
  "histogramdd",
  "hsplit",
  "hstack",
  "hypot",
  "i0",
  "identity",
  "imag",
  "in1d",
  "indices",
  "inner",
  "insert",
  "interp",
  "intersect1d",
  "invert",
  "is_busday",
  "isclose",
  "iscomplex",
  "iscomplexobj",
  "isdtype",
  "isfinite",
  "isfortran",
  "isin",
  "isinf",
  "isnan",
  "isnat",
  "isneginf",
  "isposinf",
  "isreal",
  "isrealobj",
  "isscalar",
  "issubdtype",
  "iterable",
  "ix_",
  "kaiser",
  "kron",
  "lcm",
  "ldexp",
  "left_shift",
  "less",
  "less_equal",
  "lexsort",
  "linalg.cholesky",
  "linalg.cond",
  "linalg.cross",
  "linalg.det",
  "linalg.diagonal",
  "linalg.eig",
  "linalg.eigh",
  "linalg.eigvals",
  "linalg.eigvalsh",
  "linalg.inv",
  "linalg.lstsq",
  "linalg.matmul",
  "linalg.matrix_norm",
  "linalg.matrix_power",
  "linalg.matrix_rank",
  "linalg.matrix_transpose",
  "linalg.multi_dot",
  "linalg.norm",
  "linalg.outer",
  "linalg.pinv",
  "linalg.qr",
  "linalg.slogdet",
  "linalg.solve",
  "linalg.svd",
  "linalg.svdvals",
  "linalg.tensordot",
  "linalg.tensorinv",
  "linalg.tensorsolve",
  "linalg.trace",
  "linalg.vecdot",
  "linalg.vector_norm",
  "linspace",
  "load",
  "loadtxt",
  "log",
  "log10",
  "log1p",
  "log2",
  "logaddexp",
  "logaddexp2",
  "logical_and",
  "logical_not",
  "logical_or",
  "logical_xor",
  "logspace",
  "mask_indices",
  "matmul",
  "matrix_transpose",
  "matvec",
  "max",
  "maximum",
  "may_share_memory",
  "mean",
  "median",
  "meshgrid",
  "min",
  "min_scalar_type",
  "minimum",
  "mintypecode",
  "mod",
  "modf",
  "moveaxis",
  "multiply",
  "nan_to_num",
  "nanargmax",
  "nanargmin",
  "nancumprod",
  "nancumsum",
  "nanmax",
  "nanmean",
  "nanmedian",
  "nanmin",
  "nanpercentile",
  "nanprod",
  "nanquantile",
  "nanstd",
  "nansum",
  "nanvar",
  "ndim",
  "negative",
  "nested_iters",
  "nextafter",
  "nonzero",
  "not_equal",
  "ones",
  "ones_like",
  "outer",
  "packbits",
  "pad",
  "partition",
  "percentile",
  "permute_dims",
  "piecewise",
  "place",
  "poly",
  "polyadd",
  "polyder",
  "polydiv",
  "polyfit",
  "polyint",
  "polymul",
  "polysub",
  "polyval",
  "positive",
  "pow",
  "power",
  "prod",
  "promote_types",
  "ptp",
  "put",
  "put_along_axis",
  "putmask",
  "quantile",
  "rad2deg",
  "radians",
  "random.beta",
  "random.binomial",
  "random.bytes",
  "random.chisquare",
  "random.choice",
  "random.default_rng",
  "random.dirichlet",
  "random.exponential",
  "random.f",
  "random.gamma",
  "random.geometric",
  "random.get_state",
  "random.gumbel",
  "random.hypergeometric",
  "random.laplace",
  "random.logistic",
  "random.lognormal",
  "random.logseries",
  "random.multinomial",
  "random.multivariate_normal",
  "random.negative_binomial",
  "random.noncentral_chisquare",
  "random.noncentral_f",
  "random.normal",
  "random.pareto",
  "random.permutation",
  "random.poisson",
  "random.power",
  "random.rand",
  "random.randint",
  "random.randn",
  "random.random",
  "random.random_integers",
  "random.random_sample",
  "random.ranf",
  "random.rayleigh",
  "random.sample",
  "random.seed",
  "random.set_state",
  "random.shuffle",
  "random.standard_cauchy",
  "random.standard_exponential",
  "random.standard_gamma",
  "random.standard_normal",
  "random.standard_t",
  "random.triangular",
  "random.uniform",
  "random.vonmises",
  "random.wald",
  "random.weibull",
  "random.zipf",
  "ravel",
  "ravel_multi_index",
  "real",
  "real_if_close",
  "reciprocal",
  "remainder",
  "repeat",
  "require",
  "reshape",
  "resize",
  "result_type",
  "right_shift",
  "rint",
  "roll",
  "rollaxis",
  "roots",
  "rot90",
  "round",
  "row_stack",
  "save",
  "savetxt",
  "savez",
  "savez_compressed",
  "searchsorted",
  "select",
  "setbufsize",
  "setdiff1d",
  "seterr",
  "seterrcall",
  "setxor1d",
  "shape",
  "shares_memory",
  "show_config",
  "show_runtime",
  "sign",
  "signbit",
  "sin",
  "sinc",
  "sinh",
  "size",
  "sort",
  "sort_complex",
  "spacing",
  "split",
  "sqrt",
  "square",
  "squeeze",
  "stack",
  "stats.cauchy.cdf",
  "stats.cauchy.pdf",
  "stats.cauchy.ppf",
  "stats.expon.cdf",
  "stats.expon.pdf",
  "stats.expon.ppf",
  "stats.laplace.cdf",
  "stats.laplace.pdf",
  "stats.laplace.ppf",
  "stats.logistic.cdf",
  "stats.logistic.pdf",
  "stats.logistic.ppf",
  "stats.lognorm.cdf",
  "stats.lognorm.pdf",
  "stats.lognorm.ppf",
  "stats.norm.cdf",
  "stats.norm.pdf",
  "stats.norm.ppf",
  "stats.truncnorm.cdf",
  "stats.truncnorm.pdf",
  "stats.truncnorm.ppf",
  "stats.uniform.cdf",
  "stats.uniform.pdf",
  "stats.uniform.ppf",
  "std",
  "subtract",
  "sum",
  "swapaxes",
  "take",
  "take_along_axis",
  "tan",
  "tanh",
  "tensordot",
  "tile",
  "trace",
  "transpose",
  "trapezoid",
  "trapz",
  "tri",
  "tril",
  "tril_indices",
  "tril_indices_from",
  "trim_zeros",
  "triu",
  "triu_indices",
  "triu_indices_from",
  "true_divide",
  "trunc",
  "typename",
  "union1d",
  "unique",
  "unique_all",
  "unique_counts",
  "unique_inverse",
  "unique_values",
  "unpackbits",
  "unravel_index",
  "unstack",
  "unwrap",
  "vander",
  "var",
  "vdot",
  "vecdot",
  "vecmat",
  "vsplit",
  "vstack",
  "where",
  "zeros",
  "zeros_like",
] as const;
