export const publicApiLeafImports: Record<string, () => Promise<{ default: unknown }>> = {
  "flops.stats.cauchy.cdf": () => import("./public-api/flops-stats-cauchy-cdf.json"),
  "flops.stats.cauchy.pdf": () => import("./public-api/flops-stats-cauchy-pdf.json"),
  "flops.stats.cauchy.ppf": () => import("./public-api/flops-stats-cauchy-ppf.json"),
  "flops.stats.expon.cdf": () => import("./public-api/flops-stats-expon-cdf.json"),
  "flops.stats.expon.pdf": () => import("./public-api/flops-stats-expon-pdf.json"),
  "flops.stats.expon.ppf": () => import("./public-api/flops-stats-expon-ppf.json"),
  "flops.stats.laplace.cdf": () => import("./public-api/flops-stats-laplace-cdf.json"),
  "flops.stats.laplace.pdf": () => import("./public-api/flops-stats-laplace-pdf.json"),
  "flops.stats.laplace.ppf": () => import("./public-api/flops-stats-laplace-ppf.json"),
  "flops.stats.logistic.cdf": () => import("./public-api/flops-stats-logistic-cdf.json"),
  "flops.stats.logistic.pdf": () => import("./public-api/flops-stats-logistic-pdf.json"),
  "flops.stats.logistic.ppf": () => import("./public-api/flops-stats-logistic-ppf.json"),
  "flops.stats.lognorm.cdf": () => import("./public-api/flops-stats-lognorm-cdf.json"),
  "flops.stats.lognorm.pdf": () => import("./public-api/flops-stats-lognorm-pdf.json"),
  "flops.stats.lognorm.ppf": () => import("./public-api/flops-stats-lognorm-ppf.json"),
  "flops.stats.norm.cdf": () => import("./public-api/flops-stats-norm-cdf.json"),
  "flops.stats.norm.pdf": () => import("./public-api/flops-stats-norm-pdf.json"),
  "flops.stats.norm.ppf": () => import("./public-api/flops-stats-norm-ppf.json"),
  "flops.stats.truncnorm.cdf": () => import("./public-api/flops-stats-truncnorm-cdf.json"),
  "flops.stats.truncnorm.pdf": () => import("./public-api/flops-stats-truncnorm-pdf.json"),
  "flops.stats.truncnorm.ppf": () => import("./public-api/flops-stats-truncnorm-ppf.json"),
  "flops.stats.uniform.cdf": () => import("./public-api/flops-stats-uniform-cdf.json"),
  "flops.stats.uniform.pdf": () => import("./public-api/flops-stats-uniform-pdf.json"),
  "flops.stats.uniform.ppf": () => import("./public-api/flops-stats-uniform-ppf.json"),
  "flopscope.BudgetContext": () => import("./public-api/flopscope-budget-context.json"),
  "flopscope.FlopscopeArray": () => import("./public-api/flopscope-flopscope-array.json"),
  "flopscope.PathInfo": () => import("./public-api/flopscope-path-info.json"),
  "flopscope.StepInfo": () => import("./public-api/flopscope-step-info.json"),
  "flopscope.SymmetricTensor": () => import("./public-api/flopscope-symmetric-tensor.json"),
  "flopscope.accounting.bartlett_cost": () => import("./public-api/flopscope-accounting-bartlett-cost.json"),
  "flopscope.accounting.blackman_cost": () => import("./public-api/flopscope-accounting-blackman-cost.json"),
  "flopscope.accounting.cholesky_cost": () => import("./public-api/flopscope-accounting-cholesky-cost.json"),
  "flopscope.accounting.cond_cost": () => import("./public-api/flopscope-accounting-cond-cost.json"),
  "flopscope.accounting.det_cost": () => import("./public-api/flopscope-accounting-det-cost.json"),
  "flopscope.accounting.eig_cost": () => import("./public-api/flopscope-accounting-eig-cost.json"),
  "flopscope.accounting.eigh_cost": () => import("./public-api/flopscope-accounting-eigh-cost.json"),
  "flopscope.accounting.eigvals_cost": () => import("./public-api/flopscope-accounting-eigvals-cost.json"),
  "flopscope.accounting.eigvalsh_cost": () => import("./public-api/flopscope-accounting-eigvalsh-cost.json"),
  "flopscope.accounting.einsum_cost": () => import("./public-api/flopscope-accounting-einsum-cost.json"),
  "flopscope.accounting.fft_cost": () => import("./public-api/flopscope-accounting-fft-cost.json"),
  "flopscope.accounting.fftn_cost": () => import("./public-api/flopscope-accounting-fftn-cost.json"),
  "flopscope.accounting.hamming_cost": () => import("./public-api/flopscope-accounting-hamming-cost.json"),
  "flopscope.accounting.hanning_cost": () => import("./public-api/flopscope-accounting-hanning-cost.json"),
  "flopscope.accounting.hfft_cost": () => import("./public-api/flopscope-accounting-hfft-cost.json"),
  "flopscope.accounting.inv_cost": () => import("./public-api/flopscope-accounting-inv-cost.json"),
  "flopscope.accounting.kaiser_cost": () => import("./public-api/flopscope-accounting-kaiser-cost.json"),
  "flopscope.accounting.lstsq_cost": () => import("./public-api/flopscope-accounting-lstsq-cost.json"),
  "flopscope.accounting.matrix_norm_cost": () => import("./public-api/flopscope-accounting-matrix-norm-cost.json"),
  "flopscope.accounting.matrix_power_cost": () => import("./public-api/flopscope-accounting-matrix-power-cost.json"),
  "flopscope.accounting.matrix_rank_cost": () => import("./public-api/flopscope-accounting-matrix-rank-cost.json"),
  "flopscope.accounting.multi_dot_cost": () => import("./public-api/flopscope-accounting-multi-dot-cost.json"),
  "flopscope.accounting.norm_cost": () => import("./public-api/flopscope-accounting-norm-cost.json"),
  "flopscope.accounting.pinv_cost": () => import("./public-api/flopscope-accounting-pinv-cost.json"),
  "flopscope.accounting.pointwise_cost": () => import("./public-api/flopscope-accounting-pointwise-cost.json"),
  "flopscope.accounting.poly_cost": () => import("./public-api/flopscope-accounting-poly-cost.json"),
  "flopscope.accounting.polyadd_cost": () => import("./public-api/flopscope-accounting-polyadd-cost.json"),
  "flopscope.accounting.polyder_cost": () => import("./public-api/flopscope-accounting-polyder-cost.json"),
  "flopscope.accounting.polydiv_cost": () => import("./public-api/flopscope-accounting-polydiv-cost.json"),
  "flopscope.accounting.polyfit_cost": () => import("./public-api/flopscope-accounting-polyfit-cost.json"),
  "flopscope.accounting.polyint_cost": () => import("./public-api/flopscope-accounting-polyint-cost.json"),
  "flopscope.accounting.polymul_cost": () => import("./public-api/flopscope-accounting-polymul-cost.json"),
  "flopscope.accounting.polysub_cost": () => import("./public-api/flopscope-accounting-polysub-cost.json"),
  "flopscope.accounting.polyval_cost": () => import("./public-api/flopscope-accounting-polyval-cost.json"),
  "flopscope.accounting.qr_cost": () => import("./public-api/flopscope-accounting-qr-cost.json"),
  "flopscope.accounting.reduction_cost": () => import("./public-api/flopscope-accounting-reduction-cost.json"),
  "flopscope.accounting.rfft_cost": () => import("./public-api/flopscope-accounting-rfft-cost.json"),
  "flopscope.accounting.rfftn_cost": () => import("./public-api/flopscope-accounting-rfftn-cost.json"),
  "flopscope.accounting.roots_cost": () => import("./public-api/flopscope-accounting-roots-cost.json"),
  "flopscope.accounting.slogdet_cost": () => import("./public-api/flopscope-accounting-slogdet-cost.json"),
  "flopscope.accounting.solve_cost": () => import("./public-api/flopscope-accounting-solve-cost.json"),
  "flopscope.accounting.svd_cost": () => import("./public-api/flopscope-accounting-svd-cost.json"),
  "flopscope.accounting.svdvals_cost": () => import("./public-api/flopscope-accounting-svdvals-cost.json"),
  "flopscope.accounting.tensorinv_cost": () => import("./public-api/flopscope-accounting-tensorinv-cost.json"),
  "flopscope.accounting.tensorsolve_cost": () => import("./public-api/flopscope-accounting-tensorsolve-cost.json"),
  "flopscope.accounting.trace_cost": () => import("./public-api/flopscope-accounting-trace-cost.json"),
  "flopscope.accounting.unwrap_cost": () => import("./public-api/flopscope-accounting-unwrap-cost.json"),
  "flopscope.accounting.vector_norm_cost": () => import("./public-api/flopscope-accounting-vector-norm-cost.json"),
  "flopscope.as_symmetric": () => import("./public-api/flopscope-as-symmetric.json"),
  "flopscope.budget": () => import("./public-api/flopscope-budget.json"),
  "flopscope.budget_live": () => import("./public-api/flopscope-budget-live.json"),
  "flopscope.budget_reset": () => import("./public-api/flopscope-budget-reset.json"),
  "flopscope.budget_summary": () => import("./public-api/flopscope-budget-summary.json"),
  "flopscope.budget_summary_dict": () => import("./public-api/flopscope-budget-summary-dict.json"),
  "flopscope.configure": () => import("./public-api/flopscope-configure.json"),
  "flopscope.is_symmetric": () => import("./public-api/flopscope-is-symmetric.json"),
  "flopscope.namespace": () => import("./public-api/flopscope-namespace.json"),
  "flopscope.numpy.absolute": () => import("./public-api/flopscope-numpy-absolute.json"),
  "flopscope.numpy.add": () => import("./public-api/flopscope-numpy-add.json"),
  "flopscope.numpy.all": () => import("./public-api/flopscope-numpy-all.json"),
  "flopscope.numpy.allclose": () => import("./public-api/flopscope-numpy-allclose.json"),
  "flopscope.numpy.angle": () => import("./public-api/flopscope-numpy-angle.json"),
  "flopscope.numpy.any": () => import("./public-api/flopscope-numpy-any.json"),
  "flopscope.numpy.append": () => import("./public-api/flopscope-numpy-append.json"),
  "flopscope.numpy.apply_along_axis": () => import("./public-api/flopscope-numpy-apply-along-axis.json"),
  "flopscope.numpy.apply_over_axes": () => import("./public-api/flopscope-numpy-apply-over-axes.json"),
  "flopscope.numpy.arange": () => import("./public-api/flopscope-numpy-arange.json"),
  "flopscope.numpy.arccos": () => import("./public-api/flopscope-numpy-arccos.json"),
  "flopscope.numpy.arccosh": () => import("./public-api/flopscope-numpy-arccosh.json"),
  "flopscope.numpy.arcsin": () => import("./public-api/flopscope-numpy-arcsin.json"),
  "flopscope.numpy.arcsinh": () => import("./public-api/flopscope-numpy-arcsinh.json"),
  "flopscope.numpy.arctan": () => import("./public-api/flopscope-numpy-arctan.json"),
  "flopscope.numpy.arctan2": () => import("./public-api/flopscope-numpy-arctan2.json"),
  "flopscope.numpy.arctanh": () => import("./public-api/flopscope-numpy-arctanh.json"),
  "flopscope.numpy.argmax": () => import("./public-api/flopscope-numpy-argmax.json"),
  "flopscope.numpy.argmin": () => import("./public-api/flopscope-numpy-argmin.json"),
  "flopscope.numpy.argpartition": () => import("./public-api/flopscope-numpy-argpartition.json"),
  "flopscope.numpy.argsort": () => import("./public-api/flopscope-numpy-argsort.json"),
  "flopscope.numpy.argwhere": () => import("./public-api/flopscope-numpy-argwhere.json"),
  "flopscope.numpy.array": () => import("./public-api/flopscope-numpy-array.json"),
  "flopscope.numpy.array_equal": () => import("./public-api/flopscope-numpy-array-equal.json"),
  "flopscope.numpy.array_equiv": () => import("./public-api/flopscope-numpy-array-equiv.json"),
  "flopscope.numpy.array_split": () => import("./public-api/flopscope-numpy-array-split.json"),
  "flopscope.numpy.asarray": () => import("./public-api/flopscope-numpy-asarray.json"),
  "flopscope.numpy.asarray_chkfinite": () => import("./public-api/flopscope-numpy-asarray-chkfinite.json"),
  "flopscope.numpy.astype": () => import("./public-api/flopscope-numpy-astype.json"),
  "flopscope.numpy.atleast_1d": () => import("./public-api/flopscope-numpy-atleast-1d.json"),
  "flopscope.numpy.atleast_2d": () => import("./public-api/flopscope-numpy-atleast-2d.json"),
  "flopscope.numpy.atleast_3d": () => import("./public-api/flopscope-numpy-atleast-3d.json"),
  "flopscope.numpy.average": () => import("./public-api/flopscope-numpy-average.json"),
  "flopscope.numpy.bartlett": () => import("./public-api/flopscope-numpy-bartlett.json"),
  "flopscope.numpy.bincount": () => import("./public-api/flopscope-numpy-bincount.json"),
  "flopscope.numpy.bitwise_and": () => import("./public-api/flopscope-numpy-bitwise-and.json"),
  "flopscope.numpy.bitwise_count": () => import("./public-api/flopscope-numpy-bitwise-count.json"),
  "flopscope.numpy.bitwise_left_shift": () => import("./public-api/flopscope-numpy-bitwise-left-shift.json"),
  "flopscope.numpy.bitwise_not": () => import("./public-api/flopscope-numpy-bitwise-not.json"),
  "flopscope.numpy.bitwise_or": () => import("./public-api/flopscope-numpy-bitwise-or.json"),
  "flopscope.numpy.bitwise_right_shift": () => import("./public-api/flopscope-numpy-bitwise-right-shift.json"),
  "flopscope.numpy.bitwise_xor": () => import("./public-api/flopscope-numpy-bitwise-xor.json"),
  "flopscope.numpy.blackman": () => import("./public-api/flopscope-numpy-blackman.json"),
  "flopscope.numpy.block": () => import("./public-api/flopscope-numpy-block.json"),
  "flopscope.numpy.bmat": () => import("./public-api/flopscope-numpy-bmat.json"),
  "flopscope.numpy.broadcast_arrays": () => import("./public-api/flopscope-numpy-broadcast-arrays.json"),
  "flopscope.numpy.broadcast_shapes": () => import("./public-api/flopscope-numpy-broadcast-shapes.json"),
  "flopscope.numpy.broadcast_to": () => import("./public-api/flopscope-numpy-broadcast-to.json"),
  "flopscope.numpy.can_cast": () => import("./public-api/flopscope-numpy-can-cast.json"),
  "flopscope.numpy.cbrt": () => import("./public-api/flopscope-numpy-cbrt.json"),
  "flopscope.numpy.ceil": () => import("./public-api/flopscope-numpy-ceil.json"),
  "flopscope.numpy.choose": () => import("./public-api/flopscope-numpy-choose.json"),
  "flopscope.numpy.clip": () => import("./public-api/flopscope-numpy-clip.json"),
  "flopscope.numpy.column_stack": () => import("./public-api/flopscope-numpy-column-stack.json"),
  "flopscope.numpy.common_type": () => import("./public-api/flopscope-numpy-common-type.json"),
  "flopscope.numpy.compress": () => import("./public-api/flopscope-numpy-compress.json"),
  "flopscope.numpy.concatenate": () => import("./public-api/flopscope-numpy-concatenate.json"),
  "flopscope.numpy.conj": () => import("./public-api/flopscope-numpy-conj.json"),
  "flopscope.numpy.conjugate": () => import("./public-api/flopscope-numpy-conjugate.json"),
  "flopscope.numpy.convolve": () => import("./public-api/flopscope-numpy-convolve.json"),
  "flopscope.numpy.copy": () => import("./public-api/flopscope-numpy-copy.json"),
  "flopscope.numpy.copysign": () => import("./public-api/flopscope-numpy-copysign.json"),
  "flopscope.numpy.copyto": () => import("./public-api/flopscope-numpy-copyto.json"),
  "flopscope.numpy.corrcoef": () => import("./public-api/flopscope-numpy-corrcoef.json"),
  "flopscope.numpy.correlate": () => import("./public-api/flopscope-numpy-correlate.json"),
  "flopscope.numpy.cos": () => import("./public-api/flopscope-numpy-cos.json"),
  "flopscope.numpy.cosh": () => import("./public-api/flopscope-numpy-cosh.json"),
  "flopscope.numpy.count_nonzero": () => import("./public-api/flopscope-numpy-count-nonzero.json"),
  "flopscope.numpy.cov": () => import("./public-api/flopscope-numpy-cov.json"),
  "flopscope.numpy.cross": () => import("./public-api/flopscope-numpy-cross.json"),
  "flopscope.numpy.cumprod": () => import("./public-api/flopscope-numpy-cumprod.json"),
  "flopscope.numpy.cumsum": () => import("./public-api/flopscope-numpy-cumsum.json"),
  "flopscope.numpy.cumulative_prod": () => import("./public-api/flopscope-numpy-cumulative-prod.json"),
  "flopscope.numpy.cumulative_sum": () => import("./public-api/flopscope-numpy-cumulative-sum.json"),
  "flopscope.numpy.degrees": () => import("./public-api/flopscope-numpy-degrees.json"),
  "flopscope.numpy.delete": () => import("./public-api/flopscope-numpy-delete.json"),
  "flopscope.numpy.diag": () => import("./public-api/flopscope-numpy-diag.json"),
  "flopscope.numpy.diag_indices": () => import("./public-api/flopscope-numpy-diag-indices.json"),
  "flopscope.numpy.diag_indices_from": () => import("./public-api/flopscope-numpy-diag-indices-from.json"),
  "flopscope.numpy.diagflat": () => import("./public-api/flopscope-numpy-diagflat.json"),
  "flopscope.numpy.diagonal": () => import("./public-api/flopscope-numpy-diagonal.json"),
  "flopscope.numpy.diff": () => import("./public-api/flopscope-numpy-diff.json"),
  "flopscope.numpy.digitize": () => import("./public-api/flopscope-numpy-digitize.json"),
  "flopscope.numpy.divide": () => import("./public-api/flopscope-numpy-divide.json"),
  "flopscope.numpy.dot": () => import("./public-api/flopscope-numpy-dot.json"),
  "flopscope.numpy.dsplit": () => import("./public-api/flopscope-numpy-dsplit.json"),
  "flopscope.numpy.dstack": () => import("./public-api/flopscope-numpy-dstack.json"),
  "flopscope.numpy.ediff1d": () => import("./public-api/flopscope-numpy-ediff1d.json"),
  "flopscope.numpy.einsum": () => import("./public-api/flopscope-numpy-einsum.json"),
  "flopscope.numpy.einsum_path": () => import("./public-api/flopscope-numpy-einsum-path.json"),
  "flopscope.numpy.empty": () => import("./public-api/flopscope-numpy-empty.json"),
  "flopscope.numpy.empty_like": () => import("./public-api/flopscope-numpy-empty-like.json"),
  "flopscope.numpy.equal": () => import("./public-api/flopscope-numpy-equal.json"),
  "flopscope.numpy.exp": () => import("./public-api/flopscope-numpy-exp.json"),
  "flopscope.numpy.exp2": () => import("./public-api/flopscope-numpy-exp2.json"),
  "flopscope.numpy.expand_dims": () => import("./public-api/flopscope-numpy-expand-dims.json"),
  "flopscope.numpy.expm1": () => import("./public-api/flopscope-numpy-expm1.json"),
  "flopscope.numpy.extract": () => import("./public-api/flopscope-numpy-extract.json"),
  "flopscope.numpy.eye": () => import("./public-api/flopscope-numpy-eye.json"),
  "flopscope.numpy.fabs": () => import("./public-api/flopscope-numpy-fabs.json"),
  "flopscope.numpy.fft.fft": () => import("./public-api/flopscope-numpy-fft-fft.json"),
  "flopscope.numpy.fft.fft2": () => import("./public-api/flopscope-numpy-fft-fft2.json"),
  "flopscope.numpy.fft.fftfreq": () => import("./public-api/flopscope-numpy-fft-fftfreq.json"),
  "flopscope.numpy.fft.fftn": () => import("./public-api/flopscope-numpy-fft-fftn.json"),
  "flopscope.numpy.fft.fftshift": () => import("./public-api/flopscope-numpy-fft-fftshift.json"),
  "flopscope.numpy.fft.hfft": () => import("./public-api/flopscope-numpy-fft-hfft.json"),
  "flopscope.numpy.fft.ifft": () => import("./public-api/flopscope-numpy-fft-ifft.json"),
  "flopscope.numpy.fft.ifft2": () => import("./public-api/flopscope-numpy-fft-ifft2.json"),
  "flopscope.numpy.fft.ifftn": () => import("./public-api/flopscope-numpy-fft-ifftn.json"),
  "flopscope.numpy.fft.ifftshift": () => import("./public-api/flopscope-numpy-fft-ifftshift.json"),
  "flopscope.numpy.fft.ihfft": () => import("./public-api/flopscope-numpy-fft-ihfft.json"),
  "flopscope.numpy.fft.irfft": () => import("./public-api/flopscope-numpy-fft-irfft.json"),
  "flopscope.numpy.fft.irfft2": () => import("./public-api/flopscope-numpy-fft-irfft2.json"),
  "flopscope.numpy.fft.irfftn": () => import("./public-api/flopscope-numpy-fft-irfftn.json"),
  "flopscope.numpy.fft.rfft": () => import("./public-api/flopscope-numpy-fft-rfft.json"),
  "flopscope.numpy.fft.rfft2": () => import("./public-api/flopscope-numpy-fft-rfft2.json"),
  "flopscope.numpy.fft.rfftfreq": () => import("./public-api/flopscope-numpy-fft-rfftfreq.json"),
  "flopscope.numpy.fft.rfftn": () => import("./public-api/flopscope-numpy-fft-rfftn.json"),
  "flopscope.numpy.fill_diagonal": () => import("./public-api/flopscope-numpy-fill-diagonal.json"),
  "flopscope.numpy.flatnonzero": () => import("./public-api/flopscope-numpy-flatnonzero.json"),
  "flopscope.numpy.flip": () => import("./public-api/flopscope-numpy-flip.json"),
  "flopscope.numpy.fliplr": () => import("./public-api/flopscope-numpy-fliplr.json"),
  "flopscope.numpy.flipud": () => import("./public-api/flopscope-numpy-flipud.json"),
  "flopscope.numpy.float_power": () => import("./public-api/flopscope-numpy-float-power.json"),
  "flopscope.numpy.floor": () => import("./public-api/flopscope-numpy-floor.json"),
  "flopscope.numpy.floor_divide": () => import("./public-api/flopscope-numpy-floor-divide.json"),
  "flopscope.numpy.fmax": () => import("./public-api/flopscope-numpy-fmax.json"),
  "flopscope.numpy.fmin": () => import("./public-api/flopscope-numpy-fmin.json"),
  "flopscope.numpy.fmod": () => import("./public-api/flopscope-numpy-fmod.json"),
  "flopscope.numpy.frexp": () => import("./public-api/flopscope-numpy-frexp.json"),
  "flopscope.numpy.from_dlpack": () => import("./public-api/flopscope-numpy-from-dlpack.json"),
  "flopscope.numpy.frombuffer": () => import("./public-api/flopscope-numpy-frombuffer.json"),
  "flopscope.numpy.fromfunction": () => import("./public-api/flopscope-numpy-fromfunction.json"),
  "flopscope.numpy.fromiter": () => import("./public-api/flopscope-numpy-fromiter.json"),
  "flopscope.numpy.full": () => import("./public-api/flopscope-numpy-full.json"),
  "flopscope.numpy.full_like": () => import("./public-api/flopscope-numpy-full-like.json"),
  "flopscope.numpy.gcd": () => import("./public-api/flopscope-numpy-gcd.json"),
  "flopscope.numpy.geomspace": () => import("./public-api/flopscope-numpy-geomspace.json"),
  "flopscope.numpy.gradient": () => import("./public-api/flopscope-numpy-gradient.json"),
  "flopscope.numpy.greater": () => import("./public-api/flopscope-numpy-greater.json"),
  "flopscope.numpy.greater_equal": () => import("./public-api/flopscope-numpy-greater-equal.json"),
  "flopscope.numpy.hamming": () => import("./public-api/flopscope-numpy-hamming.json"),
  "flopscope.numpy.hanning": () => import("./public-api/flopscope-numpy-hanning.json"),
  "flopscope.numpy.heaviside": () => import("./public-api/flopscope-numpy-heaviside.json"),
  "flopscope.numpy.histogram": () => import("./public-api/flopscope-numpy-histogram.json"),
  "flopscope.numpy.histogram2d": () => import("./public-api/flopscope-numpy-histogram2d.json"),
  "flopscope.numpy.histogram_bin_edges": () => import("./public-api/flopscope-numpy-histogram-bin-edges.json"),
  "flopscope.numpy.histogramdd": () => import("./public-api/flopscope-numpy-histogramdd.json"),
  "flopscope.numpy.hsplit": () => import("./public-api/flopscope-numpy-hsplit.json"),
  "flopscope.numpy.hstack": () => import("./public-api/flopscope-numpy-hstack.json"),
  "flopscope.numpy.hypot": () => import("./public-api/flopscope-numpy-hypot.json"),
  "flopscope.numpy.i0": () => import("./public-api/flopscope-numpy-i0.json"),
  "flopscope.numpy.identity": () => import("./public-api/flopscope-numpy-identity.json"),
  "flopscope.numpy.imag": () => import("./public-api/flopscope-numpy-imag.json"),
  "flopscope.numpy.in1d": () => import("./public-api/flopscope-numpy-in1d.json"),
  "flopscope.numpy.indices": () => import("./public-api/flopscope-numpy-indices.json"),
  "flopscope.numpy.inner": () => import("./public-api/flopscope-numpy-inner.json"),
  "flopscope.numpy.insert": () => import("./public-api/flopscope-numpy-insert.json"),
  "flopscope.numpy.interp": () => import("./public-api/flopscope-numpy-interp.json"),
  "flopscope.numpy.intersect1d": () => import("./public-api/flopscope-numpy-intersect1d.json"),
  "flopscope.numpy.invert": () => import("./public-api/flopscope-numpy-invert.json"),
  "flopscope.numpy.isclose": () => import("./public-api/flopscope-numpy-isclose.json"),
  "flopscope.numpy.iscomplex": () => import("./public-api/flopscope-numpy-iscomplex.json"),
  "flopscope.numpy.iscomplexobj": () => import("./public-api/flopscope-numpy-iscomplexobj.json"),
  "flopscope.numpy.isdtype": () => import("./public-api/flopscope-numpy-isdtype.json"),
  "flopscope.numpy.isfinite": () => import("./public-api/flopscope-numpy-isfinite.json"),
  "flopscope.numpy.isfortran": () => import("./public-api/flopscope-numpy-isfortran.json"),
  "flopscope.numpy.isin": () => import("./public-api/flopscope-numpy-isin.json"),
  "flopscope.numpy.isinf": () => import("./public-api/flopscope-numpy-isinf.json"),
  "flopscope.numpy.isnan": () => import("./public-api/flopscope-numpy-isnan.json"),
  "flopscope.numpy.isneginf": () => import("./public-api/flopscope-numpy-isneginf.json"),
  "flopscope.numpy.isposinf": () => import("./public-api/flopscope-numpy-isposinf.json"),
  "flopscope.numpy.isreal": () => import("./public-api/flopscope-numpy-isreal.json"),
  "flopscope.numpy.isrealobj": () => import("./public-api/flopscope-numpy-isrealobj.json"),
  "flopscope.numpy.isscalar": () => import("./public-api/flopscope-numpy-isscalar.json"),
  "flopscope.numpy.issubdtype": () => import("./public-api/flopscope-numpy-issubdtype.json"),
  "flopscope.numpy.iterable": () => import("./public-api/flopscope-numpy-iterable.json"),
  "flopscope.numpy.ix_": () => import("./public-api/flopscope-numpy-ix-.json"),
  "flopscope.numpy.kaiser": () => import("./public-api/flopscope-numpy-kaiser.json"),
  "flopscope.numpy.kron": () => import("./public-api/flopscope-numpy-kron.json"),
  "flopscope.numpy.lcm": () => import("./public-api/flopscope-numpy-lcm.json"),
  "flopscope.numpy.ldexp": () => import("./public-api/flopscope-numpy-ldexp.json"),
  "flopscope.numpy.left_shift": () => import("./public-api/flopscope-numpy-left-shift.json"),
  "flopscope.numpy.less": () => import("./public-api/flopscope-numpy-less.json"),
  "flopscope.numpy.less_equal": () => import("./public-api/flopscope-numpy-less-equal.json"),
  "flopscope.numpy.lexsort": () => import("./public-api/flopscope-numpy-lexsort.json"),
  "flopscope.numpy.linalg.cholesky": () => import("./public-api/flopscope-numpy-linalg-cholesky.json"),
  "flopscope.numpy.linalg.cond": () => import("./public-api/flopscope-numpy-linalg-cond.json"),
  "flopscope.numpy.linalg.cross": () => import("./public-api/flopscope-numpy-linalg-cross.json"),
  "flopscope.numpy.linalg.det": () => import("./public-api/flopscope-numpy-linalg-det.json"),
  "flopscope.numpy.linalg.diagonal": () => import("./public-api/flopscope-numpy-linalg-diagonal.json"),
  "flopscope.numpy.linalg.eig": () => import("./public-api/flopscope-numpy-linalg-eig.json"),
  "flopscope.numpy.linalg.eigh": () => import("./public-api/flopscope-numpy-linalg-eigh.json"),
  "flopscope.numpy.linalg.eigvals": () => import("./public-api/flopscope-numpy-linalg-eigvals.json"),
  "flopscope.numpy.linalg.eigvalsh": () => import("./public-api/flopscope-numpy-linalg-eigvalsh.json"),
  "flopscope.numpy.linalg.inv": () => import("./public-api/flopscope-numpy-linalg-inv.json"),
  "flopscope.numpy.linalg.lstsq": () => import("./public-api/flopscope-numpy-linalg-lstsq.json"),
  "flopscope.numpy.linalg.matmul": () => import("./public-api/flopscope-numpy-linalg-matmul.json"),
  "flopscope.numpy.linalg.matrix_norm": () => import("./public-api/flopscope-numpy-linalg-matrix-norm.json"),
  "flopscope.numpy.linalg.matrix_power": () => import("./public-api/flopscope-numpy-linalg-matrix-power.json"),
  "flopscope.numpy.linalg.matrix_rank": () => import("./public-api/flopscope-numpy-linalg-matrix-rank.json"),
  "flopscope.numpy.linalg.matrix_transpose": () => import("./public-api/flopscope-numpy-linalg-matrix-transpose.json"),
  "flopscope.numpy.linalg.multi_dot": () => import("./public-api/flopscope-numpy-linalg-multi-dot.json"),
  "flopscope.numpy.linalg.norm": () => import("./public-api/flopscope-numpy-linalg-norm.json"),
  "flopscope.numpy.linalg.outer": () => import("./public-api/flopscope-numpy-linalg-outer.json"),
  "flopscope.numpy.linalg.pinv": () => import("./public-api/flopscope-numpy-linalg-pinv.json"),
  "flopscope.numpy.linalg.qr": () => import("./public-api/flopscope-numpy-linalg-qr.json"),
  "flopscope.numpy.linalg.slogdet": () => import("./public-api/flopscope-numpy-linalg-slogdet.json"),
  "flopscope.numpy.linalg.solve": () => import("./public-api/flopscope-numpy-linalg-solve.json"),
  "flopscope.numpy.linalg.svd": () => import("./public-api/flopscope-numpy-linalg-svd.json"),
  "flopscope.numpy.linalg.svdvals": () => import("./public-api/flopscope-numpy-linalg-svdvals.json"),
  "flopscope.numpy.linalg.tensordot": () => import("./public-api/flopscope-numpy-linalg-tensordot.json"),
  "flopscope.numpy.linalg.tensorinv": () => import("./public-api/flopscope-numpy-linalg-tensorinv.json"),
  "flopscope.numpy.linalg.tensorsolve": () => import("./public-api/flopscope-numpy-linalg-tensorsolve.json"),
  "flopscope.numpy.linalg.trace": () => import("./public-api/flopscope-numpy-linalg-trace.json"),
  "flopscope.numpy.linalg.vecdot": () => import("./public-api/flopscope-numpy-linalg-vecdot.json"),
  "flopscope.numpy.linalg.vector_norm": () => import("./public-api/flopscope-numpy-linalg-vector-norm.json"),
  "flopscope.numpy.linspace": () => import("./public-api/flopscope-numpy-linspace.json"),
  "flopscope.numpy.log": () => import("./public-api/flopscope-numpy-log.json"),
  "flopscope.numpy.log10": () => import("./public-api/flopscope-numpy-log10.json"),
  "flopscope.numpy.log1p": () => import("./public-api/flopscope-numpy-log1p.json"),
  "flopscope.numpy.log2": () => import("./public-api/flopscope-numpy-log2.json"),
  "flopscope.numpy.logaddexp": () => import("./public-api/flopscope-numpy-logaddexp.json"),
  "flopscope.numpy.logaddexp2": () => import("./public-api/flopscope-numpy-logaddexp2.json"),
  "flopscope.numpy.logical_and": () => import("./public-api/flopscope-numpy-logical-and.json"),
  "flopscope.numpy.logical_not": () => import("./public-api/flopscope-numpy-logical-not.json"),
  "flopscope.numpy.logical_or": () => import("./public-api/flopscope-numpy-logical-or.json"),
  "flopscope.numpy.logical_xor": () => import("./public-api/flopscope-numpy-logical-xor.json"),
  "flopscope.numpy.logspace": () => import("./public-api/flopscope-numpy-logspace.json"),
  "flopscope.numpy.mask_indices": () => import("./public-api/flopscope-numpy-mask-indices.json"),
  "flopscope.numpy.matmul": () => import("./public-api/flopscope-numpy-matmul.json"),
  "flopscope.numpy.matrix_transpose": () => import("./public-api/flopscope-numpy-matrix-transpose.json"),
  "flopscope.numpy.matvec": () => import("./public-api/flopscope-numpy-matvec.json"),
  "flopscope.numpy.max": () => import("./public-api/flopscope-numpy-max.json"),
  "flopscope.numpy.maximum": () => import("./public-api/flopscope-numpy-maximum.json"),
  "flopscope.numpy.may_share_memory": () => import("./public-api/flopscope-numpy-may-share-memory.json"),
  "flopscope.numpy.mean": () => import("./public-api/flopscope-numpy-mean.json"),
  "flopscope.numpy.median": () => import("./public-api/flopscope-numpy-median.json"),
  "flopscope.numpy.meshgrid": () => import("./public-api/flopscope-numpy-meshgrid.json"),
  "flopscope.numpy.min": () => import("./public-api/flopscope-numpy-min.json"),
  "flopscope.numpy.min_scalar_type": () => import("./public-api/flopscope-numpy-min-scalar-type.json"),
  "flopscope.numpy.minimum": () => import("./public-api/flopscope-numpy-minimum.json"),
  "flopscope.numpy.mintypecode": () => import("./public-api/flopscope-numpy-mintypecode.json"),
  "flopscope.numpy.mod": () => import("./public-api/flopscope-numpy-mod.json"),
  "flopscope.numpy.modf": () => import("./public-api/flopscope-numpy-modf.json"),
  "flopscope.numpy.moveaxis": () => import("./public-api/flopscope-numpy-moveaxis.json"),
  "flopscope.numpy.multiply": () => import("./public-api/flopscope-numpy-multiply.json"),
  "flopscope.numpy.nan_to_num": () => import("./public-api/flopscope-numpy-nan-to-num.json"),
  "flopscope.numpy.nanargmax": () => import("./public-api/flopscope-numpy-nanargmax.json"),
  "flopscope.numpy.nanargmin": () => import("./public-api/flopscope-numpy-nanargmin.json"),
  "flopscope.numpy.nancumprod": () => import("./public-api/flopscope-numpy-nancumprod.json"),
  "flopscope.numpy.nancumsum": () => import("./public-api/flopscope-numpy-nancumsum.json"),
  "flopscope.numpy.nanmax": () => import("./public-api/flopscope-numpy-nanmax.json"),
  "flopscope.numpy.nanmean": () => import("./public-api/flopscope-numpy-nanmean.json"),
  "flopscope.numpy.nanmedian": () => import("./public-api/flopscope-numpy-nanmedian.json"),
  "flopscope.numpy.nanmin": () => import("./public-api/flopscope-numpy-nanmin.json"),
  "flopscope.numpy.nanpercentile": () => import("./public-api/flopscope-numpy-nanpercentile.json"),
  "flopscope.numpy.nanprod": () => import("./public-api/flopscope-numpy-nanprod.json"),
  "flopscope.numpy.nanquantile": () => import("./public-api/flopscope-numpy-nanquantile.json"),
  "flopscope.numpy.nanstd": () => import("./public-api/flopscope-numpy-nanstd.json"),
  "flopscope.numpy.nansum": () => import("./public-api/flopscope-numpy-nansum.json"),
  "flopscope.numpy.nanvar": () => import("./public-api/flopscope-numpy-nanvar.json"),
  "flopscope.numpy.ndim": () => import("./public-api/flopscope-numpy-ndim.json"),
  "flopscope.numpy.negative": () => import("./public-api/flopscope-numpy-negative.json"),
  "flopscope.numpy.nextafter": () => import("./public-api/flopscope-numpy-nextafter.json"),
  "flopscope.numpy.nonzero": () => import("./public-api/flopscope-numpy-nonzero.json"),
  "flopscope.numpy.not_equal": () => import("./public-api/flopscope-numpy-not-equal.json"),
  "flopscope.numpy.ones": () => import("./public-api/flopscope-numpy-ones.json"),
  "flopscope.numpy.ones_like": () => import("./public-api/flopscope-numpy-ones-like.json"),
  "flopscope.numpy.outer": () => import("./public-api/flopscope-numpy-outer.json"),
  "flopscope.numpy.packbits": () => import("./public-api/flopscope-numpy-packbits.json"),
  "flopscope.numpy.pad": () => import("./public-api/flopscope-numpy-pad.json"),
  "flopscope.numpy.partition": () => import("./public-api/flopscope-numpy-partition.json"),
  "flopscope.numpy.percentile": () => import("./public-api/flopscope-numpy-percentile.json"),
  "flopscope.numpy.permute_dims": () => import("./public-api/flopscope-numpy-permute-dims.json"),
  "flopscope.numpy.piecewise": () => import("./public-api/flopscope-numpy-piecewise.json"),
  "flopscope.numpy.place": () => import("./public-api/flopscope-numpy-place.json"),
  "flopscope.numpy.poly": () => import("./public-api/flopscope-numpy-poly.json"),
  "flopscope.numpy.polyadd": () => import("./public-api/flopscope-numpy-polyadd.json"),
  "flopscope.numpy.polyder": () => import("./public-api/flopscope-numpy-polyder.json"),
  "flopscope.numpy.polydiv": () => import("./public-api/flopscope-numpy-polydiv.json"),
  "flopscope.numpy.polyfit": () => import("./public-api/flopscope-numpy-polyfit.json"),
  "flopscope.numpy.polyint": () => import("./public-api/flopscope-numpy-polyint.json"),
  "flopscope.numpy.polymul": () => import("./public-api/flopscope-numpy-polymul.json"),
  "flopscope.numpy.polysub": () => import("./public-api/flopscope-numpy-polysub.json"),
  "flopscope.numpy.polyval": () => import("./public-api/flopscope-numpy-polyval.json"),
  "flopscope.numpy.positive": () => import("./public-api/flopscope-numpy-positive.json"),
  "flopscope.numpy.power": () => import("./public-api/flopscope-numpy-power.json"),
  "flopscope.numpy.prod": () => import("./public-api/flopscope-numpy-prod.json"),
  "flopscope.numpy.promote_types": () => import("./public-api/flopscope-numpy-promote-types.json"),
  "flopscope.numpy.ptp": () => import("./public-api/flopscope-numpy-ptp.json"),
  "flopscope.numpy.put": () => import("./public-api/flopscope-numpy-put.json"),
  "flopscope.numpy.put_along_axis": () => import("./public-api/flopscope-numpy-put-along-axis.json"),
  "flopscope.numpy.putmask": () => import("./public-api/flopscope-numpy-putmask.json"),
  "flopscope.numpy.quantile": () => import("./public-api/flopscope-numpy-quantile.json"),
  "flopscope.numpy.radians": () => import("./public-api/flopscope-numpy-radians.json"),
  "flopscope.numpy.random.RandomState": () => import("./public-api/flopscope-numpy-random-random-state.json"),
  "flopscope.numpy.random.SeedSequence": () => import("./public-api/flopscope-numpy-random-seed-sequence.json"),
  "flopscope.numpy.random.beta": () => import("./public-api/flopscope-numpy-random-beta.json"),
  "flopscope.numpy.random.binomial": () => import("./public-api/flopscope-numpy-random-binomial.json"),
  "flopscope.numpy.random.bytes": () => import("./public-api/flopscope-numpy-random-bytes.json"),
  "flopscope.numpy.random.chisquare": () => import("./public-api/flopscope-numpy-random-chisquare.json"),
  "flopscope.numpy.random.choice": () => import("./public-api/flopscope-numpy-random-choice.json"),
  "flopscope.numpy.random.default_rng": () => import("./public-api/flopscope-numpy-random-default-rng.json"),
  "flopscope.numpy.random.dirichlet": () => import("./public-api/flopscope-numpy-random-dirichlet.json"),
  "flopscope.numpy.random.exponential": () => import("./public-api/flopscope-numpy-random-exponential.json"),
  "flopscope.numpy.random.f": () => import("./public-api/flopscope-numpy-random-f.json"),
  "flopscope.numpy.random.gamma": () => import("./public-api/flopscope-numpy-random-gamma.json"),
  "flopscope.numpy.random.geometric": () => import("./public-api/flopscope-numpy-random-geometric.json"),
  "flopscope.numpy.random.get_state": () => import("./public-api/flopscope-numpy-random-get-state.json"),
  "flopscope.numpy.random.gumbel": () => import("./public-api/flopscope-numpy-random-gumbel.json"),
  "flopscope.numpy.random.hypergeometric": () => import("./public-api/flopscope-numpy-random-hypergeometric.json"),
  "flopscope.numpy.random.laplace": () => import("./public-api/flopscope-numpy-random-laplace.json"),
  "flopscope.numpy.random.logistic": () => import("./public-api/flopscope-numpy-random-logistic.json"),
  "flopscope.numpy.random.lognormal": () => import("./public-api/flopscope-numpy-random-lognormal.json"),
  "flopscope.numpy.random.logseries": () => import("./public-api/flopscope-numpy-random-logseries.json"),
  "flopscope.numpy.random.multinomial": () => import("./public-api/flopscope-numpy-random-multinomial.json"),
  "flopscope.numpy.random.multivariate_normal": () => import("./public-api/flopscope-numpy-random-multivariate-normal.json"),
  "flopscope.numpy.random.negative_binomial": () => import("./public-api/flopscope-numpy-random-negative-binomial.json"),
  "flopscope.numpy.random.noncentral_chisquare": () => import("./public-api/flopscope-numpy-random-noncentral-chisquare.json"),
  "flopscope.numpy.random.noncentral_f": () => import("./public-api/flopscope-numpy-random-noncentral-f.json"),
  "flopscope.numpy.random.normal": () => import("./public-api/flopscope-numpy-random-normal.json"),
  "flopscope.numpy.random.pareto": () => import("./public-api/flopscope-numpy-random-pareto.json"),
  "flopscope.numpy.random.permutation": () => import("./public-api/flopscope-numpy-random-permutation.json"),
  "flopscope.numpy.random.poisson": () => import("./public-api/flopscope-numpy-random-poisson.json"),
  "flopscope.numpy.random.power": () => import("./public-api/flopscope-numpy-random-power.json"),
  "flopscope.numpy.random.rand": () => import("./public-api/flopscope-numpy-random-rand.json"),
  "flopscope.numpy.random.randint": () => import("./public-api/flopscope-numpy-random-randint.json"),
  "flopscope.numpy.random.randn": () => import("./public-api/flopscope-numpy-random-randn.json"),
  "flopscope.numpy.random.random": () => import("./public-api/flopscope-numpy-random-random.json"),
  "flopscope.numpy.random.random_integers": () => import("./public-api/flopscope-numpy-random-random-integers.json"),
  "flopscope.numpy.random.random_sample": () => import("./public-api/flopscope-numpy-random-random-sample.json"),
  "flopscope.numpy.random.ranf": () => import("./public-api/flopscope-numpy-random-ranf.json"),
  "flopscope.numpy.random.rayleigh": () => import("./public-api/flopscope-numpy-random-rayleigh.json"),
  "flopscope.numpy.random.sample": () => import("./public-api/flopscope-numpy-random-sample.json"),
  "flopscope.numpy.random.seed": () => import("./public-api/flopscope-numpy-random-seed.json"),
  "flopscope.numpy.random.set_state": () => import("./public-api/flopscope-numpy-random-set-state.json"),
  "flopscope.numpy.random.shuffle": () => import("./public-api/flopscope-numpy-random-shuffle.json"),
  "flopscope.numpy.random.standard_cauchy": () => import("./public-api/flopscope-numpy-random-standard-cauchy.json"),
  "flopscope.numpy.random.standard_exponential": () => import("./public-api/flopscope-numpy-random-standard-exponential.json"),
  "flopscope.numpy.random.standard_gamma": () => import("./public-api/flopscope-numpy-random-standard-gamma.json"),
  "flopscope.numpy.random.standard_normal": () => import("./public-api/flopscope-numpy-random-standard-normal.json"),
  "flopscope.numpy.random.standard_t": () => import("./public-api/flopscope-numpy-random-standard-t.json"),
  "flopscope.numpy.random.symmetric": () => import("./public-api/flopscope-numpy-random-symmetric.json"),
  "flopscope.numpy.random.triangular": () => import("./public-api/flopscope-numpy-random-triangular.json"),
  "flopscope.numpy.random.uniform": () => import("./public-api/flopscope-numpy-random-uniform.json"),
  "flopscope.numpy.random.vonmises": () => import("./public-api/flopscope-numpy-random-vonmises.json"),
  "flopscope.numpy.random.wald": () => import("./public-api/flopscope-numpy-random-wald.json"),
  "flopscope.numpy.random.weibull": () => import("./public-api/flopscope-numpy-random-weibull.json"),
  "flopscope.numpy.random.zipf": () => import("./public-api/flopscope-numpy-random-zipf.json"),
  "flopscope.numpy.ravel": () => import("./public-api/flopscope-numpy-ravel.json"),
  "flopscope.numpy.ravel_multi_index": () => import("./public-api/flopscope-numpy-ravel-multi-index.json"),
  "flopscope.numpy.real": () => import("./public-api/flopscope-numpy-real.json"),
  "flopscope.numpy.real_if_close": () => import("./public-api/flopscope-numpy-real-if-close.json"),
  "flopscope.numpy.reciprocal": () => import("./public-api/flopscope-numpy-reciprocal.json"),
  "flopscope.numpy.remainder": () => import("./public-api/flopscope-numpy-remainder.json"),
  "flopscope.numpy.repeat": () => import("./public-api/flopscope-numpy-repeat.json"),
  "flopscope.numpy.require": () => import("./public-api/flopscope-numpy-require.json"),
  "flopscope.numpy.reshape": () => import("./public-api/flopscope-numpy-reshape.json"),
  "flopscope.numpy.resize": () => import("./public-api/flopscope-numpy-resize.json"),
  "flopscope.numpy.result_type": () => import("./public-api/flopscope-numpy-result-type.json"),
  "flopscope.numpy.right_shift": () => import("./public-api/flopscope-numpy-right-shift.json"),
  "flopscope.numpy.rint": () => import("./public-api/flopscope-numpy-rint.json"),
  "flopscope.numpy.roll": () => import("./public-api/flopscope-numpy-roll.json"),
  "flopscope.numpy.rollaxis": () => import("./public-api/flopscope-numpy-rollaxis.json"),
  "flopscope.numpy.roots": () => import("./public-api/flopscope-numpy-roots.json"),
  "flopscope.numpy.rot90": () => import("./public-api/flopscope-numpy-rot90.json"),
  "flopscope.numpy.row_stack": () => import("./public-api/flopscope-numpy-row-stack.json"),
  "flopscope.numpy.searchsorted": () => import("./public-api/flopscope-numpy-searchsorted.json"),
  "flopscope.numpy.select": () => import("./public-api/flopscope-numpy-select.json"),
  "flopscope.numpy.setdiff1d": () => import("./public-api/flopscope-numpy-setdiff1d.json"),
  "flopscope.numpy.setxor1d": () => import("./public-api/flopscope-numpy-setxor1d.json"),
  "flopscope.numpy.shape": () => import("./public-api/flopscope-numpy-shape.json"),
  "flopscope.numpy.shares_memory": () => import("./public-api/flopscope-numpy-shares-memory.json"),
  "flopscope.numpy.sign": () => import("./public-api/flopscope-numpy-sign.json"),
  "flopscope.numpy.signbit": () => import("./public-api/flopscope-numpy-signbit.json"),
  "flopscope.numpy.sin": () => import("./public-api/flopscope-numpy-sin.json"),
  "flopscope.numpy.sinc": () => import("./public-api/flopscope-numpy-sinc.json"),
  "flopscope.numpy.sinh": () => import("./public-api/flopscope-numpy-sinh.json"),
  "flopscope.numpy.size": () => import("./public-api/flopscope-numpy-size.json"),
  "flopscope.numpy.sort": () => import("./public-api/flopscope-numpy-sort.json"),
  "flopscope.numpy.sort_complex": () => import("./public-api/flopscope-numpy-sort-complex.json"),
  "flopscope.numpy.spacing": () => import("./public-api/flopscope-numpy-spacing.json"),
  "flopscope.numpy.split": () => import("./public-api/flopscope-numpy-split.json"),
  "flopscope.numpy.sqrt": () => import("./public-api/flopscope-numpy-sqrt.json"),
  "flopscope.numpy.square": () => import("./public-api/flopscope-numpy-square.json"),
  "flopscope.numpy.squeeze": () => import("./public-api/flopscope-numpy-squeeze.json"),
  "flopscope.numpy.stack": () => import("./public-api/flopscope-numpy-stack.json"),
  "flopscope.numpy.std": () => import("./public-api/flopscope-numpy-std.json"),
  "flopscope.numpy.subtract": () => import("./public-api/flopscope-numpy-subtract.json"),
  "flopscope.numpy.sum": () => import("./public-api/flopscope-numpy-sum.json"),
  "flopscope.numpy.swapaxes": () => import("./public-api/flopscope-numpy-swapaxes.json"),
  "flopscope.numpy.take": () => import("./public-api/flopscope-numpy-take.json"),
  "flopscope.numpy.take_along_axis": () => import("./public-api/flopscope-numpy-take-along-axis.json"),
  "flopscope.numpy.tan": () => import("./public-api/flopscope-numpy-tan.json"),
  "flopscope.numpy.tanh": () => import("./public-api/flopscope-numpy-tanh.json"),
  "flopscope.numpy.tensordot": () => import("./public-api/flopscope-numpy-tensordot.json"),
  "flopscope.numpy.tile": () => import("./public-api/flopscope-numpy-tile.json"),
  "flopscope.numpy.trace": () => import("./public-api/flopscope-numpy-trace.json"),
  "flopscope.numpy.transpose": () => import("./public-api/flopscope-numpy-transpose.json"),
  "flopscope.numpy.trapezoid": () => import("./public-api/flopscope-numpy-trapezoid.json"),
  "flopscope.numpy.tri": () => import("./public-api/flopscope-numpy-tri.json"),
  "flopscope.numpy.tril": () => import("./public-api/flopscope-numpy-tril.json"),
  "flopscope.numpy.tril_indices": () => import("./public-api/flopscope-numpy-tril-indices.json"),
  "flopscope.numpy.tril_indices_from": () => import("./public-api/flopscope-numpy-tril-indices-from.json"),
  "flopscope.numpy.trim_zeros": () => import("./public-api/flopscope-numpy-trim-zeros.json"),
  "flopscope.numpy.triu": () => import("./public-api/flopscope-numpy-triu.json"),
  "flopscope.numpy.triu_indices": () => import("./public-api/flopscope-numpy-triu-indices.json"),
  "flopscope.numpy.triu_indices_from": () => import("./public-api/flopscope-numpy-triu-indices-from.json"),
  "flopscope.numpy.true_divide": () => import("./public-api/flopscope-numpy-true-divide.json"),
  "flopscope.numpy.trunc": () => import("./public-api/flopscope-numpy-trunc.json"),
  "flopscope.numpy.typename": () => import("./public-api/flopscope-numpy-typename.json"),
  "flopscope.numpy.union1d": () => import("./public-api/flopscope-numpy-union1d.json"),
  "flopscope.numpy.unique": () => import("./public-api/flopscope-numpy-unique.json"),
  "flopscope.numpy.unique_all": () => import("./public-api/flopscope-numpy-unique-all.json"),
  "flopscope.numpy.unique_counts": () => import("./public-api/flopscope-numpy-unique-counts.json"),
  "flopscope.numpy.unique_inverse": () => import("./public-api/flopscope-numpy-unique-inverse.json"),
  "flopscope.numpy.unique_values": () => import("./public-api/flopscope-numpy-unique-values.json"),
  "flopscope.numpy.unpackbits": () => import("./public-api/flopscope-numpy-unpackbits.json"),
  "flopscope.numpy.unravel_index": () => import("./public-api/flopscope-numpy-unravel-index.json"),
  "flopscope.numpy.unstack": () => import("./public-api/flopscope-numpy-unstack.json"),
  "flopscope.numpy.unwrap": () => import("./public-api/flopscope-numpy-unwrap.json"),
  "flopscope.numpy.vander": () => import("./public-api/flopscope-numpy-vander.json"),
  "flopscope.numpy.var": () => import("./public-api/flopscope-numpy-var.json"),
  "flopscope.numpy.vdot": () => import("./public-api/flopscope-numpy-vdot.json"),
  "flopscope.numpy.vecdot": () => import("./public-api/flopscope-numpy-vecdot.json"),
  "flopscope.numpy.vecmat": () => import("./public-api/flopscope-numpy-vecmat.json"),
  "flopscope.numpy.vsplit": () => import("./public-api/flopscope-numpy-vsplit.json"),
  "flopscope.numpy.vstack": () => import("./public-api/flopscope-numpy-vstack.json"),
  "flopscope.numpy.where": () => import("./public-api/flopscope-numpy-where.json"),
  "flopscope.numpy.zeros": () => import("./public-api/flopscope-numpy-zeros.json"),
  "flopscope.numpy.zeros_like": () => import("./public-api/flopscope-numpy-zeros-like.json"),
  "flopscope.stats.cauchy": () => import("./public-api/flopscope-stats-cauchy.json"),
  "flopscope.stats.cauchy.cdf": () => import("./public-api/flopscope-stats-cauchy-cdf.json"),
  "flopscope.stats.cauchy.pdf": () => import("./public-api/flopscope-stats-cauchy-pdf.json"),
  "flopscope.stats.cauchy.ppf": () => import("./public-api/flopscope-stats-cauchy-ppf.json"),
  "flopscope.stats.expon": () => import("./public-api/flopscope-stats-expon.json"),
  "flopscope.stats.expon.cdf": () => import("./public-api/flopscope-stats-expon-cdf.json"),
  "flopscope.stats.expon.pdf": () => import("./public-api/flopscope-stats-expon-pdf.json"),
  "flopscope.stats.expon.ppf": () => import("./public-api/flopscope-stats-expon-ppf.json"),
  "flopscope.stats.laplace": () => import("./public-api/flopscope-stats-laplace.json"),
  "flopscope.stats.laplace.cdf": () => import("./public-api/flopscope-stats-laplace-cdf.json"),
  "flopscope.stats.laplace.pdf": () => import("./public-api/flopscope-stats-laplace-pdf.json"),
  "flopscope.stats.laplace.ppf": () => import("./public-api/flopscope-stats-laplace-ppf.json"),
  "flopscope.stats.logistic": () => import("./public-api/flopscope-stats-logistic.json"),
  "flopscope.stats.logistic.cdf": () => import("./public-api/flopscope-stats-logistic-cdf.json"),
  "flopscope.stats.logistic.pdf": () => import("./public-api/flopscope-stats-logistic-pdf.json"),
  "flopscope.stats.logistic.ppf": () => import("./public-api/flopscope-stats-logistic-ppf.json"),
  "flopscope.stats.lognorm": () => import("./public-api/flopscope-stats-lognorm.json"),
  "flopscope.stats.lognorm.cdf": () => import("./public-api/flopscope-stats-lognorm-cdf.json"),
  "flopscope.stats.lognorm.pdf": () => import("./public-api/flopscope-stats-lognorm-pdf.json"),
  "flopscope.stats.lognorm.ppf": () => import("./public-api/flopscope-stats-lognorm-ppf.json"),
  "flopscope.stats.norm": () => import("./public-api/flopscope-stats-norm.json"),
  "flopscope.stats.norm.cdf": () => import("./public-api/flopscope-stats-norm-cdf.json"),
  "flopscope.stats.norm.pdf": () => import("./public-api/flopscope-stats-norm-pdf.json"),
  "flopscope.stats.norm.ppf": () => import("./public-api/flopscope-stats-norm-ppf.json"),
  "flopscope.stats.truncnorm": () => import("./public-api/flopscope-stats-truncnorm.json"),
  "flopscope.stats.truncnorm.cdf": () => import("./public-api/flopscope-stats-truncnorm-cdf.json"),
  "flopscope.stats.truncnorm.pdf": () => import("./public-api/flopscope-stats-truncnorm-pdf.json"),
  "flopscope.stats.truncnorm.ppf": () => import("./public-api/flopscope-stats-truncnorm-ppf.json"),
  "flopscope.stats.uniform": () => import("./public-api/flopscope-stats-uniform.json"),
  "flopscope.stats.uniform.cdf": () => import("./public-api/flopscope-stats-uniform-cdf.json"),
  "flopscope.stats.uniform.pdf": () => import("./public-api/flopscope-stats-uniform-pdf.json"),
  "flopscope.stats.uniform.ppf": () => import("./public-api/flopscope-stats-uniform-ppf.json"),
  "flopscope.symmetrize": () => import("./public-api/flopscope-symmetrize.json"),
};

export const publicApiLeafImportPaths = [
  "flops.stats.cauchy.cdf",
  "flops.stats.cauchy.pdf",
  "flops.stats.cauchy.ppf",
  "flops.stats.expon.cdf",
  "flops.stats.expon.pdf",
  "flops.stats.expon.ppf",
  "flops.stats.laplace.cdf",
  "flops.stats.laplace.pdf",
  "flops.stats.laplace.ppf",
  "flops.stats.logistic.cdf",
  "flops.stats.logistic.pdf",
  "flops.stats.logistic.ppf",
  "flops.stats.lognorm.cdf",
  "flops.stats.lognorm.pdf",
  "flops.stats.lognorm.ppf",
  "flops.stats.norm.cdf",
  "flops.stats.norm.pdf",
  "flops.stats.norm.ppf",
  "flops.stats.truncnorm.cdf",
  "flops.stats.truncnorm.pdf",
  "flops.stats.truncnorm.ppf",
  "flops.stats.uniform.cdf",
  "flops.stats.uniform.pdf",
  "flops.stats.uniform.ppf",
  "flopscope.BudgetContext",
  "flopscope.FlopscopeArray",
  "flopscope.PathInfo",
  "flopscope.StepInfo",
  "flopscope.SymmetricTensor",
  "flopscope.accounting.bartlett_cost",
  "flopscope.accounting.blackman_cost",
  "flopscope.accounting.cholesky_cost",
  "flopscope.accounting.cond_cost",
  "flopscope.accounting.det_cost",
  "flopscope.accounting.eig_cost",
  "flopscope.accounting.eigh_cost",
  "flopscope.accounting.eigvals_cost",
  "flopscope.accounting.eigvalsh_cost",
  "flopscope.accounting.einsum_cost",
  "flopscope.accounting.fft_cost",
  "flopscope.accounting.fftn_cost",
  "flopscope.accounting.hamming_cost",
  "flopscope.accounting.hanning_cost",
  "flopscope.accounting.hfft_cost",
  "flopscope.accounting.inv_cost",
  "flopscope.accounting.kaiser_cost",
  "flopscope.accounting.lstsq_cost",
  "flopscope.accounting.matrix_norm_cost",
  "flopscope.accounting.matrix_power_cost",
  "flopscope.accounting.matrix_rank_cost",
  "flopscope.accounting.multi_dot_cost",
  "flopscope.accounting.norm_cost",
  "flopscope.accounting.pinv_cost",
  "flopscope.accounting.pointwise_cost",
  "flopscope.accounting.poly_cost",
  "flopscope.accounting.polyadd_cost",
  "flopscope.accounting.polyder_cost",
  "flopscope.accounting.polydiv_cost",
  "flopscope.accounting.polyfit_cost",
  "flopscope.accounting.polyint_cost",
  "flopscope.accounting.polymul_cost",
  "flopscope.accounting.polysub_cost",
  "flopscope.accounting.polyval_cost",
  "flopscope.accounting.qr_cost",
  "flopscope.accounting.reduction_cost",
  "flopscope.accounting.rfft_cost",
  "flopscope.accounting.rfftn_cost",
  "flopscope.accounting.roots_cost",
  "flopscope.accounting.slogdet_cost",
  "flopscope.accounting.solve_cost",
  "flopscope.accounting.svd_cost",
  "flopscope.accounting.svdvals_cost",
  "flopscope.accounting.tensorinv_cost",
  "flopscope.accounting.tensorsolve_cost",
  "flopscope.accounting.trace_cost",
  "flopscope.accounting.unwrap_cost",
  "flopscope.accounting.vector_norm_cost",
  "flopscope.as_symmetric",
  "flopscope.budget",
  "flopscope.budget_live",
  "flopscope.budget_reset",
  "flopscope.budget_summary",
  "flopscope.budget_summary_dict",
  "flopscope.configure",
  "flopscope.is_symmetric",
  "flopscope.namespace",
  "flopscope.numpy.absolute",
  "flopscope.numpy.add",
  "flopscope.numpy.all",
  "flopscope.numpy.allclose",
  "flopscope.numpy.angle",
  "flopscope.numpy.any",
  "flopscope.numpy.append",
  "flopscope.numpy.apply_along_axis",
  "flopscope.numpy.apply_over_axes",
  "flopscope.numpy.arange",
  "flopscope.numpy.arccos",
  "flopscope.numpy.arccosh",
  "flopscope.numpy.arcsin",
  "flopscope.numpy.arcsinh",
  "flopscope.numpy.arctan",
  "flopscope.numpy.arctan2",
  "flopscope.numpy.arctanh",
  "flopscope.numpy.argmax",
  "flopscope.numpy.argmin",
  "flopscope.numpy.argpartition",
  "flopscope.numpy.argsort",
  "flopscope.numpy.argwhere",
  "flopscope.numpy.array",
  "flopscope.numpy.array_equal",
  "flopscope.numpy.array_equiv",
  "flopscope.numpy.array_split",
  "flopscope.numpy.asarray",
  "flopscope.numpy.asarray_chkfinite",
  "flopscope.numpy.astype",
  "flopscope.numpy.atleast_1d",
  "flopscope.numpy.atleast_2d",
  "flopscope.numpy.atleast_3d",
  "flopscope.numpy.average",
  "flopscope.numpy.bartlett",
  "flopscope.numpy.bincount",
  "flopscope.numpy.bitwise_and",
  "flopscope.numpy.bitwise_count",
  "flopscope.numpy.bitwise_left_shift",
  "flopscope.numpy.bitwise_not",
  "flopscope.numpy.bitwise_or",
  "flopscope.numpy.bitwise_right_shift",
  "flopscope.numpy.bitwise_xor",
  "flopscope.numpy.blackman",
  "flopscope.numpy.block",
  "flopscope.numpy.bmat",
  "flopscope.numpy.broadcast_arrays",
  "flopscope.numpy.broadcast_shapes",
  "flopscope.numpy.broadcast_to",
  "flopscope.numpy.can_cast",
  "flopscope.numpy.cbrt",
  "flopscope.numpy.ceil",
  "flopscope.numpy.choose",
  "flopscope.numpy.clip",
  "flopscope.numpy.column_stack",
  "flopscope.numpy.common_type",
  "flopscope.numpy.compress",
  "flopscope.numpy.concatenate",
  "flopscope.numpy.conj",
  "flopscope.numpy.conjugate",
  "flopscope.numpy.convolve",
  "flopscope.numpy.copy",
  "flopscope.numpy.copysign",
  "flopscope.numpy.copyto",
  "flopscope.numpy.corrcoef",
  "flopscope.numpy.correlate",
  "flopscope.numpy.cos",
  "flopscope.numpy.cosh",
  "flopscope.numpy.count_nonzero",
  "flopscope.numpy.cov",
  "flopscope.numpy.cross",
  "flopscope.numpy.cumprod",
  "flopscope.numpy.cumsum",
  "flopscope.numpy.cumulative_prod",
  "flopscope.numpy.cumulative_sum",
  "flopscope.numpy.degrees",
  "flopscope.numpy.delete",
  "flopscope.numpy.diag",
  "flopscope.numpy.diag_indices",
  "flopscope.numpy.diag_indices_from",
  "flopscope.numpy.diagflat",
  "flopscope.numpy.diagonal",
  "flopscope.numpy.diff",
  "flopscope.numpy.digitize",
  "flopscope.numpy.divide",
  "flopscope.numpy.dot",
  "flopscope.numpy.dsplit",
  "flopscope.numpy.dstack",
  "flopscope.numpy.ediff1d",
  "flopscope.numpy.einsum",
  "flopscope.numpy.einsum_path",
  "flopscope.numpy.empty",
  "flopscope.numpy.empty_like",
  "flopscope.numpy.equal",
  "flopscope.numpy.exp",
  "flopscope.numpy.exp2",
  "flopscope.numpy.expand_dims",
  "flopscope.numpy.expm1",
  "flopscope.numpy.extract",
  "flopscope.numpy.eye",
  "flopscope.numpy.fabs",
  "flopscope.numpy.fft.fft",
  "flopscope.numpy.fft.fft2",
  "flopscope.numpy.fft.fftfreq",
  "flopscope.numpy.fft.fftn",
  "flopscope.numpy.fft.fftshift",
  "flopscope.numpy.fft.hfft",
  "flopscope.numpy.fft.ifft",
  "flopscope.numpy.fft.ifft2",
  "flopscope.numpy.fft.ifftn",
  "flopscope.numpy.fft.ifftshift",
  "flopscope.numpy.fft.ihfft",
  "flopscope.numpy.fft.irfft",
  "flopscope.numpy.fft.irfft2",
  "flopscope.numpy.fft.irfftn",
  "flopscope.numpy.fft.rfft",
  "flopscope.numpy.fft.rfft2",
  "flopscope.numpy.fft.rfftfreq",
  "flopscope.numpy.fft.rfftn",
  "flopscope.numpy.fill_diagonal",
  "flopscope.numpy.flatnonzero",
  "flopscope.numpy.flip",
  "flopscope.numpy.fliplr",
  "flopscope.numpy.flipud",
  "flopscope.numpy.float_power",
  "flopscope.numpy.floor",
  "flopscope.numpy.floor_divide",
  "flopscope.numpy.fmax",
  "flopscope.numpy.fmin",
  "flopscope.numpy.fmod",
  "flopscope.numpy.frexp",
  "flopscope.numpy.from_dlpack",
  "flopscope.numpy.frombuffer",
  "flopscope.numpy.fromfunction",
  "flopscope.numpy.fromiter",
  "flopscope.numpy.full",
  "flopscope.numpy.full_like",
  "flopscope.numpy.gcd",
  "flopscope.numpy.geomspace",
  "flopscope.numpy.gradient",
  "flopscope.numpy.greater",
  "flopscope.numpy.greater_equal",
  "flopscope.numpy.hamming",
  "flopscope.numpy.hanning",
  "flopscope.numpy.heaviside",
  "flopscope.numpy.histogram",
  "flopscope.numpy.histogram2d",
  "flopscope.numpy.histogram_bin_edges",
  "flopscope.numpy.histogramdd",
  "flopscope.numpy.hsplit",
  "flopscope.numpy.hstack",
  "flopscope.numpy.hypot",
  "flopscope.numpy.i0",
  "flopscope.numpy.identity",
  "flopscope.numpy.imag",
  "flopscope.numpy.in1d",
  "flopscope.numpy.indices",
  "flopscope.numpy.inner",
  "flopscope.numpy.insert",
  "flopscope.numpy.interp",
  "flopscope.numpy.intersect1d",
  "flopscope.numpy.invert",
  "flopscope.numpy.isclose",
  "flopscope.numpy.iscomplex",
  "flopscope.numpy.iscomplexobj",
  "flopscope.numpy.isdtype",
  "flopscope.numpy.isfinite",
  "flopscope.numpy.isfortran",
  "flopscope.numpy.isin",
  "flopscope.numpy.isinf",
  "flopscope.numpy.isnan",
  "flopscope.numpy.isneginf",
  "flopscope.numpy.isposinf",
  "flopscope.numpy.isreal",
  "flopscope.numpy.isrealobj",
  "flopscope.numpy.isscalar",
  "flopscope.numpy.issubdtype",
  "flopscope.numpy.iterable",
  "flopscope.numpy.ix_",
  "flopscope.numpy.kaiser",
  "flopscope.numpy.kron",
  "flopscope.numpy.lcm",
  "flopscope.numpy.ldexp",
  "flopscope.numpy.left_shift",
  "flopscope.numpy.less",
  "flopscope.numpy.less_equal",
  "flopscope.numpy.lexsort",
  "flopscope.numpy.linalg.cholesky",
  "flopscope.numpy.linalg.cond",
  "flopscope.numpy.linalg.cross",
  "flopscope.numpy.linalg.det",
  "flopscope.numpy.linalg.diagonal",
  "flopscope.numpy.linalg.eig",
  "flopscope.numpy.linalg.eigh",
  "flopscope.numpy.linalg.eigvals",
  "flopscope.numpy.linalg.eigvalsh",
  "flopscope.numpy.linalg.inv",
  "flopscope.numpy.linalg.lstsq",
  "flopscope.numpy.linalg.matmul",
  "flopscope.numpy.linalg.matrix_norm",
  "flopscope.numpy.linalg.matrix_power",
  "flopscope.numpy.linalg.matrix_rank",
  "flopscope.numpy.linalg.matrix_transpose",
  "flopscope.numpy.linalg.multi_dot",
  "flopscope.numpy.linalg.norm",
  "flopscope.numpy.linalg.outer",
  "flopscope.numpy.linalg.pinv",
  "flopscope.numpy.linalg.qr",
  "flopscope.numpy.linalg.slogdet",
  "flopscope.numpy.linalg.solve",
  "flopscope.numpy.linalg.svd",
  "flopscope.numpy.linalg.svdvals",
  "flopscope.numpy.linalg.tensordot",
  "flopscope.numpy.linalg.tensorinv",
  "flopscope.numpy.linalg.tensorsolve",
  "flopscope.numpy.linalg.trace",
  "flopscope.numpy.linalg.vecdot",
  "flopscope.numpy.linalg.vector_norm",
  "flopscope.numpy.linspace",
  "flopscope.numpy.log",
  "flopscope.numpy.log10",
  "flopscope.numpy.log1p",
  "flopscope.numpy.log2",
  "flopscope.numpy.logaddexp",
  "flopscope.numpy.logaddexp2",
  "flopscope.numpy.logical_and",
  "flopscope.numpy.logical_not",
  "flopscope.numpy.logical_or",
  "flopscope.numpy.logical_xor",
  "flopscope.numpy.logspace",
  "flopscope.numpy.mask_indices",
  "flopscope.numpy.matmul",
  "flopscope.numpy.matrix_transpose",
  "flopscope.numpy.matvec",
  "flopscope.numpy.max",
  "flopscope.numpy.maximum",
  "flopscope.numpy.may_share_memory",
  "flopscope.numpy.mean",
  "flopscope.numpy.median",
  "flopscope.numpy.meshgrid",
  "flopscope.numpy.min",
  "flopscope.numpy.min_scalar_type",
  "flopscope.numpy.minimum",
  "flopscope.numpy.mintypecode",
  "flopscope.numpy.mod",
  "flopscope.numpy.modf",
  "flopscope.numpy.moveaxis",
  "flopscope.numpy.multiply",
  "flopscope.numpy.nan_to_num",
  "flopscope.numpy.nanargmax",
  "flopscope.numpy.nanargmin",
  "flopscope.numpy.nancumprod",
  "flopscope.numpy.nancumsum",
  "flopscope.numpy.nanmax",
  "flopscope.numpy.nanmean",
  "flopscope.numpy.nanmedian",
  "flopscope.numpy.nanmin",
  "flopscope.numpy.nanpercentile",
  "flopscope.numpy.nanprod",
  "flopscope.numpy.nanquantile",
  "flopscope.numpy.nanstd",
  "flopscope.numpy.nansum",
  "flopscope.numpy.nanvar",
  "flopscope.numpy.ndim",
  "flopscope.numpy.negative",
  "flopscope.numpy.nextafter",
  "flopscope.numpy.nonzero",
  "flopscope.numpy.not_equal",
  "flopscope.numpy.ones",
  "flopscope.numpy.ones_like",
  "flopscope.numpy.outer",
  "flopscope.numpy.packbits",
  "flopscope.numpy.pad",
  "flopscope.numpy.partition",
  "flopscope.numpy.percentile",
  "flopscope.numpy.permute_dims",
  "flopscope.numpy.piecewise",
  "flopscope.numpy.place",
  "flopscope.numpy.poly",
  "flopscope.numpy.polyadd",
  "flopscope.numpy.polyder",
  "flopscope.numpy.polydiv",
  "flopscope.numpy.polyfit",
  "flopscope.numpy.polyint",
  "flopscope.numpy.polymul",
  "flopscope.numpy.polysub",
  "flopscope.numpy.polyval",
  "flopscope.numpy.positive",
  "flopscope.numpy.power",
  "flopscope.numpy.prod",
  "flopscope.numpy.promote_types",
  "flopscope.numpy.ptp",
  "flopscope.numpy.put",
  "flopscope.numpy.put_along_axis",
  "flopscope.numpy.putmask",
  "flopscope.numpy.quantile",
  "flopscope.numpy.radians",
  "flopscope.numpy.random.RandomState",
  "flopscope.numpy.random.SeedSequence",
  "flopscope.numpy.random.beta",
  "flopscope.numpy.random.binomial",
  "flopscope.numpy.random.bytes",
  "flopscope.numpy.random.chisquare",
  "flopscope.numpy.random.choice",
  "flopscope.numpy.random.default_rng",
  "flopscope.numpy.random.dirichlet",
  "flopscope.numpy.random.exponential",
  "flopscope.numpy.random.f",
  "flopscope.numpy.random.gamma",
  "flopscope.numpy.random.geometric",
  "flopscope.numpy.random.get_state",
  "flopscope.numpy.random.gumbel",
  "flopscope.numpy.random.hypergeometric",
  "flopscope.numpy.random.laplace",
  "flopscope.numpy.random.logistic",
  "flopscope.numpy.random.lognormal",
  "flopscope.numpy.random.logseries",
  "flopscope.numpy.random.multinomial",
  "flopscope.numpy.random.multivariate_normal",
  "flopscope.numpy.random.negative_binomial",
  "flopscope.numpy.random.noncentral_chisquare",
  "flopscope.numpy.random.noncentral_f",
  "flopscope.numpy.random.normal",
  "flopscope.numpy.random.pareto",
  "flopscope.numpy.random.permutation",
  "flopscope.numpy.random.poisson",
  "flopscope.numpy.random.power",
  "flopscope.numpy.random.rand",
  "flopscope.numpy.random.randint",
  "flopscope.numpy.random.randn",
  "flopscope.numpy.random.random",
  "flopscope.numpy.random.random_integers",
  "flopscope.numpy.random.random_sample",
  "flopscope.numpy.random.ranf",
  "flopscope.numpy.random.rayleigh",
  "flopscope.numpy.random.sample",
  "flopscope.numpy.random.seed",
  "flopscope.numpy.random.set_state",
  "flopscope.numpy.random.shuffle",
  "flopscope.numpy.random.standard_cauchy",
  "flopscope.numpy.random.standard_exponential",
  "flopscope.numpy.random.standard_gamma",
  "flopscope.numpy.random.standard_normal",
  "flopscope.numpy.random.standard_t",
  "flopscope.numpy.random.symmetric",
  "flopscope.numpy.random.triangular",
  "flopscope.numpy.random.uniform",
  "flopscope.numpy.random.vonmises",
  "flopscope.numpy.random.wald",
  "flopscope.numpy.random.weibull",
  "flopscope.numpy.random.zipf",
  "flopscope.numpy.ravel",
  "flopscope.numpy.ravel_multi_index",
  "flopscope.numpy.real",
  "flopscope.numpy.real_if_close",
  "flopscope.numpy.reciprocal",
  "flopscope.numpy.remainder",
  "flopscope.numpy.repeat",
  "flopscope.numpy.require",
  "flopscope.numpy.reshape",
  "flopscope.numpy.resize",
  "flopscope.numpy.result_type",
  "flopscope.numpy.right_shift",
  "flopscope.numpy.rint",
  "flopscope.numpy.roll",
  "flopscope.numpy.rollaxis",
  "flopscope.numpy.roots",
  "flopscope.numpy.rot90",
  "flopscope.numpy.row_stack",
  "flopscope.numpy.searchsorted",
  "flopscope.numpy.select",
  "flopscope.numpy.setdiff1d",
  "flopscope.numpy.setxor1d",
  "flopscope.numpy.shape",
  "flopscope.numpy.shares_memory",
  "flopscope.numpy.sign",
  "flopscope.numpy.signbit",
  "flopscope.numpy.sin",
  "flopscope.numpy.sinc",
  "flopscope.numpy.sinh",
  "flopscope.numpy.size",
  "flopscope.numpy.sort",
  "flopscope.numpy.sort_complex",
  "flopscope.numpy.spacing",
  "flopscope.numpy.split",
  "flopscope.numpy.sqrt",
  "flopscope.numpy.square",
  "flopscope.numpy.squeeze",
  "flopscope.numpy.stack",
  "flopscope.numpy.std",
  "flopscope.numpy.subtract",
  "flopscope.numpy.sum",
  "flopscope.numpy.swapaxes",
  "flopscope.numpy.take",
  "flopscope.numpy.take_along_axis",
  "flopscope.numpy.tan",
  "flopscope.numpy.tanh",
  "flopscope.numpy.tensordot",
  "flopscope.numpy.tile",
  "flopscope.numpy.trace",
  "flopscope.numpy.transpose",
  "flopscope.numpy.trapezoid",
  "flopscope.numpy.tri",
  "flopscope.numpy.tril",
  "flopscope.numpy.tril_indices",
  "flopscope.numpy.tril_indices_from",
  "flopscope.numpy.trim_zeros",
  "flopscope.numpy.triu",
  "flopscope.numpy.triu_indices",
  "flopscope.numpy.triu_indices_from",
  "flopscope.numpy.true_divide",
  "flopscope.numpy.trunc",
  "flopscope.numpy.typename",
  "flopscope.numpy.union1d",
  "flopscope.numpy.unique",
  "flopscope.numpy.unique_all",
  "flopscope.numpy.unique_counts",
  "flopscope.numpy.unique_inverse",
  "flopscope.numpy.unique_values",
  "flopscope.numpy.unpackbits",
  "flopscope.numpy.unravel_index",
  "flopscope.numpy.unstack",
  "flopscope.numpy.unwrap",
  "flopscope.numpy.vander",
  "flopscope.numpy.var",
  "flopscope.numpy.vdot",
  "flopscope.numpy.vecdot",
  "flopscope.numpy.vecmat",
  "flopscope.numpy.vsplit",
  "flopscope.numpy.vstack",
  "flopscope.numpy.where",
  "flopscope.numpy.zeros",
  "flopscope.numpy.zeros_like",
  "flopscope.stats.cauchy",
  "flopscope.stats.cauchy.cdf",
  "flopscope.stats.cauchy.pdf",
  "flopscope.stats.cauchy.ppf",
  "flopscope.stats.expon",
  "flopscope.stats.expon.cdf",
  "flopscope.stats.expon.pdf",
  "flopscope.stats.expon.ppf",
  "flopscope.stats.laplace",
  "flopscope.stats.laplace.cdf",
  "flopscope.stats.laplace.pdf",
  "flopscope.stats.laplace.ppf",
  "flopscope.stats.logistic",
  "flopscope.stats.logistic.cdf",
  "flopscope.stats.logistic.pdf",
  "flopscope.stats.logistic.ppf",
  "flopscope.stats.lognorm",
  "flopscope.stats.lognorm.cdf",
  "flopscope.stats.lognorm.pdf",
  "flopscope.stats.lognorm.ppf",
  "flopscope.stats.norm",
  "flopscope.stats.norm.cdf",
  "flopscope.stats.norm.pdf",
  "flopscope.stats.norm.ppf",
  "flopscope.stats.truncnorm",
  "flopscope.stats.truncnorm.cdf",
  "flopscope.stats.truncnorm.pdf",
  "flopscope.stats.truncnorm.ppf",
  "flopscope.stats.uniform",
  "flopscope.stats.uniform.cdf",
  "flopscope.stats.uniform.pdf",
  "flopscope.stats.uniform.ppf",
  "flopscope.symmetrize",
] as const;
