export const symbolDocImports: Record<string, () => Promise<{ default: unknown }>> = {
  "budget-context": () => import("./symbols/budget-context.json"),
  "cycle": () => import("./symbols/cycle.json"),
  "op-record": () => import("./symbols/op-record.json"),
  "path-info": () => import("./symbols/path-info.json"),
  "permutation": () => import("./symbols/permutation.json"),
  "permutation-group": () => import("./symbols/permutation-group.json"),
  "step-info": () => import("./symbols/step-info.json"),
  "symmetric-tensor": () => import("./symbols/symmetric-tensor.json"),
  "symmetry-info": () => import("./symbols/symmetry-info.json"),
  "as-symmetric": () => import("./symbols/as-symmetric.json"),
  "base-repr": () => import("./symbols/base-repr.json"),
  "binary-repr": () => import("./symbols/binary-repr.json"),
  "broadcast": () => import("./symbols/broadcast.json"),
  "budget": () => import("./symbols/budget.json"),
  "budget-live": () => import("./symbols/budget-live.json"),
  "budget-reset": () => import("./symbols/budget-reset.json"),
  "budget-summary": () => import("./symbols/budget-summary.json"),
  "budget-summary-dict": () => import("./symbols/budget-summary-dict.json"),
  "clear-einsum-cache": () => import("./symbols/clear-einsum-cache.json"),
  "configure": () => import("./symbols/configure.json"),
  "einsum-cache-info": () => import("./symbols/einsum-cache-info.json"),
  "errstate": () => import("./symbols/errstate.json"),
  "finfo": () => import("./symbols/finfo.json"),
  "flops-bartlett-cost": () => import("./symbols/flops-bartlett-cost.json"),
  "flops-blackman-cost": () => import("./symbols/flops-blackman-cost.json"),
  "flops-cholesky-cost": () => import("./symbols/flops-cholesky-cost.json"),
  "flops-cond-cost": () => import("./symbols/flops-cond-cost.json"),
  "flops-det-cost": () => import("./symbols/flops-det-cost.json"),
  "flops-eig-cost": () => import("./symbols/flops-eig-cost.json"),
  "flops-eigh-cost": () => import("./symbols/flops-eigh-cost.json"),
  "flops-eigvals-cost": () => import("./symbols/flops-eigvals-cost.json"),
  "flops-eigvalsh-cost": () => import("./symbols/flops-eigvalsh-cost.json"),
  "flops-einsum-cost": () => import("./symbols/flops-einsum-cost.json"),
  "flops-fft-cost": () => import("./symbols/flops-fft-cost.json"),
  "flops-fftn-cost": () => import("./symbols/flops-fftn-cost.json"),
  "flops-hamming-cost": () => import("./symbols/flops-hamming-cost.json"),
  "flops-hanning-cost": () => import("./symbols/flops-hanning-cost.json"),
  "flops-hfft-cost": () => import("./symbols/flops-hfft-cost.json"),
  "flops-inv-cost": () => import("./symbols/flops-inv-cost.json"),
  "flops-kaiser-cost": () => import("./symbols/flops-kaiser-cost.json"),
  "flops-lstsq-cost": () => import("./symbols/flops-lstsq-cost.json"),
  "flops-matrix-norm-cost": () => import("./symbols/flops-matrix-norm-cost.json"),
  "flops-matrix-power-cost": () => import("./symbols/flops-matrix-power-cost.json"),
  "flops-matrix-rank-cost": () => import("./symbols/flops-matrix-rank-cost.json"),
  "flops-multi-dot-cost": () => import("./symbols/flops-multi-dot-cost.json"),
  "flops-norm-cost": () => import("./symbols/flops-norm-cost.json"),
  "flops-pinv-cost": () => import("./symbols/flops-pinv-cost.json"),
  "flops-pointwise-cost": () => import("./symbols/flops-pointwise-cost.json"),
  "flops-poly-cost": () => import("./symbols/flops-poly-cost.json"),
  "flops-polyadd-cost": () => import("./symbols/flops-polyadd-cost.json"),
  "flops-polyder-cost": () => import("./symbols/flops-polyder-cost.json"),
  "flops-polydiv-cost": () => import("./symbols/flops-polydiv-cost.json"),
  "flops-polyfit-cost": () => import("./symbols/flops-polyfit-cost.json"),
  "flops-polyint-cost": () => import("./symbols/flops-polyint-cost.json"),
  "flops-polymul-cost": () => import("./symbols/flops-polymul-cost.json"),
  "flops-polysub-cost": () => import("./symbols/flops-polysub-cost.json"),
  "flops-polyval-cost": () => import("./symbols/flops-polyval-cost.json"),
  "flops-qr-cost": () => import("./symbols/flops-qr-cost.json"),
  "flops-reduction-cost": () => import("./symbols/flops-reduction-cost.json"),
  "flops-rfft-cost": () => import("./symbols/flops-rfft-cost.json"),
  "flops-rfftn-cost": () => import("./symbols/flops-rfftn-cost.json"),
  "flops-roots-cost": () => import("./symbols/flops-roots-cost.json"),
  "flops-slogdet-cost": () => import("./symbols/flops-slogdet-cost.json"),
  "flops-solve-cost": () => import("./symbols/flops-solve-cost.json"),
  "flops-svd-cost": () => import("./symbols/flops-svd-cost.json"),
  "flops-svdvals-cost": () => import("./symbols/flops-svdvals-cost.json"),
  "flops-tensorinv-cost": () => import("./symbols/flops-tensorinv-cost.json"),
  "flops-tensorsolve-cost": () => import("./symbols/flops-tensorsolve-cost.json"),
  "flops-trace-cost": () => import("./symbols/flops-trace-cost.json"),
  "flops-unwrap-cost": () => import("./symbols/flops-unwrap-cost.json"),
  "flops-vector-norm-cost": () => import("./symbols/flops-vector-norm-cost.json"),
  "fromfile": () => import("./symbols/fromfile.json"),
  "fromregex": () => import("./symbols/fromregex.json"),
  "fromstring": () => import("./symbols/fromstring.json"),
  "get-printoptions": () => import("./symbols/get-printoptions.json"),
  "geterr": () => import("./symbols/geterr.json"),
  "iinfo": () => import("./symbols/iinfo.json"),
  "is-symmetric": () => import("./symbols/is-symmetric.json"),
  "isnat": () => import("./symbols/isnat.json"),
  "namespace": () => import("./symbols/namespace.json"),
  "ndenumerate": () => import("./symbols/ndenumerate.json"),
  "ndindex": () => import("./symbols/ndindex.json"),
  "nditer": () => import("./symbols/nditer.json"),
  "printoptions": () => import("./symbols/printoptions.json"),
  "random-random-state": () => import("./symbols/random-random-state.json"),
  "random-seed-sequence": () => import("./symbols/random-seed-sequence.json"),
  "random-ranf": () => import("./symbols/random-ranf.json"),
  "random-sample": () => import("./symbols/random-sample.json"),
  "random-symmetric": () => import("./symbols/random-symmetric.json"),
  "set-printoptions": () => import("./symbols/set-printoptions.json"),
  "seterr": () => import("./symbols/seterr.json"),
  "stats-cauchy": () => import("./symbols/stats-cauchy.json"),
  "stats-expon": () => import("./symbols/stats-expon.json"),
  "stats-laplace": () => import("./symbols/stats-laplace.json"),
  "stats-logistic": () => import("./symbols/stats-logistic.json"),
  "stats-lognorm": () => import("./symbols/stats-lognorm.json"),
  "stats-norm": () => import("./symbols/stats-norm.json"),
  "stats-truncnorm": () => import("./symbols/stats-truncnorm.json"),
  "stats-uniform": () => import("./symbols/stats-uniform.json"),
  "symmetrize": () => import("./symbols/symmetrize.json"),
  "testing-assert-allclose": () => import("./symbols/testing-assert-allclose.json"),
  "testing-assert-array-equal": () => import("./symbols/testing-assert-array-equal.json"),
};

export const symbolDocSlugs = [
  "as-symmetric",
  "base-repr",
  "binary-repr",
  "broadcast",
  "budget",
  "budget-context",
  "budget-live",
  "budget-reset",
  "budget-summary",
  "budget-summary-dict",
  "clear-einsum-cache",
  "configure",
  "cycle",
  "einsum-cache-info",
  "errstate",
  "finfo",
  "flops-bartlett-cost",
  "flops-blackman-cost",
  "flops-cholesky-cost",
  "flops-cond-cost",
  "flops-det-cost",
  "flops-eig-cost",
  "flops-eigh-cost",
  "flops-eigvals-cost",
  "flops-eigvalsh-cost",
  "flops-einsum-cost",
  "flops-fft-cost",
  "flops-fftn-cost",
  "flops-hamming-cost",
  "flops-hanning-cost",
  "flops-hfft-cost",
  "flops-inv-cost",
  "flops-kaiser-cost",
  "flops-lstsq-cost",
  "flops-matrix-norm-cost",
  "flops-matrix-power-cost",
  "flops-matrix-rank-cost",
  "flops-multi-dot-cost",
  "flops-norm-cost",
  "flops-pinv-cost",
  "flops-pointwise-cost",
  "flops-poly-cost",
  "flops-polyadd-cost",
  "flops-polyder-cost",
  "flops-polydiv-cost",
  "flops-polyfit-cost",
  "flops-polyint-cost",
  "flops-polymul-cost",
  "flops-polysub-cost",
  "flops-polyval-cost",
  "flops-qr-cost",
  "flops-reduction-cost",
  "flops-rfft-cost",
  "flops-rfftn-cost",
  "flops-roots-cost",
  "flops-slogdet-cost",
  "flops-solve-cost",
  "flops-svd-cost",
  "flops-svdvals-cost",
  "flops-tensorinv-cost",
  "flops-tensorsolve-cost",
  "flops-trace-cost",
  "flops-unwrap-cost",
  "flops-vector-norm-cost",
  "fromfile",
  "fromregex",
  "fromstring",
  "get-printoptions",
  "geterr",
  "iinfo",
  "is-symmetric",
  "isnat",
  "namespace",
  "ndenumerate",
  "ndindex",
  "nditer",
  "op-record",
  "path-info",
  "permutation",
  "permutation-group",
  "printoptions",
  "random-random-state",
  "random-ranf",
  "random-sample",
  "random-seed-sequence",
  "random-symmetric",
  "set-printoptions",
  "seterr",
  "stats-cauchy",
  "stats-expon",
  "stats-laplace",
  "stats-logistic",
  "stats-lognorm",
  "stats-norm",
  "stats-truncnorm",
  "stats-uniform",
  "step-info",
  "symmetric-tensor",
  "symmetrize",
  "symmetry-info",
  "testing-assert-allclose",
  "testing-assert-array-equal",
] as const;
