"""Math constants extracted from the math module at Docker build time.

Do not edit — regenerated by docker/lockdown/generate_constants.py.
"""

pi: float = 3.141592653589793
e: float = 2.718281828459045
inf: float = float("inf")
nan: float = float("nan")
