#!/usr/bin/env python3
"""Extract math constants at build time and write _constants.py.

Run BEFORE stripping the stdlib (math is still available).
The generated file has no 'import math' — just literal values
with full float64 precision via repr().

Usage:
    python generate_constants.py <output_path>
"""

import math
import sys


def main() -> None:
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <output_path>", file=sys.stderr)
        sys.exit(1)

    output_path = sys.argv[1]

    lines = [
        '"""Math constants extracted from the math module at Docker build time.',
        "",
        "Do not edit — regenerated by docker/lockdown/generate_constants.py.",
        '"""',
        "",
        f"pi: float = {math.pi!r}",
        f"e: float = {math.e!r}",
        f"inf: float = float({str(math.inf)!r})",
        f"nan: float = float({str(math.nan)!r})",
        "",
    ]

    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    # Verify roundtrip
    ns: dict = {}
    exec(open(output_path).read(), ns)
    assert ns["pi"] == math.pi, "pi roundtrip failed"
    assert ns["e"] == math.e, "e roundtrip failed"
    assert ns["inf"] == math.inf, "inf roundtrip failed"
    assert str(ns["nan"]) == str(math.nan), "nan roundtrip failed"
    print(f"Generated {output_path} with verified constants")


if __name__ == "__main__":
    main()
