#!/usr/bin/env python
"""generate_api_docs.py — Generate API reference pages and verify coverage.

Usage
-----
    python scripts/generate_api_docs.py              # generate all docs
    python scripts/generate_api_docs.py --verify     # check coverage only
"""

from __future__ import annotations

import argparse
import importlib
import inspect
import json
import sys
import textwrap
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
API_DIR = DOCS / "api"
REF_DIR = DOCS / "reference"

# ---------------------------------------------------------------------------
# Registry loading
# ---------------------------------------------------------------------------

def load_registry() -> dict[str, dict]:
    sys.path.insert(0, str(ROOT / "src"))
    from mechestim._registry import REGISTRY  # type: ignore
    return REGISTRY


# ---------------------------------------------------------------------------
# Module mapping: which mechestim source modules cover which registry ops
# ---------------------------------------------------------------------------

# Maps (registry module, category prefix) → list of mkdocstrings directives
# and the doc page they belong to.
#
# Existing pages (not generated):
#   counted-ops.md  → ::: mechestim._pointwise, ::: mechestim._einsum.einsum
#   free-ops.md     → ::: mechestim._free_ops
#
# Generated pages:
GENERATED_PAGES: dict[str, dict] = {
    "api/linalg.md": {
        "title": "Linear Algebra",
        "description": (
            "Operations from `mechestim.linalg`. "
            "Cost formulas vary per operation — see each function's docstring."
        ),
        "directives": [
            "mechestim.linalg._svd",
            "mechestim.linalg._decompositions",
            "mechestim.linalg._solvers",
            "mechestim.linalg._properties",
            "mechestim.linalg._compound",
            "mechestim.linalg._aliases",
        ],
        "registry_modules": {"numpy.linalg"},
    },
    "api/fft.md": {
        "title": "FFT",
        "description": (
            "Fast Fourier Transform operations from `mechestim.fft`. "
            "Transform costs scale as *n* log *n*."
        ),
        "directives": [
            "mechestim.fft._transforms",
            "mechestim.fft._free",
        ],
        "registry_modules": {"numpy.fft"},
    },
    "api/random.md": {
        "title": "Random",
        "description": (
            "Random number generation from `mechestim.random`. "
            "All random operations are **free** (0 FLOPs) — "
            "they are direct passthroughs to `numpy.random`."
        ),
        "directives": [
            "mechestim.random",
        ],
        "registry_modules": {"numpy.random"},
    },
    "api/polynomial.md": {
        "title": "Polynomial",
        "description": (
            "Polynomial operations from `mechestim`. "
            "Cost formulas vary per operation."
        ),
        "directives": [
            "mechestim._polynomial",
        ],
        "registry_modules": {"mechestim._polynomial"},
    },
    "api/window.md": {
        "title": "Window Functions",
        "description": (
            "Window function wrappers from `mechestim`. "
            "Cost formulas vary per operation."
        ),
        "directives": [
            "mechestim._window",
        ],
        "registry_modules": {"mechestim._window"},
    },
}

# Existing (non-generated) pages and what registry modules they cover
EXISTING_PAGES: dict[str, set[str]] = {
    "api/counted-ops.md": set(),   # covers numpy counted ops + einsum + unwrap
    "api/free-ops.md": set(),      # covers numpy free ops
    "api/symmetric.md": set(),     # covers SymmetricTensor, SymmetryInfo, as_symmetric
}


# ---------------------------------------------------------------------------
# Generate API reference pages
# ---------------------------------------------------------------------------

HEADER = "<!-- Auto-generated by scripts/generate_api_docs.py. Do not edit manually. -->"


def generate_api_page(page_path: str, page_info: dict) -> None:
    """Generate a single API reference markdown page."""
    out = DOCS / page_path
    out.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        HEADER,
        f"# {page_info['title']}",
        "",
        page_info["description"],
        "",
    ]

    for directive in page_info["directives"]:
        lines.append(f"::: {directive}")
        lines.append("")

    out.write_text("\n".join(lines))
    print(f"  Generated {page_path}")


# ---------------------------------------------------------------------------
# Generate operation audit page
# ---------------------------------------------------------------------------

CATEGORY_ORDER = [
    "free",
    "counted_unary",
    "counted_binary",
    "counted_reduction",
    "counted_custom",
    "blacklisted",
]

CATEGORY_LABELS = {
    "free": ("Free Operations (0 FLOPs)", "0 FLOPs"),
    "counted_unary": ("Counted Unary Operations", "numel(output)"),
    "counted_binary": ("Counted Binary Operations", "numel(output)"),
    "counted_reduction": ("Counted Reduction Operations", "numel(input)"),
    "counted_custom": ("Counted Custom Operations", "Per-operation formula"),
    "blacklisted": ("Blacklisted Operations", "Not available"),
}

CATEGORY_EMOJI = {
    "free": "\U0001f7e2",           # green circle
    "counted_unary": "\U0001f7e1",  # yellow circle
    "counted_binary": "\U0001f7e1",
    "counted_reduction": "\U0001f7e1",
    "counted_custom": "\U0001f7e0",  # orange circle
    "blacklisted": "\U0001f534",    # red circle
}

# ---------------------------------------------------------------------------
# Per-operation cost formulas (plain text + LaTeX)
# ---------------------------------------------------------------------------

CUSTOM_COSTS: dict[str, tuple[str, str]] = {
    "einsum": ("product of all index dims", r"$\prod_i d_i$"),
    "einsum_path": ("0 (planning only)", "$0$"),
    "dot": ("m * k * n", r"$m \cdot k \cdot n$"),
    "matmul": ("m * k * n", r"$m \cdot k \cdot n$"),
    "inner": ("n", "$n$"),
    "outer": ("m * n", r"$m \cdot n$"),
    "tensordot": ("product of contracted dims * output size", r"$\prod_i d_i$"),
    "vdot": ("n", "$n$"),
    "vecdot": ("n", "$n$"),
    "kron": ("m1*m2 * n1*n2", r"$m_1 m_2 \cdot n_1 n_2$"),
    "clip": ("numel(input)", r"$\text{numel}(\text{input})$"),
    "cross": ("numel(output)", r"$\text{numel}(\text{output})$"),
    "diff": ("numel(input)", r"$\text{numel}(\text{input})$"),
    "ediff1d": ("numel(input)", r"$\text{numel}(\text{input})$"),
    "gradient": ("numel(input)", r"$\text{numel}(\text{input})$"),
    "convolve": ("n * m", r"$n \cdot m$"),
    "correlate": ("n * m", r"$n \cdot m$"),
    "corrcoef": ("n^2 * m", r"$n^2 \cdot m$"),
    "cov": ("n^2 * m", r"$n^2 \cdot m$"),
    "interp": ("n * log(m)", r"$n \cdot \log m$"),
    "trapezoid": ("numel(input)", r"$\text{numel}(\text{input})$"),
    "trapz": ("numel(input)", r"$\text{numel}(\text{input})$"),
    "linalg.svd": ("m * n * k", r"$m \cdot n \cdot k$"),
    "linalg.svdvals": ("m * n * min(m,n)", r"$m \cdot n \cdot \min(m,n)$"),
    "linalg.cholesky": ("n^3 / 3", r"$n^3 / 3$"),
    "linalg.qr": ("2mn^2 - 2n^3/3", r"$2mn^2 - 2n^3/3$"),
    "linalg.eig": ("10n^3", r"$10n^3$"),
    "linalg.eigh": ("4n^3 / 3", r"$4n^3 / 3$"),
    "linalg.eigvals": ("10n^3", r"$10n^3$"),
    "linalg.eigvalsh": ("4n^3 / 3", r"$4n^3 / 3$"),
    "linalg.solve": ("2n^3/3 + n^2*nrhs", r"$2n^3/3 + n^2 \cdot n_{\text{rhs}}$"),
    "linalg.inv": ("n^3", r"$n^3$"),
    "linalg.lstsq": ("m * n * min(m,n)", r"$m \cdot n \cdot \min(m,n)$"),
    "linalg.pinv": ("m * n * min(m,n)", r"$m \cdot n \cdot \min(m,n)$"),
    "linalg.tensorsolve": ("n^3", r"$n^3$"),
    "linalg.tensorinv": ("n^3", r"$n^3$"),
    "linalg.trace": ("n", "$n$"),
    "linalg.det": ("n^3", r"$n^3$"),
    "linalg.slogdet": ("n^3", r"$n^3$"),
    "linalg.norm": ("depends on ord", r"varies"),
    "linalg.vector_norm": ("n or 2n", r"$n$ or $2n$"),
    "linalg.matrix_norm": ("depends on ord", r"varies"),
    "linalg.cond": ("m * n * min(m,n)", r"$m \cdot n \cdot \min(m,n)$"),
    "linalg.matrix_rank": ("m * n * min(m,n)", r"$m \cdot n \cdot \min(m,n)$"),
    "linalg.multi_dot": ("optimal chain cost", r"optimal chain"),
    "linalg.matrix_power": ("log2(k) * n^3", r"$\lfloor\log_2 k\rfloor \cdot n^3$"),
    "fft.fft": ("5n * ceil(log2(n))", r"$5n \cdot \lceil\log_2 n\rceil$"),
    "fft.ifft": ("5n * ceil(log2(n))", r"$5n \cdot \lceil\log_2 n\rceil$"),
    "fft.fft2": ("5N * ceil(log2(N))", r"$5N \cdot \lceil\log_2 N\rceil$"),
    "fft.ifft2": ("5N * ceil(log2(N))", r"$5N \cdot \lceil\log_2 N\rceil$"),
    "fft.fftn": ("5N * ceil(log2(N))", r"$5N \cdot \lceil\log_2 N\rceil$"),
    "fft.ifftn": ("5N * ceil(log2(N))", r"$5N \cdot \lceil\log_2 N\rceil$"),
    "fft.rfft": ("5(n/2) * ceil(log2(n))", r"$5(n/2) \cdot \lceil\log_2 n\rceil$"),
    "fft.irfft": ("5(n/2) * ceil(log2(n))", r"$5(n/2) \cdot \lceil\log_2 n\rceil$"),
    "fft.rfft2": ("5(N/2) * ceil(log2(N))", r"$5(N/2) \cdot \lceil\log_2 N\rceil$"),
    "fft.irfft2": ("5(N/2) * ceil(log2(N))", r"$5(N/2) \cdot \lceil\log_2 N\rceil$"),
    "fft.rfftn": ("5(N/2) * ceil(log2(N))", r"$5(N/2) \cdot \lceil\log_2 N\rceil$"),
    "fft.irfftn": ("5(N/2) * ceil(log2(N))", r"$5(N/2) \cdot \lceil\log_2 N\rceil$"),
    "fft.hfft": ("5n * ceil(log2(n))", r"$5n \cdot \lceil\log_2 n\rceil$"),
    "fft.ihfft": ("5n * ceil(log2(n))", r"$5n \cdot \lceil\log_2 n\rceil$"),
    "polyval": ("2 * m * deg", r"$2 \cdot m \cdot \text{deg}$"),
    "polyadd": ("max(n1, n2)", r"$\max(n_1, n_2)$"),
    "polysub": ("max(n1, n2)", r"$\max(n_1, n_2)$"),
    "polyder": ("n", "$n$"),
    "polyint": ("n", "$n$"),
    "polymul": ("n1 * n2", r"$n_1 \cdot n_2$"),
    "polydiv": ("n1 * n2", r"$n_1 \cdot n_2$"),
    "polyfit": ("2m * (deg+1)^2", r"$2m \cdot (\text{deg}+1)^2$"),
    "poly": ("n^2", r"$n^2$"),
    "roots": ("10n^3", r"$10n^3$"),
    "bartlett": ("n", "$n$"),
    "blackman": ("3n", "$3n$"),
    "hamming": ("n", "$n$"),
    "hanning": ("n", "$n$"),
    "kaiser": ("3n", "$3n$"),
    "unwrap": ("numel(input)", r"$\text{numel}(\text{input})$"),
}

CATEGORY_COST_LATEX: dict[str, tuple[str, str]] = {
    "free": ("0", "$0$"),
    "counted_unary": ("numel(output)", r"$\text{numel}(\text{output})$"),
    "counted_binary": ("numel(output)", r"$\text{numel}(\text{output})$"),
    "counted_reduction": ("numel(input)", r"$\text{numel}(\text{input})$"),
    "counted_custom": ("per-operation", "varies"),
    "blacklisted": ("N/A", "N/A"),
}


# ---------------------------------------------------------------------------
# Helper functions for op references and cost lookup
# ---------------------------------------------------------------------------

def mechestim_ref(name: str, module: str) -> str:
    """Derive the mechestim call reference from an op name and registry module."""
    if module == "numpy.linalg":
        return f"`me.linalg.{name.removeprefix('linalg.')}`"
    if module == "numpy.fft":
        return f"`me.fft.{name.removeprefix('fft.')}`"
    if module == "numpy.random":
        return f"`me.random.{name.removeprefix('random.')}`"
    return f"`me.{name}`"


def numpy_ref(name: str, module: str) -> str:
    """Derive the NumPy call reference from an op name and registry module."""
    if module == "numpy.linalg":
        return f"`np.linalg.{name.removeprefix('linalg.')}`"
    if module == "numpy.fft":
        return f"`np.fft.{name.removeprefix('fft.')}`"
    if module == "numpy.random":
        return f"`np.random.{name.removeprefix('random.')}`"
    return f"`np.{name}`"


def cost_for_op(name: str, category: str) -> tuple[str, str]:
    """Return (plain_text, latex) cost formula for an operation."""
    if name in CUSTOM_COSTS:
        return CUSTOM_COSTS[name]
    return CATEGORY_COST_LATEX.get(category, ("unknown", "unknown"))


def generate_audit_page(registry: dict[str, dict]) -> None:
    """Generate docs/reference/operation-audit.md from the registry."""
    REF_DIR.mkdir(parents=True, exist_ok=True)

    # Group ops by category
    by_cat: dict[str, list[str]] = {cat: [] for cat in CATEGORY_ORDER}
    for name, info in sorted(registry.items()):
        cat = info["category"]
        if cat in by_cat:
            by_cat[cat].append(name)

    lines = [
        HEADER,
        "# Operation Audit",
        "",
        "Complete list of every NumPy operation and its mechestim category.",
        "Generated from the operation registry (`_registry.py`).",
        "",
        "## Summary",
        "",
        "| Category | Count | Cost |",
        "|----------|-------|------|",
    ]

    total = 0
    for cat in CATEGORY_ORDER:
        label, cost = CATEGORY_LABELS[cat]
        count = len(by_cat[cat])
        total += count
        lines.append(f"| {cat} | {count} | {cost} |")
    lines.append(f"| **Total** | **{total}** | |")
    lines.append("")

    # Per-category sections
    for cat in CATEGORY_ORDER:
        label, cost = CATEGORY_LABELS[cat]
        emoji = CATEGORY_EMOJI[cat]
        ops = by_cat[cat]
        lines.append(f"## {emoji} {label}")
        lines.append("")
        lines.append(f"**{len(ops)} operations:**")
        lines.append("")

        # Format as backtick-wrapped, 6 per line
        formatted = [f"`{op}`" for op in ops]
        for i in range(0, len(formatted), 6):
            chunk = ", ".join(formatted[i:i+6])
            lines.append(chunk)
        lines.append("")

    out = REF_DIR / "operation-audit.md"
    out.write_text("\n".join(lines))
    print(f"  Generated reference/operation-audit.md")


def generate_ops_json(registry: dict[str, dict]) -> None:
    """Generate docs/ops.json — machine-readable operation manifest."""
    ops = []
    for name, info in sorted(registry.items()):
        cat = info["category"]
        mod = info["module"]
        plain, latex = cost_for_op(name, cat)
        ops.append({
            "name": name,
            "module": mod,
            "mechestim_ref": mechestim_ref(name, mod).strip("`"),
            "numpy_ref": numpy_ref(name, mod).strip("`"),
            "category": cat,
            "cost_formula": plain,
            "cost_formula_latex": latex,
            "free": cat == "free",
            "blocked": cat == "blacklisted",
            "status": "blocked" if cat == "blacklisted" else "supported",
            "notes": info.get("notes", ""),
        })
    out = DOCS / "ops.json"
    out.write_text(json.dumps({"operations": ops, "total": len(ops)}, indent=2))
    print(f"  Generated ops.json ({len(ops)} operations)")


# ---------------------------------------------------------------------------
# Update counted-ops.md to include polynomial, window, unwrap
# ---------------------------------------------------------------------------

def update_counted_ops_page(registry: dict[str, dict]) -> None:
    """Ensure counted-ops.md includes directives for polynomial, window, unwrap."""
    page = API_DIR / "counted-ops.md"
    content = page.read_text()

    additions = []
    for module_directive, label in [
        ("mechestim._polynomial", "polynomial"),
        ("mechestim._window", "window"),
        ("mechestim._unwrap", "unwrap"),
    ]:
        if f"::: {module_directive}" not in content:
            additions.append(f"\n::: {module_directive}")

    if additions:
        new_content = content.rstrip() + "\n" + "\n".join(additions) + "\n"
        page.write_text(new_content)
        print(f"  Updated api/counted-ops.md with: {', '.join(a.strip().removeprefix('::: ') for a in additions)}")
    else:
        print(f"  api/counted-ops.md already up to date")


# ---------------------------------------------------------------------------
# Verify coverage
# ---------------------------------------------------------------------------

def get_module_public_names(module_path: str) -> set[str]:
    """Import a module and return its public callable names."""
    try:
        mod = importlib.import_module(module_path)
    except ImportError:
        return set()

    if hasattr(mod, "__all__"):
        return {n for n in mod.__all__ if callable(getattr(mod, n, None))}

    return {
        n for n, obj in inspect.getmembers(mod)
        if not n.startswith("_") and callable(obj)
    }


def extract_directives_from_file(path: Path) -> list[str]:
    """Extract ::: directives from a markdown file."""
    directives = []
    if not path.exists():
        return directives
    for line in path.read_text().splitlines():
        stripped = line.strip()
        if stripped.startswith("::: "):
            directives.append(stripped[4:].strip())
    return directives


def verify_coverage(registry: dict[str, dict]) -> bool:
    """Verify that every non-blacklisted op is covered by an API doc page."""
    # Collect all non-blacklisted ops grouped by registry module
    ops_by_module: dict[str, set[str]] = {}
    for name, info in registry.items():
        if info["category"] == "blacklisted":
            continue
        module = info["module"]
        ops_by_module.setdefault(module, set()).add(name)

    # Collect all modules referenced by ::: directives across all API pages
    covered_modules: dict[str, set[str]] = {}  # directive → set of public names
    for md_file in API_DIR.glob("*.md"):
        for directive in extract_directives_from_file(md_file):
            names = get_module_public_names(directive)
            # Handle single-function directives like mechestim._einsum.einsum
            if not names:
                # Could be a function path like mechestim._einsum.einsum
                parts = directive.rsplit(".", 1)
                if len(parts) == 2:
                    mod_path, func_name = parts
                    try:
                        mod = importlib.import_module(mod_path)
                        if hasattr(mod, func_name):
                            names = {func_name}
                    except ImportError:
                        pass
            covered_modules[directive] = names

    all_covered_names: set[str] = set()
    for names in covered_modules.values():
        all_covered_names.update(names)

    # Also add random.* ops — the random module uses __getattr__ passthrough,
    # so we check that random ops are covered if mechestim.random directive exists
    random_directive_exists = any("mechestim.random" in d for d in covered_modules)
    if random_directive_exists:
        for name, info in registry.items():
            if info["module"] == "numpy.random" and info["category"] != "blacklisted":
                # Strip the "random." prefix for matching
                bare_name = name.removeprefix("random.")
                all_covered_names.add(name)
                all_covered_names.add(bare_name)

    # Check: which non-blacklisted ops are missing?
    missing = []
    for name, info in sorted(registry.items()):
        if info["category"] == "blacklisted":
            continue

        # Check if the op name (possibly prefixed) is covered
        bare = name.split(".")[-1]  # e.g., "linalg.svd" → "svd"
        if name in all_covered_names or bare in all_covered_names:
            continue

        missing.append((name, info["category"], info["module"]))

    if missing:
        print(f"\nMISSING from API docs ({len(missing)} ops):\n")
        for name, cat, mod in missing:
            print(f"  {name:40s} {cat:20s} {mod}")
        print(f"\nRun 'python scripts/generate_api_docs.py' to regenerate.")
        return False
    else:
        total_non_bl = sum(1 for i in registry.values() if i["category"] != "blacklisted")
        print(f"\nAll {total_non_bl} non-blacklisted operations are covered in API docs.")
        return True


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Generate API docs from mechestim registry")
    parser.add_argument("--verify", action="store_true", help="Verify coverage only (no generation)")
    args = parser.parse_args()

    registry = load_registry()

    if args.verify:
        ok = verify_coverage(registry)
        sys.exit(0 if ok else 1)

    print("Generating API reference pages...")

    # Generate new submodule pages
    for page_path, page_info in GENERATED_PAGES.items():
        generate_api_page(page_path, page_info)

    # Update counted-ops to include polynomial/window/unwrap
    update_counted_ops_page(registry)

    # Generate audit page
    generate_audit_page(registry)

    # Generate ops.json
    generate_ops_json(registry)

    print("\nDone. Run with --verify to check coverage.")


if __name__ == "__main__":
    main()
