#!/usr/bin/env python
"""Generate derived client artifacts from the core mechestim library.

Usage:
    uv run scripts/sync_client.py          # regenerate files in-place
    uv run scripts/sync_client.py --check  # exit non-zero if anything would change
"""
from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

_HEADER = '''\
# AUTO-GENERATED by scripts/sync_client.py — DO NOT EDIT
# Source of truth: the mechestim core library (src/mechestim/)
# Regenerate: uv run scripts/sync_client.py
'''

_CLIENT_SRC = Path(__file__).resolve().parent.parent / "mechestim-client" / "src" / "mechestim"


def _generate_registry_data() -> str:
    """Generate _registry_data.py from core REGISTRY."""
    from mechestim._registry import REGISTRY

    lines = [_HEADER, '"""Registry data snapshot for the mechestim client."""\n\n']
    lines.append("FUNCTION_CATEGORIES: dict[str, str] = {\n")
    for name in sorted(REGISTRY.keys()):
        cat = REGISTRY[name]["category"]
        lines.append(f'    {name!r}: {cat!r},\n')
    lines.append("}\n")
    return "".join(lines)


def _write_or_check(path: Path, content: str, check: bool, diffs: list[str]) -> None:
    """Write content to path, or check if it matches."""
    path.parent.mkdir(parents=True, exist_ok=True)
    if check:
        existing = path.read_text() if path.exists() else ""
        if existing != content:
            diff = difflib.unified_diff(
                existing.splitlines(keepends=True),
                content.splitlines(keepends=True),
                fromfile=str(path),
                tofile=str(path) + " (generated)",
            )
            diffs.append(f"--- {path} is out of sync ---\n" + "".join(diff))
    else:
        path.write_text(content)
        print(f"  wrote {path}")


def _generate_perm_group() -> str:
    """Copy _perm_group.py from core (pure Python, no numpy dependency)."""
    core_path = Path(__file__).resolve().parent.parent / "src" / "mechestim" / "_perm_group.py"
    content = core_path.read_text()
    return _HEADER + "\n" + content


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="Exit non-zero if any file would change")
    args = parser.parse_args()
    diffs: list[str] = []

    print("Generating registry data...")
    _write_or_check(
        _CLIENT_SRC / "_registry_data.py",
        _generate_registry_data(),
        args.check, diffs,
    )

    print("Generating perm group classes...")
    _write_or_check(
        _CLIENT_SRC / "_perm_group.py",
        _generate_perm_group(),
        args.check, diffs,
    )

    if diffs:
        print("\n".join(diffs), file=sys.stderr)
        print(f"\n{len(diffs)} file(s) out of sync. Run: uv run scripts/sync_client.py",
              file=sys.stderr)
        sys.exit(1)
    elif args.check:
        print("All generated files are in sync.")


if __name__ == "__main__":
    main()
