#!/usr/bin/env python
"""Generate derived client artifacts from the core whest library.

Usage:
    uv run scripts/sync_client.py          # regenerate files in-place
    uv run scripts/sync_client.py --check  # exit non-zero if anything would change
"""

from __future__ import annotations

import argparse
import difflib
import subprocess
import sys
from pathlib import Path

_HEADER = """\
# AUTO-GENERATED by scripts/sync_client.py — DO NOT EDIT
# Source of truth: the whest core library (src/whest/)
# Regenerate: uv run scripts/sync_client.py
"""

_CLIENT_SRC = Path(__file__).resolve().parent.parent / "whest-client" / "src" / "whest"


def _generate_registry_data() -> str:
    """Generate _registry_data.py from core REGISTRY."""
    from whest._registry import REGISTRY

    lines = [_HEADER, '"""Registry data snapshot for the whest client."""\n\n']
    lines.append("FUNCTION_CATEGORIES: dict[str, str] = {\n")
    for name in sorted(REGISTRY.keys()):
        cat = REGISTRY[name]["category"]
        lines.append(f"    {name!r}: {cat!r},\n")
    lines.append("}\n")
    return "".join(lines)


def _ruff_format(content: str) -> str:
    """Run ruff format on a string of Python code, return formatted version."""
    result = subprocess.run(
        ["ruff", "format", "--stdin-filename", "_.py"],
        input=content,
        capture_output=True,
        text=True,
    )
    return result.stdout if result.returncode == 0 else content


def _write_or_check(path: Path, content: str, check: bool, diffs: list[str]) -> None:
    """Write content to path, or check if it matches."""
    content = _ruff_format(content)
    path.parent.mkdir(parents=True, exist_ok=True)
    if check:
        existing = path.read_text() if path.exists() else ""
        if existing != content:
            diff = difflib.unified_diff(
                existing.splitlines(keepends=True),
                content.splitlines(keepends=True),
                fromfile=str(path),
                tofile=str(path) + " (generated)",
            )
            diffs.append(f"--- {path} is out of sync ---\n" + "".join(diff))
    else:
        path.write_text(content)
        print(f"  wrote {path}")


def _generate_errors() -> str:
    """Generate errors.py for the client from core whest.errors."""
    # Classes with custom __init__ that need message-based constructors
    _CUSTOM_INIT_CLASSES = {
        "BudgetExhaustedError",
        "NoBudgetContextError",
        "SymmetryError",
        "TimeExhaustedError",
        "UnsupportedFunctionError",
    }

    # (class_name, base_class, docstring) in declaration order
    _CLASSES = [
        ("WhestError", "Exception", "Base exception for all whest errors."),
        (
            "BudgetExhaustedError",
            "WhestError",
            "Raised when an operation would exceed the FLOP budget.",
        ),
        (
            "TimeExhaustedError",
            "WhestError",
            "Raised when an operation exceeds the wall-clock time limit.",
        ),
        (
            "NoBudgetContextError",
            "WhestError",
            "Raised when a counted operation is called outside a BudgetContext.",
        ),
        (
            "SymmetryError",
            "WhestError",
            "Raised when a claimed tensor symmetry does not hold.",
        ),
        (
            "UnsupportedFunctionError",
            "WhestError",
            "Raised when calling a function not available in the installed NumPy.",
        ),
        (
            "WhestWarning",
            "UserWarning",
            "Warning issued when whest detects potential numerical issues.",
        ),
        (
            "SymmetryLossWarning",
            "WhestWarning",
            "Warning issued when an operation causes loss of symmetry metadata.",
        ),
        # client-only
        (
            "WhestServerError",
            "WhestError",
            "Server-side error that does not map to a more specific exception.",
        ),
    ]

    # Whest error class names (excludes warnings) for _WHEST_ERRORS frozenset
    _WHEST_ERROR_NAMES = [
        name
        for name, base, _ in _CLASSES
        if "Warning" not in name and name != "WhestError" and name != "WhestServerError"
    ]

    lines = [
        _HEADER,
        '"""Custom exceptions and warnings for the whest client."""\n\n',
        "from __future__ import annotations\n\n\n",
    ]

    for cls_name, base, doc in _CLASSES:
        lines.append(f"class {cls_name}({base}):\n")
        lines.append(f'    """{doc}"""\n')
        if cls_name in _CUSTOM_INIT_CLASSES:
            lines.append("\n")
            lines.append('    def __init__(self, message: str = "") -> None:\n')
            lines.append("        super().__init__(message)\n")
        lines.append("\n\n")

    # _WHEST_ERRORS frozenset
    lines.append(
        "# ---------------------------------------------------------------------------\n"
    )
    lines.append("# Error map and dispatcher\n")
    lines.append(
        "# ---------------------------------------------------------------------------\n\n"
    )
    lines.append("_WHEST_ERRORS: frozenset[str] = frozenset(\n")
    lines.append("    {\n")
    for name in _WHEST_ERROR_NAMES:
        lines.append(f"        {name!r},\n")
    lines.append("    }\n")
    lines.append(")\n\n")

    # _ERROR_MAP dict
    lines.append("_ERROR_MAP: dict[str, type[Exception]] = {\n")
    for name in _WHEST_ERROR_NAMES:
        lines.append(f"    {name!r}: {name},\n")
    lines.append(f"    {'WhestServerError'!r}: WhestServerError,\n")
    for std_name, mapped in [
        ("ValueError", "ValueError"),
        ("TypeError", "TypeError"),
        ("KeyError", "KeyError"),
        ("RuntimeError", "RuntimeError"),
        ("InvalidRequestError", "WhestServerError"),
    ]:
        lines.append(f"    {std_name!r}: {mapped},\n")
    lines.append("}\n\n\n")

    # raise_from_response function
    lines.append(
        "def raise_from_response(error_type: str, message: str) -> None:\n"
        '    """Map *error_type* string to an exception class and raise it.\n\n'
        "    Unknown error types are treated as :class:`WhestServerError`.\n"
        '    """\n'
        "    # Ensure message is a str (server may send bytes if it contains non-ASCII)\n"
        "    if isinstance(message, bytes):\n"
        '        message = message.decode("utf-8", errors="replace")\n'
        "    if isinstance(error_type, bytes):\n"
        '        error_type = error_type.decode("utf-8", errors="replace")\n'
        "\n"
        "    exc_cls = _ERROR_MAP.get(error_type, WhestServerError)\n"
        "    if error_type in _WHEST_ERRORS:\n"
        "        raise exc_cls(message=message)\n"
        "    raise exc_cls(message)\n"
    )

    return "".join(lines)


def _generate_perm_group() -> str:
    """Copy _perm_group.py from core (pure Python, no numpy dependency)."""
    core_path = (
        Path(__file__).resolve().parent.parent / "src" / "whest" / "_perm_group.py"
    )
    content = core_path.read_text()
    return _HEADER + "\n" + content


def _generate_stats_init() -> str:
    """Generate stats/__init__.py with proxy distribution objects."""
    import whest.stats as core_stats

    dist_names = sorted(core_stats.__all__)

    lines = [_HEADER]
    lines.append(
        '"""whest.stats \u2014 statistical distributions submodule proxy."""\n\n'
    )
    lines.append("from __future__ import annotations\n\n")
    lines.append("from whest._connection import get_connection\n")
    lines.append("from whest._getattr import make_module_getattr\n")
    lines.append("from whest._protocol import encode_request\n")
    lines.append("from whest._remote_array import (\n")
    lines.append("    _encode_arg,\n")
    lines.append("    _result_from_response,\n")
    lines.append(")\n\n\n")

    # _DistributionProxy class with pdf, cdf, ppf
    lines.append("class _DistributionProxy:\n")
    lines.append('    """Proxy for a server-side statistical distribution."""\n\n')
    lines.append("    def __init__(self, name: str) -> None:\n")
    lines.append("        self._name = name\n\n")
    lines.append("    def __repr__(self) -> str:\n")
    lines.append('        return f"<whest.stats.{self._name}>"\n\n')

    for method in ("pdf", "cdf", "ppf"):
        lines.append(f"    def {method}(self, x, *args, **kwargs):\n")
        lines.append(
            f'        """Dispatch stats.{{self._name}}.{method} to the server."""\n'
        )
        lines.append("        conn = get_connection()\n")
        lines.append(f'        op = f"stats.{{self._name}}.{method}"\n')
        lines.append(
            "        encoded_args = [_encode_arg(x)] + [_encode_arg(a) for a in args]\n"
        )
        lines.append(
            "        encoded_kwargs = {k: _encode_arg(v) for k, v in kwargs.items()}\n"
        )
        lines.append("        resp = conn.send_recv(\n")
        lines.append(
            "            encode_request(op, args=encoded_args, kwargs=encoded_kwargs)\n"
        )
        lines.append("        )\n")
        lines.append("        return _result_from_response(resp)\n\n")

    # Distribution instances
    lines.append("\n# Distribution instances\n")
    for name in dist_names:
        lines.append(f"{name} = _DistributionProxy({name!r})\n")

    lines.append(f"\n__all__ = {dist_names!r}\n\n")
    lines.append("# Fall-through for unknown names\n")
    lines.append('__getattr__ = make_module_getattr("stats.", "whest.stats")\n')

    return "".join(lines)


def _generate_linalg_init() -> str:
    """Generate linalg/__init__.py with proxies for all linalg ops."""
    from whest._registry import REGISTRY

    linalg_ops = sorted(
        name[len("linalg.") :]
        for name, entry in REGISTRY.items()
        if name.startswith("linalg.") and entry["category"] != "blacklisted"
    )

    lines = [_HEADER]
    lines.append('"""whest.linalg \u2014 linear algebra submodule proxy."""\n\n')
    lines.append("from __future__ import annotations\n\n")
    lines.append("from whest._connection import get_connection\n")
    lines.append("from whest._getattr import make_module_getattr\n")
    lines.append("from whest._protocol import encode_request\n")
    lines.append("from whest._remote_array import (\n")
    lines.append("    _encode_arg,\n")
    lines.append("    _result_from_response,\n")
    lines.append(")\n\n\n")

    lines.append("def _make_linalg_proxy(op_name: str):\n")
    lines.append('    """Create a proxy function for ``linalg.<op_name>``."""\n')
    lines.append('    qualified = f"linalg.{op_name}"\n\n')
    lines.append("    def proxy(*args, **kwargs):\n")
    lines.append("        conn = get_connection()\n")
    lines.append("        encoded_args = [_encode_arg(a) for a in args]\n")
    lines.append(
        "        encoded_kwargs = {k: _encode_arg(v) for k, v in kwargs.items()}\n"
    )
    lines.append("        resp = conn.send_recv(\n")
    lines.append(
        "            encode_request(qualified, args=encoded_args, kwargs=encoded_kwargs)\n"
    )
    lines.append("        )\n")
    lines.append("        return _result_from_response(resp)\n\n")
    lines.append("    proxy.__name__ = op_name\n")
    lines.append('    proxy.__qualname__ = f"linalg.{op_name}"\n')
    lines.append("    return proxy\n\n\n")

    for op in linalg_ops:
        lines.append(f"{op} = _make_linalg_proxy({op!r})\n")

    lines.append("\n# Fall-through for blacklisted / unknown names\n")
    lines.append('__getattr__ = make_module_getattr("linalg.", "whest.linalg")\n')

    return "".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="Exit non-zero if any file would change"
    )
    args = parser.parse_args()
    diffs: list[str] = []

    print("Generating registry data...")
    _write_or_check(
        _CLIENT_SRC / "_registry_data.py",
        _generate_registry_data(),
        args.check,
        diffs,
    )

    print("Generating errors...")
    _write_or_check(
        _CLIENT_SRC / "errors.py",
        _generate_errors(),
        args.check,
        diffs,
    )

    print("Generating perm group classes...")
    _write_or_check(
        _CLIENT_SRC / "_perm_group.py",
        _generate_perm_group(),
        args.check,
        diffs,
    )

    print("Generating stats proxy...")
    _write_or_check(
        _CLIENT_SRC / "stats" / "__init__.py",
        _generate_stats_init(),
        args.check,
        diffs,
    )

    print("Generating linalg proxy...")
    _write_or_check(
        _CLIENT_SRC / "linalg" / "__init__.py",
        _generate_linalg_init(),
        args.check,
        diffs,
    )

    if diffs:
        print("\n".join(diffs), file=sys.stderr)
        print(
            f"\n{len(diffs)} file(s) out of sync. Run: uv run scripts/sync_client.py",
            file=sys.stderr,
        )
        sys.exit(1)
    elif args.check:
        print("All generated files are in sync.")


if __name__ == "__main__":
    main()
