import type { SectionCopy } from '../schema';

const p = (text: string) => ({ kind: 'paragraph', text } as const);
const l = (text: string) => ({ kind: 'label', text } as const);

const section1 = {
  title: 'The main page computes a pointwise group',
  deck: 'The cost panels group together only relabelings that preserve the indexed summand before summation.',
  slots: {
    intro: [
      p('Let $L$ be all labels, $V$ the output labels, and $W = L \\setminus V$ the summed labels. The main page searches for symmetries by acting on the rows of the incidence matrix $M$. A candidate row move $\\sigma$ comes from repeated operands and declared operand symmetries. It is admissible only when the row-permuted matrix has column fingerprints that can be matched bijectively back to the original columns while preserving label domains.'),
      p('When such a bijection exists, it induces a label relabeling $\\pi_\\sigma$. The group generated by these admissible relabelings is $G_{\\text{pt}}$, the pointwise symmetry group. It is the group used by the main page’s direct cost calculation because its orbits contain assignments whose summand products are equal before summation is performed.'),
    ],
    takeaway: [
      p('$G_{\\text{pt}}$ is a cost group: it is valid for direct product/update compression because it identifies equal indexed products under the declared equality model.'),
    ],
    auditIntro: [
      l('σ-loop audit'),
      p('The table below is an implementation audit of the $\\sigma$-loop for representative presets.'),
    ],
    columnGuide: [
      p('Columns. $L$, $V$, $W$ record all labels, output labels, and summed labels. $H_A$, $m_A$ record the declared operand symmetry and operand multiplicity.'),
      p('$|G_{\\mathrm{wreath}}|$ counts candidate row moves before filtering. Recorded counts admissible non-identity relabelings, Identity-only counts admissible moves whose induced relabeling is the identity, Rejected counts failed fingerprint/domain checks, and $|G_{\\text{pt}}|$ is the final detected pointwise group size.'),
    ],
    followups: [
      l('Frobenius.'),
      p('The operand swap is admissible, but the induced relabeling stays the identity, so no non-identity pointwise symmetry is recorded.'),
      l('Triangle.'),
      p('The same preset displays both accepted and rejected row moves, so the row-level boundary is visible in one table.'),
    ],
  },
} satisfies SectionCopy;

export default section1;
