import type { SectionCopy } from '../schema';

const p = (text: string) => ({ kind: 'paragraph', text } as const);
const l = (text: string) => ({ kind: 'label', text } as const);

const section1 = {
  title: 'Product-side symmetry before summation',
  deck: 'The main page compresses products only by relabelings that preserve the indexed summand before summation.',
  slots: {
    intro: [
      p('Let $L$ be all labels, $V$ the output labels, and $W = L \\setminus V$ the summed labels. The main page searches for symmetries by acting on the rows of the incidence matrix $M$. A candidate row move $\\sigma$ comes from repeated operands and declared operand symmetries. It is admissible only when the row-permuted matrix has column fingerprints that can be matched bijectively back to the original columns while preserving label domains.'),
      p('When such a bijection exists, it induces a label relabeling $\\pi_\\sigma$. The group generated by these admissible relabelings is $G_{\\text{pt}}$, the product-side pointwise group. Its orbits contain full assignments whose summand products are equal before summation, which is why the direct cost can collapse them to one representative product.'),
    ],
    takeaway: [
      p('$G_{\\text{pt}}$ is the product-side cost group. Its orbits identify equal indexed products before summation. Accumulation also needs the derived output-side action $H$, introduced below.'),
    ],
    auditIntro: [
      l('σ-loop audit'),
      p('The table below is an implementation audit of the $\\sigma$-loop for representative presets.'),
    ],
    columnGuide: [
      p('Columns. $L$, $V$, $W$ record all labels, output labels, and summed labels. $H_A$, $m_A$ record the declared operand symmetry and operand multiplicity.'),
      p('$|G_{\\mathrm{wreath}}|$ counts candidate row moves before filtering. Recorded counts admissible non-identity relabelings, Identity-only counts admissible moves whose induced relabeling is the identity, Rejected counts failed fingerprint/domain checks, and $|G_{\\text{pt}}|$ is the final detected pointwise group size.'),
    ],
    followups: [
      l('Frobenius.'),
      p('The operand swap is admissible, but the induced relabeling stays the identity, so no non-identity pointwise symmetry is recorded.'),
      l('Triangle.'),
      p('The same preset displays both accepted and rejected row moves, so the row-level boundary is visible in one table.'),
    ],
  },
} satisfies SectionCopy;

export default section1;
