import type { SectionCopy } from '../schema.ts';

const p = (text: string) => ({ kind: 'paragraph', text } as const);
const l = (text: string) => ({ kind: 'label', text } as const);

const section1 = {
  title: 'The main page computes a pointwise group',
  deck: 'The cost panels group together only those symmetries that preserve the indexed summand before summation.',
  slots: {
    intro: [
      p('Let $L$ be the set of all labels in the einsum, $V_{\\mathrm{free}}$ the output labels, and $W_{\\mathrm{summed}} = L \\setminus V_{\\mathrm{free}}$ the summed labels. The main page searches for symmetries by acting on the rows of the incidence matrix $M$. A candidate row move $\\sigma_{\\mathrm{row\\;move}}$ comes from repeated operands and declared operand symmetries. It is admissible only when the row-permuted matrix $M_\\sigma$ has column fingerprints that can be matched bijectively back to the original columns of $M$.'),
      p('When such a bijection exists, it induces a label relabeling $\\pi_\\sigma$. The group generated by the admissible relabelings is $G_{\\mathrm{pt}}$, the pointwise symmetry group. This is the group used by the main page’s cost calculation, because its orbits contain assignments whose summand products are equal before the summation is performed.'),
    ],
    takeaway: [
      p('$G_{\\mathrm{pt}}$ is a cost group: it is valid for accumulation because it identifies genuinely equal indexed products.'),
    ],
    auditIntro: [
      l('σ-loop audit'),
      p('The table below is an implementation audit of the $\\sigma$-loop for representative presets.'),
    ],
    columnGuide: [
      p('Columns. $L$, $V$, $W$ record all labels, output labels, and summed labels. $H_A$, $m_A$ record the declared operand symmetry and operand multiplicity.'),
      p('$|G_{\\mathrm{wreath}}|$ counts candidate row moves before filtering. Recorded counts admissible non-identity relabelings, Identity-only counts admissible moves whose induced relabeling is the identity, Rejected counts failed fingerprint checks, and $|G_{\\mathrm{pt}}|$ is the final detected pointwise group size.'),
    ],
    followups: [
      l('Frobenius.'),
      p('The operand swap is admissible, but the induced relabeling stays the identity, so no non-identity pointwise symmetry is recorded.'),
      l('Triangle.'),
      p('The same preset displays both accepted and rejected row moves, so the row-level boundary is visible in one table.'),
    ],
  },
} satisfies SectionCopy;

export default section1;
